CREATE TABLE "DOCSUBDIVISION" (
"INNERID" VARCHAR2(255 BYTE),
"COMEFROMSITENAME" VARCHAR2(255 BYTE),
"DOCTYPENAME" VARCHAR2(255 BYTE),
"DOCTYPEINNERNAME" VARCHAR2(255 BYTE) ,
"LOCALDOCTYPENAME" VARCHAR2(255 BYTE),
"LOCALDOCTYPEINNERNAME" VARCHAR2(255 BYTE) 
)

