
  CREATE TABLE "PDM10"."GWCHAOMULUMEMBERLINK"
   (	"YQJNUMBER" VARCHAR2(200 BYTE) NOT NULL ENABLE,
	"ORDERNUMBER" VARCHAR2(200 BYTE) NOT NULL ENABLE,
	"BPMWORKFLOWID" VARCHAR2(200 BYTE),
	"BPMWORKFLOWNUMBER" VARCHAR2(200 BYTE),
	"EXTERNALTYPEID" VARCHAR2(20 BYTE),
	"YQJNAME" VARCHAR2(200 BYTE),
	"YQJVERSION" VARCHAR2(20 BYTE),
	 CONSTRAINT "CHAOMULUMEMBERLINK_PK" PRIMARY KEY ("YQJNUMBER", "ORDERNUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

