create table MODELTYPEATTRIBUTEINFO(
ATTRIBUTE_ZH VARCHAR2(255),
ATTRIBUTE_US VARCHAR2(255),
SAST_ATTRIBUTE_ZH VARCHAR2(255),
SAST_ATTRIBUTE_US VARCHAR2(255),
SAST_MODELTYPE_ZH VARCHAR2(255),
SAST_MODELTYPE_US VARCHAR2(255),
SYNC_TIME LONG
)