CREATE TABLE "RECEIVEDMODELTYPE" (
"ID" VARCHAR2(255 BYTE),
"SAST_MODELTYPEID" VARCHAR2(255 BYTE),
"SAST_MODELTYPENAME" VARCHAR2(255 BYTE),
"LOCAL_MODELTYPEID" VARCHAR2(255 BYTE),
"LOCAL_MODELTYPENAME" VARCHAR2(255 BYTE)  
)
