CREATE TABLE "RECEIVESCOPEMODELTYPE" (
"PARENT_MODELTYPE_ID" VARCHAR2(255 BYTE),
"PARENT_MODELTYPE_NAME" VARCHAR2(255 BYTE),
"MODELTYPE_ID" VARCHAR2(255 BYTE),
"MODELTYPE_NAME" VARCHAR2(255 BYTE) 
)

