/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.glaway.mpm.qmIntf.resourceTree;

import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.border.TitledBorder;

import com.glaway.mpm.view.NewTechnicsPart;

/**
 *
 * @author ylshao
 */
public class RsInfoPanel extends javax.swing.JPanel {

	private NewTechnicsPart frame;

	/**
	 * Creates new form EpInfoPanel
	 */
	public RsInfoPanel(NewTechnicsPart frame) {
		this.frame = frame;
		initComponents();
		initAction();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		setBorder(new TitledBorder(null, "基本信息",
				TitledBorder.DEFAULT_JUSTIFICATION,
				TitledBorder.DEFAULT_POSITION, null, null));

		jLabel1 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();

		jLabel11 = new javax.swing.JLabel();
		jLabel11.setVisible(false);
		jLabel12 = new javax.swing.JLabel();
		jLabel12.setVisible(false);
		jLabel13 = new javax.swing.JLabel();
		jLabel13.setVisible(false);
		jLabel14 = new javax.swing.JLabel();
		jLabel14.setVisible(false);
		jLabel15 = new javax.swing.JLabel();
		jLabel15.setVisible(false);
		jLabel16 = new javax.swing.JLabel();
		jLabel16.setVisible(false);
		jLabel21 = new javax.swing.JLabel();
		jLabel21.setVisible(false);
		jLabel22 = new javax.swing.JLabel();
		jLabel22.setVisible(false);
		jLabel23 = new javax.swing.JLabel();
		jLabel23.setVisible(false);
		jLabel24 = new javax.swing.JLabel();
		jLabel24.setVisible(false);
		jLabel25 = new javax.swing.JLabel();
		jLabel25.setVisible(false);
		jLabel26 = new javax.swing.JLabel();
		jLabel26.setVisible(false);
		jLabel31 = new javax.swing.JLabel();
		jLabel31.setVisible(false);
		jLabel32 = new javax.swing.JLabel();
		jLabel32.setVisible(false);
		jLabel33 = new javax.swing.JLabel();
		jLabel33.setVisible(false);
		jLabel34 = new javax.swing.JLabel();
		jLabel34.setVisible(false);
		jLabel35 = new javax.swing.JLabel();
		jLabel35.setVisible(false);
		jLabel36 = new javax.swing.JLabel();
		jLabel36.setVisible(false);
		jLabel37 = new javax.swing.JLabel();
		jLabel37.setVisible(false);
		jLabel38 = new javax.swing.JLabel();
		jLabel38.setVisible(false);
		jLabel39 = new javax.swing.JLabel();
		jLabel39.setVisible(false);
		jLabel40 = new javax.swing.JLabel();
		jLabel40.setVisible(false);
		jLabel41 = new javax.swing.JLabel();
		jLabel41.setVisible(false);
		jLabel42 = new javax.swing.JLabel();
		jLabel42.setVisible(false);
		jLabel43 = new javax.swing.JLabel();
		jLabel43.setVisible(false);
		jLabel44 = new javax.swing.JLabel();
		jLabel44.setVisible(false);
		jLabel45 = new javax.swing.JLabel();
		jLabel45.setVisible(false);
		jLabel46 = new javax.swing.JLabel();
		jLabel46.setVisible(false);
		jLabel47 = new javax.swing.JLabel();
		jLabel47.setVisible(false);
		jLabel48 = new javax.swing.JLabel();
		jLabel48.setVisible(false);

		jLabel1.setText("编号：");
		jLabel3.setText("名称：");
		jLabel5.setText("类别：");
		jLabel11.setText("刃口直径：");
		jLabel13.setText("夹持直径：");
		jLabel15.setText("刃口长度：");
		jLabel21.setText("总长度：");
		jLabel23.setText("公差：");
		jLabel25.setText("最小加工尺寸：");
		jLabel31.setText("最大加工尺寸：");
		jLabel33.setText("结构形式：");
		jLabel35.setText("接口类型：");
		jLabel37.setText("技术备注：");
		jLabel39.setText("刃口圆角半径：");
		jLabel41.setText("类别：");

		GroupLayout layout = new GroupLayout(this);
		this.setLayout(layout);

		GroupLayout.SequentialGroup hGroup = layout.createSequentialGroup();
		hGroup.addGroup(
				layout.createParallelGroup().addComponent(
						jLabel1,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel3,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel5,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel11,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel13,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel15,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel21,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel23,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel25,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel31,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel33,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel35,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel37,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel39,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel41,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel43,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel45,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel47,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				);
		hGroup.addGroup(
				layout.createParallelGroup().addComponent(
						jLabel2,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel4,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel6,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel12,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel14,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel16,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel22,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel24,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel26,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel32,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel34,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel36,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel38,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel40,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel42,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel44,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)

				.addComponent(
						jLabel46,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jLabel48,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				);

		GroupLayout.SequentialGroup vGroup = layout.createSequentialGroup();

        vGroup.addGroup(layout.createParallelGroup().addComponent(jLabel1).addComponent(jLabel2));
        vGroup.addGroup(layout.createParallelGroup().addComponent(jLabel3).addComponent(jLabel4));
        vGroup.addGroup(layout.createParallelGroup().addComponent(jLabel5).addComponent(jLabel6));
        vGroup.addGroup(layout.createParallelGroup().addComponent(jLabel11).addComponent(jLabel12));
        vGroup.addGroup(layout.createParallelGroup().addComponent(jLabel13).addComponent(jLabel14));
        vGroup.addGroup(layout.createParallelGroup().addComponent(jLabel15).addComponent(jLabel16));
        vGroup.addGroup(layout.createParallelGroup().addComponent(jLabel21).addComponent(jLabel22));
        vGroup.addGroup(layout.createParallelGroup().addComponent(jLabel23).addComponent(jLabel24));
        vGroup.addGroup(layout.createParallelGroup().addComponent(jLabel25).addComponent(jLabel26));
        vGroup.addGroup(layout.createParallelGroup().addComponent(jLabel31).addComponent(jLabel32));
        vGroup.addGroup(layout.createParallelGroup().addComponent(jLabel33).addComponent(jLabel34));
        vGroup.addGroup(layout.createParallelGroup().addComponent(jLabel35).addComponent(jLabel36));

        vGroup.addGroup(layout.createParallelGroup().addComponent(jLabel37).addComponent(jLabel38));
        vGroup.addGroup(layout.createParallelGroup().addComponent(jLabel39).addComponent(jLabel40));
        vGroup.addGroup(layout.createParallelGroup().addComponent(jLabel41).addComponent(jLabel42));
        vGroup.addGroup(layout.createParallelGroup().addComponent(jLabel43).addComponent(jLabel44));
        vGroup.addGroup(layout.createParallelGroup().addComponent(jLabel45).addComponent(jLabel46));
        vGroup.addGroup(layout.createParallelGroup().addComponent(jLabel47).addComponent(jLabel48));

		layout.setHorizontalGroup(hGroup);
		layout.setVerticalGroup(vGroup);
	}

	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;



	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;


	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel23;
	private javax.swing.JLabel jLabel24;
	private javax.swing.JLabel jLabel25;
	private javax.swing.JLabel jLabel26;


	private javax.swing.JLabel jLabel31;
	private javax.swing.JLabel jLabel32;
	private javax.swing.JLabel jLabel33;
	private javax.swing.JLabel jLabel34;
	private javax.swing.JLabel jLabel35;
	private javax.swing.JLabel jLabel36;

	private javax.swing.JLabel jLabel37;
	private javax.swing.JLabel jLabel38;

	private javax.swing.JLabel jLabel39;
	private javax.swing.JLabel jLabel40;

	private javax.swing.JLabel jLabel41;
	private javax.swing.JLabel jLabel42;

	private javax.swing.JLabel jLabel43;
	private javax.swing.JLabel jLabel44;

	private javax.swing.JLabel jLabel45;
	private javax.swing.JLabel jLabel46;

	private javax.swing.JLabel jLabel47;
	private javax.swing.JLabel jLabel48;

	// End of variables declaration

	public JLabel getjLabel1() {
		return jLabel1;
	}

	public void setjLabel1(JLabel jLabel1) {
		this.jLabel1 = jLabel1;
	}

	public JLabel getjLabel2() {
		return jLabel2;
	}

	public void setjLabel2(JLabel jLabel2) {
		this.jLabel2 = jLabel2;
	}

	public JLabel getjLabel3() {
		return jLabel3;
	}

	public void setjLabel3(JLabel jLabel3) {
		this.jLabel3 = jLabel3;
	}

	public JLabel getjLabel4() {
		return jLabel4;
	}

	public void setjLabel4(JLabel jLabel4) {
		this.jLabel4 = jLabel4;
	}

	public JLabel getjLabel5() {
		return jLabel5;
	}

	public void setjLabel5(JLabel jLabel5) {
		this.jLabel5 = jLabel5;
	}

	public JLabel getjLabel6() {
		return jLabel6;
	}

	public void setjLabel6(JLabel jLabel6) {
		this.jLabel6 = jLabel6;
	}



	public javax.swing.JLabel getjLabel11() {
		return jLabel11;
	}

	public void setjLabel11(javax.swing.JLabel jLabel11) {
		this.jLabel11 = jLabel11;
	}

	public javax.swing.JLabel getjLabel12() {
		return jLabel12;
	}

	public void setjLabel12(javax.swing.JLabel jLabel12) {
		this.jLabel12 = jLabel12;
	}

	public javax.swing.JLabel getjLabel13() {
		return jLabel13;
	}

	public void setjLabel13(javax.swing.JLabel jLabel13) {
		this.jLabel13 = jLabel13;
	}

	public javax.swing.JLabel getjLabel14() {
		return jLabel14;
	}

	public void setjLabel14(javax.swing.JLabel jLabel14) {
		this.jLabel14 = jLabel14;
	}

	public javax.swing.JLabel getjLabel15() {
		return jLabel15;
	}

	public void setjLabel15(javax.swing.JLabel jLabel15) {
		this.jLabel15 = jLabel15;
	}

	public javax.swing.JLabel getjLabel16() {
		return jLabel16;
	}

	public void setjLabel16(javax.swing.JLabel jLabel16) {
		this.jLabel16 = jLabel16;
	}

	public javax.swing.JLabel getjLabel21() {
		return jLabel21;
	}

	public void setjLabel21(javax.swing.JLabel jLabel21) {
		this.jLabel21 = jLabel21;
	}

	public javax.swing.JLabel getjLabel22() {
		return jLabel22;
	}

	public void setjLabel22(javax.swing.JLabel jLabel22) {
		this.jLabel22 = jLabel22;
	}

	public javax.swing.JLabel getjLabel23() {
		return jLabel23;
	}

	public void setjLabel23(javax.swing.JLabel jLabel23) {
		this.jLabel23 = jLabel23;
	}

	public javax.swing.JLabel getjLabel24() {
		return jLabel24;
	}

	public void setjLabel24(javax.swing.JLabel jLabel24) {
		this.jLabel24 = jLabel24;
	}

	public javax.swing.JLabel getjLabel25() {
		return jLabel25;
	}

	public void setjLabel25(javax.swing.JLabel jLabel25) {
		this.jLabel25 = jLabel25;
	}

	public javax.swing.JLabel getjLabel26() {
		return jLabel26;
	}

	public void setjLabel26(javax.swing.JLabel jLabel26) {
		this.jLabel26 = jLabel26;
	}

	public javax.swing.JLabel getjLabel31() {
		return jLabel31;
	}

	public void setjLabel31(javax.swing.JLabel jLabel31) {
		this.jLabel31 = jLabel31;
	}

	public javax.swing.JLabel getjLabel32() {
		return jLabel32;
	}

	public void setjLabel32(javax.swing.JLabel jLabel32) {
		this.jLabel32 = jLabel32;
	}

	public javax.swing.JLabel getjLabel33() {
		return jLabel33;
	}

	public void setjLabel33(javax.swing.JLabel jLabel33) {
		this.jLabel33 = jLabel33;
	}

	public javax.swing.JLabel getjLabel34() {
		return jLabel34;
	}

	public void setjLabel34(javax.swing.JLabel jLabel34) {
		this.jLabel34 = jLabel34;
	}

	public javax.swing.JLabel getjLabel35() {
		return jLabel35;
	}

	public void setjLabel35(javax.swing.JLabel jLabel35) {
		this.jLabel35 = jLabel35;
	}

	public javax.swing.JLabel getjLabel36() {
		return jLabel36;
	}

	public void setjLabel36(javax.swing.JLabel jLabel36) {
		this.jLabel36 = jLabel36;
	}

	public javax.swing.JLabel getjLabel37() {
		return jLabel37;
	}

	public void setjLabel37(javax.swing.JLabel jLabel37) {
		this.jLabel37 = jLabel37;
	}

	public javax.swing.JLabel getjLabel38() {
		return jLabel38;
	}

	public void setjLabel38(javax.swing.JLabel jLabel38) {
		this.jLabel38 = jLabel38;
	}

	public javax.swing.JLabel getjLabel39() {
		return jLabel39;
	}

	public void setjLabel39(javax.swing.JLabel jLabel39) {
		this.jLabel39 = jLabel39;
	}

	public javax.swing.JLabel getjLabel40() {
		return jLabel40;
	}

	public void setjLabel40(javax.swing.JLabel jLabel40) {
		this.jLabel40 = jLabel40;
	}

	public javax.swing.JLabel getjLabel41() {
		return jLabel41;
	}

	public void setjLabel41(javax.swing.JLabel jLabel41) {
		this.jLabel41 = jLabel41;
	}

	public javax.swing.JLabel getjLabel42() {
		return jLabel42;
	}

	public void setjLabel42(javax.swing.JLabel jLabel42) {
		this.jLabel42 = jLabel42;
	}

	public javax.swing.JLabel getjLabel43() {
		return jLabel43;
	}

	public void setjLabel43(javax.swing.JLabel jLabel43) {
		this.jLabel43 = jLabel43;
	}

	public javax.swing.JLabel getjLabel44() {
		return jLabel44;
	}

	public void setjLabel44(javax.swing.JLabel jLabel44) {
		this.jLabel44 = jLabel44;
	}

	public javax.swing.JLabel getjLabel45() {
		return jLabel45;
	}

	public void setjLabel45(javax.swing.JLabel jLabel45) {
		this.jLabel45 = jLabel45;
	}

	public javax.swing.JLabel getjLabel46() {
		return jLabel46;
	}

	public void setjLabel46(javax.swing.JLabel jLabel46) {
		this.jLabel46 = jLabel46;
	}

	public javax.swing.JLabel getjLabel47() {
		return jLabel47;
	}

	public void setjLabel47(javax.swing.JLabel jLabel47) {
		this.jLabel47 = jLabel47;
	}

	public javax.swing.JLabel getjLabel48() {
		return jLabel48;
	}

	public void setjLabel48(javax.swing.JLabel jLabel48) {
		this.jLabel48 = jLabel48;
	}

	private void initAction() {
//		jLabel9.setForeground(UIManager.getColor("Tree.selectionBackground"));
//		jLabel9.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
//		jLabel9.addMouseListener(new MouseAdapter() {
//			@Override
//			public void mouseClicked(MouseEvent e) {
//				Map map = new HashMap();
//				String text = jLabel9.getText();
//				String frockCardNum = text.substring(0, text.indexOf("_"));
//				map.put("number", frockCardNum);
//				FrockCardSearchDialog dialog = new FrockCardSearchDialog(frame,
//						null);
//				dialog.showDialog(ResourceIntf.showFrockCard(map));
//
//			}
//		});
	}
}
