##############################################
# font mapping property file                 #
# created and edited by xiong dai jun,QM,FAW #
# all rights reserved                        #
##############################################
Arial=ARIAL.TTF
ArialBlack=ARIBLK.TTF
ArialBlackCursiva=
ArialCursiva=
ArialNarrow=ARIALN.TTF
ArialNarrowCursiva=
ArialNarrowNegreta=
ArialNarrowNegretacursiva=
ArialNegreta=
ArialNegretacursiva=
BankGothicLightBT=bgothl.ttf
BankGothicMediumBT=bgothm.ttf
BitstreamVeraSansMono=VeraMono.ttf
BookAntiqua=BKANT.TTF
BookAntiquaCursiva=
BookAntiquaNegreta=
BookAntiquaNegretacursiva=
BookmanOldStyle=BOOKOS.TTF
BookmanOldStyleCursiva=
BookmanOldStyleNegreta=
BookmanOldStyleNegretacursiva=
CenturyGothic=Gothic.TTF
CenturyGothicCursiva=
CenturyGothicNegreta=
CenturyGothicNegretacursiva=
CityBlueprint=cityb___.ttf
ComicSansMS=comic.ttf
ComicSansMSNegreta=
CommercialPiBT=compi.ttf
CommercialScriptBT=comsc.ttf
Complex=complex_.ttf
CountryBlueprint=counb___.ttf
CourierNew=COUR.TTF
CourierNewCursiva=
CourierNewNegreta=
CourierNewNegretacursiva=
Dutch801BoldBT=dutchb.ttf
Dutch801BoldItalicBT=dutchbi.ttf
Dutch801ExtraBoldBT=dutcheb.ttf
Dutch801ItalicBT=dutchi.ttf
Dutch801RomanBT=dutch.ttf
EuroRoman=eurr____.ttf
EuroRomanOblique=eurro___.ttf
方正舒体=FZSTK.TTF
方正姚体=FZYTK.TTF
仿宋_GB2312=SIMFANG.TTF
GDT=gdt_____.ttf
Garamond=GARA.TTF
GaramondCursiva=
GaramondNegreta=
Georgia= georgia
GeorgiaCursiva=
GeorgiaNegreta=
GeorgiaNegretacursiva=
GothicE=gothice_.ttf
GothicG=gothicg_.ttf
GothicI=gothici_.ttf
GreekC=greekc__.ttf
GreekS=greeds__.ttf
ISOCP=isocp___.ttf
ISOCP2=isocp2__.ttf
ISOCP3=isocp3__.ttf
ISOCPEUR=isocpeur.ttf
ISOCPEURItalic=isocpeui.ttf
ISOCT=isoct___.ttf
ISOCT2=isoct2__.ttf
ISOCT3=isoct3__.ttf
ISOCTEUR=isocpeur.ttf
ISOCTEURItalic=isocpeui.ttf
Impact=
Italic=italic__.ttf
ItalicC=iatlicc_.ttf
ItalicT=italict_.ttf
楷体_GB2312=SIMKAI.TTF
隶书=SIMLI.TTF
LucidaBrightDemibold=
LucidaBrightDemiboldItalic=
LucidaBrightItalic=
LucidaBrightRegular=
LucidaConsole=LUCON.TTF
LucidaSansDemibold=
LucidaSansRegular=
LucidaSansTypewriterBold=
LucidaSansTypewriterRegular=
LucidaSansUnicode=L_10646.TTF
Marlett=
MicrosoftSansSerif=
Monospace821BT=
Monospace821BoldBT=monos.ttf
Monospace821BoldItalicBT=monosbi.ttf
Monospace821ItalicBT=monosi.ttf
Monotxt=monotxt_.ttf
MonotypeCorsiva=MTCORSVA.TTF
新宋体=SIMSUN.TTC
PalatinoLinotype=pala
PalatinoLinotypeCursiva=
PalatinoLinotypeNegreta=
PalatinoLinotypeNegretacursiva=
PanRoman=panroman.ttf
Proxy1=mtproxy1.ttf
Proxy2=mtproxy2.ttf
Proxy3=mtproxy3.ttf
Proxy4=mtproxy4.ttf
Proxy5=mtproxy5.ttf
Proxy6=mtproxy6.ttf
Proxy7=mtproxy7.ttf
Proxy8=mtproxy8.ttf
Proxy9=mtproxy9.ttf
RomanC=romanc__.ttf
RomanD=romand__.ttf
RomanS=romans__.ttf
RomanT=romant__.ttf
Romantic=romantic.ttf
RomanticBold=romab___.ttf
RomanticItalic=romai___.ttf
华文彩云=STCAIYUN.TTF
华文仿宋=STFANGSO.TTF
华文细黑=STXIHEI.TTF
华文行楷=STXINGKA.TTF
华文新魏=STXINEI.TTF
华文中宋=STZHONGS.TTF
SWAstro=swastro.ttf
SWComp=swcomp.ttf
SWGDT=swgdt.ttf
SWGothe=swgothe.ttf
SWGothg=swthg.ttf
SWGothi=swgothi.ttf
SWGrekc=swgreck.ttf
SWGreks=swgreks.ttf
SWIsop1=swisop1.ttf
SWIsop2=swisop2.ttf
SWIsop3=swisop3.ttf
SWIsot1=swisot1.ttf
SWIsot2=swisot2.ttf
SWIsot3=swisot3.ttf
SWItal=swital.ttf
SWItalc=switalc.ttf
SWItalt=switalt.ttf
SWMap=swmap.ttf
SWMath=swmath.ttf
SWMeteo=swmeteo.ttf
SWMono=swmono.ttf
SWMusic=swmusic.ttf
SWRomnc=swromnc.ttf
SWRomnd=swromnd.ttf
SWRomns=swromns.ttf
SWRomnt=swromnt.ttf
SWScrpc=swscrpc.ttf
SWScrps=swscrps.ttf
SWSimp=swsimp.ttf
SWTxt=swtxt.ttf
SansSerif.plain=sanss___.ttf
SansSerifBold=sanssb__.ttf
SansSerifBoldOblique=sanssbo_.ttf
SansSerifOblique=sansso__.ttf
ScriptC=scriptc_.ttf
ScriptS=srcipts_.ttf
黑体=SIMHEI.TTF
宋体=SIMSUN.TTC
Simplex=simplex_.ttf
宋体-方正超大字符集=SURSONG.TTF
StylusBT=stylu.ttf
SuperFrench=supef___.ttf
Swiss721BT=swiss.ttf
Swiss721BlackBT=swissk.ttf
Swiss721BlackCondensedBT=swissck.ttf
Swiss721BlackCondensedItalicBT=swisski.ttf
Swiss721BlackExtendedBT=swissek.ttf
Swiss721BlackItalicBT=swisski.ttf
Swiss721BlackOutlineBT=swissko.ttf
Swiss721BoldBT=swissb.ttf
Swiss721BoldCondensedBT=swisscb.ttf
Swiss721BoldCondensedItalicBT=swisscbi.ttf
Swiss721BoldCondensedOutlineBT=swisscbo.ttf
Swiss721BoldExtendedBT=swisseb.ttf
Swiss721BoldItalicBT=swissbi.ttf
Swiss721BoldOutlineBT=swissbo.ttf
Swiss721CondensedBT=swissc.ttf
Swiss721CondensedItalicBT=swissci.ttf
Swiss721ExtendedBT=swisse.ttf
Swiss721ItalicBT=swissi.ttf
Swiss721LightBT=swissl.ttf
Swiss721LightCondensedBT=swisscl.ttf
Swiss721LightCondensedItalicBT=swisscli.ttf
Swiss721LightExtendedBT=swissel.ttf
Swiss721LightItalicBT=swissli.ttf
Syastro=syastro_.ttf
Symap=symap___.ttf
Symath=symath__.ttf
Symbol=symbol.ttf
Symeteo=symeteo.ttf
Symusic=symusic_.ttf
Tahoma=TAHOMA.TTF
TahomaNegreta=
Technic=technic_.ttf
TechnicBold=techb___.ttf
TechnicLite=techl___.ttf
TimesNewRoman=TIMES.TTF
TimesNewRomanNegreta=
TimesNewRomanNegretacursiva=
TimesNewRomancursiva=
TrebuchetMS=trebuc
TrebuchetMSCursiva=
TrebuchetMSNegreta=
TrebuchetMSNegretacursiva=
Txt=txt_____.ttf
UniversalMath1BT=umath.ttf
Verdana=verdana
VerdanaCursiva=
VerdanaNegreta=
VerdanaNegretacursiva=
VinetaBT=vinet.ttf
Webdings=webdings.ttf
Wingdings=WINGDING.TTF
Wingdings2=WINGDING2.TTF
Wingdings3=WINGDING3.TTF
幼圆=SIMYOU.TTF
ZWAdobeF=ZWAdebeF.TTF
dialog.bold=
dialog.bolditalic=
dialog.italic=
dialog.plain=
dialoginput.bold=
dialoginput.bolditalic=
dialoginput.italic=
dialoginput.plain=
monospaced.bold=
monospaced.bolditalic=
monospaced.italic=
monospaced.plain=
sansserif.bold=
sansserif.bolditalic=
sansserif.italic=
sansserif.plain=
serif.bold=
serif.bolditalic=
serif.italic=
serif.plain=
DefaultFontFile=txt.ttf