#Menu definition
Title = JCad

menubar = file edit view draw modify option format help
file = new open save - exportsvg exportimage- print - exit
fileLabel=File
openLabel=Open
openImage=/images/open.gif
newLabel=New
newImage=/images/new.gif
saveLabel=Save
saveImage=/images/save.gif
exportsvgLabel=Export SVG
exportsvgImage=/images/export.gif
exportimageLabel=Export Image
exportsvgImage=/images/export.gif
printLabel=Print
printImage=/images/print.gif
exitLabel=Exit
recentfileLabel=Recent Files

edit = undo redo - cut copy paste - deleteentity editentity blockentity
editLabel=Edit
undoLabel=Undo
undoImage=/images/undo.gif
redoLabel=Redo
redoImage=/images/redo.gif
deleteentityLabel=Delete Entity
deleteentityImage=/images/deleteentity.gif
editentityLabel=Edit Entity
editentityImage=/images/editentity.gif
blockentityLabel=Block Entity
blockentityImage=/images/blockentity.gif
cutLabel=Cut
copyLabel=Copy
pasteLabel=Paste
cutImage=/images/cut.gif
copyImage=/images/copy.gif
pasteImage=/images/paste.gif
redrawLabel=Redraw
redrawImage=/images/redraw.gif

help = viewhelp about
helpLabel=Help
viewhelpLabel=View Help
aboutLabel=About

option = editoption
optionLabel=Option
editoptionLabel=Edit Option

view = redraw - zoomin zoomout zoompage zoomwindow zoomentity
viewLabel=View
zoominLabel=Zoom In
zoomoutLabel=Zoom Out
zoompageLabel=Zoom to Page
zoomwindowLabel=Zoom Window
zoomentityLabel=Zoom to Entity
redrawImage=/images/zoomredraw.gif
zoominImage=/images/zoomincrease.gif
zoomoutImage=/images/zoomdecrease.gif
zoompageImage=/images/zoomtopage.gif
zoomwindowImage=/images/zoomwindow.gif
zoomentityImage=/images/zoomwindow.gif

draw = drawline drawsolid drawcircle drawarc drawtext drawpolygon drawellipse
drawLabel = Draw
drawlineLabel = Line
drawpolygonLabel=Polygon
drawellipseLabel=Ellipse
drawsolidLabel=Solid
drawcircleLabel = Circle
drawlineImage=/images/line.gif
drawpolygonImage=/images/polygon.gif
drawellipseImage=/images/ellipse.gif
drawsolidImage=/images/solid.gif
drawcircleImage=/images/circle.gif
drawarcLabel = Arc
drawarcImage=/images/arc.gif
drawtextLabel = Text

modify = moveentity mirrorentity scaleentity stretchentity rotateentity roundentity
modifyLabel = Modify
moveentityLabel = Move
moveentityImage=/images/moveentity.gif
mirrorentityLabel = Mirror
mirrorentityImage=/images/mirrorentity.gif
scaleentityLabel = Scale
scaleentityImage=/images/scaleentity.gif
stretchentityLabel = Stretch
stretchentityImage=/images/stretchentity.gif
rotateentityLabel = Rotate
rotateentityImage=/images/rotateentity.gif
roundentityLabel = Round
roundentityImage=/images/roundentity.gif

format = layer linetype block
formatLabel=Format
layerLabel=Layer
layerImage=/images/layer.gif
linetypeLabel=Linetype
blockLabel=Block


# toolbar definition
#
# Each of the strings that follow form a key to be
# used as the basis of the tool definition.  Actions
# are of course sharable, and in this case are shared
# with the menu items.
maintoolbar=new open save - print - cut copy paste - undo redo - redraw - zoomin zoomout zoompage zoomwindow zoomentity - layer
newTooltip=Create a new file
openTooltip=Open a file
saveTooltip=Save to a file
cutTooltip=Move selection to clipboard
copyTooltip=Copy selection to clipboard
pasteTooltip=Paste clipboard to selection
zoominTooltip=Zoom increase
zoomoutTooltip=Zoom decrease
zoompageTooltip=Zoom to Page
zoomwindowTooltip=Zoom Window
zoomentityTooltip=Zoom to Entity

Margin = 10
#right click menu definition
rightclick =  cancel zoomin zoomout deleteentity editentity
cancelLabel = Cancel
##########################################
drawtoolbar = drawline drawsolid drawcircle drawarc drawtext - deleteentity editentity blockentity - moveentity mirrorentity scaleentity stretchentity rotateentity roundentity drawpolygon drawellipse
drawlineTooltip =Line
drawpolygonTooltip=Polygon
drawellipseTooltip=Ellipse
drawsolid=Solid
drawcircleTooltip =Circle
drawarcTooltip =Arc
drawtextTooltip =Text
deleteentityTooltip =Delete Entity
editentityTooltip =Edit Entity
moveentityTooltip =Move Entity
mirrorentityTooltip =Mirror Entity
scaleentityTooltip =Scale Entity
strethentityTooltip =Stretch Entity
rotateentityTooltip =Rotate Entity
roundentityTooltip =Round Entity

drawcircleOption = CIRCLE(3P) CIRCLE(CR)
#3P:three points
#CR:Center Radius
CIRCLE(3P)Label = 3 Points
CIRCLE(CR)Label = Center,Radius
CIRCLE(CR)Action = drawcircle
CIRCLE(3P)Action = drawcircle3p
CIRCLE(3P)Image = /images/circle3p.gif
CIRCLE(CR)Image = /images/circlecr.gif
drawarcOption = ARC(CSE) ARC(CR2A) ARC(3P)
ARC(CSE)Label = Center,Start Point,End Point
ARC(CR2A)Label = Center,Radius,Start Angle,Stop Angle
ARC(3P)Label = Start Point,End Point,Point on Arc
ARC(CSE)Action = drawarccse
ARC(CR2A)Action = drawarc3p
ARC(3P)Action = drawarc3p
ARC(CSE)Image = /images/arccse.gif
ARC(3P)Image = /images/arc3p.gif
drawtextImage=/images/text.gif

#Titles of Dialog
aboutTitle=About
exitTitle=Exit
editentitypropertyTitle=Edit Entity Property
#Labels of Button and other components
common.okLabel=OK
common.CancelLabel=Cancel
common.cancelLabel=Cancel
common.ApplyLabel=Apply
common.applyLabel=Apply
common.nameLabel=Name
common.colorLabel=Color
common.onLabel=On
common.frozenLabel=Frozen
common.defaultLabel=Default
common.linetypeLabel=Linetype
common.newLabel=New
common.closeLabel=Close
common.deleteLabel=Delete
common.edit=Edit
file.untitledLabel=Untitled
helpviewer.title=View Help
helpviewer.url=URL

OKLabel=OK
CancelLabel=Cancel
statusbarLabel=Status Bar
currentlinetypeLabel=Current Linetype:
currentlayerLabel=Current Layer:
orthoLabel=Ortho
usevalueLabel=Use Value
usecoordinateLabel=Use Coordinate
confirmLabel=Confirm
currentlocationLabel=Current Location
#Snap Methods
endpointLabel=End Point
midpointLabel=Mid Point
centerLabel=Center
intersectLabel=Intersect Point
quadrantLabel=Quadrant Point

optionsTitle=Options
options.general.label=General

colorLabel=Color
thicknessLabel=Thickness
deleteLabel=Delete

layerdialog.freeze/thawLabel=Freeze/Thaw
layerdialog.on/offLabel=On/Off
layerdialog.setdefaultLabel=Set Default

blockentitydialog_orgpointLabel=Origin Point

modifyentityaction.message=Please select some entitiy(s) first

styleLabel=Style
horizonalalignmentLabel=Horizonal Alignment
heightLabel=Height
textLabel=Text
nameLabel=Name

optionsTitle=Options
historyLabel=History
#Messages
mirrorentity_selectaxisMessage=Please select the mirror axis
mirrorentity_selectentityMessage=Please select entity(s) to mirror
roundentity_selectline1Message=Please select the first line
roundentity_selectline2Message=Please select the second line
exitMessage=Do you really want to exit???
aboutMessage=JCad,a smart 2D CAD Drafting Program with Pure 100% Java,Please visit us at http://javacad.sourceforge.net
forQM=false
