package com.glaway.mpm.visual.view.ui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dialog;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

import javax.media.j3d.BoundingBox;																		
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.vecmath.Point3d;

import wt.method.RemoteMethodServer;


import com.glaway.mpm.visual.log.VaLogger;
import com.glaway.mpm.visual.util.VaGuiUtil;
import com.glaway.mpm.visual.view.VaContext;
import com.glaway.mpm.visual.view.action.VaAction;
import com.glaway.mpm.visual.view.action.VaPViewZoomAll;
import com.glaway.mpm.visual.view.action.VaPViewZoomSelected;
import com.glaway.mpm.visual.view.pview.VaEPVSelectionObserver;
import com.glaway.mpm.visual.view.pview.VaEPViewStructureGenerator;
import com.glaway.mpm.visual.view.pview.VaPViewFactory;
import com.glaway.mpm.visual.view.pview.VaPViewGenerator;
import com.glaway.mpm.visual.view.pview.VaPViewImpl;
import com.glaway.mpm.visual.view.pview.VaPViewNode;
import com.glaway.mpm.visual.view.pview.VaPViewNodeGenerator;
import com.glaway.mpm.visual.view.tree.VaTree;
import com.glaway.mpm.visual.view.tree.VaTreeNode;
import com.glaway.mpm.visual.view.tree.VaTreeSelectionListener;
import com.ptc.pview.pvapi.SelectionObserver;
import com.ptc.pview.utils.dom.ActorShutdownException;
import com.ptc.pview.utils.dom.ConnectionLostException;
import com.ptc.pview.utils.dom.InvalidActorException;
import com.ptc.pview.utils.dom.MessageProtocolException;

public class VaPartDialog extends JDialog {
	private static VaPartDialog frame = null;

	public static final int TEXTFIELD_SIZE = 21;
	public static final int TEXTFIELD_SIZE2 = 30;
	
	private String curPartNumber;

	public String getCurPartNumber() {
		return curPartNumber;
	}

	public void setCurPartNumber(String curPartNumber) {
		this.curPartNumber = curPartNumber;
	}

	private static final VaLogger log = VaLogger
			.getLogger(VaTreeSelectionListener.class);

	public static synchronized VaPartDialog getInstance() {
		if (frame == null) {
			frame = new VaPartDialog();
			frame.setAlwaysOnTop(true);
		}
		return frame;
	}

	/**
	 * Creates new form VaMainframe
	 */
	private VaPartDialog() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel4 = new javax.swing.JPanel();
		jTextField1 = new javax.swing.JTextField(TEXTFIELD_SIZE);
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField(TEXTFIELD_SIZE);
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField(TEXTFIELD_SIZE);
		jTextField4 = new javax.swing.JTextField(TEXTFIELD_SIZE);
		jTextField5 = new javax.swing.JTextField(TEXTFIELD_SIZE);
		jTextField6 = new javax.swing.JTextField(TEXTFIELD_SIZE);
		jTextField7 = new javax.swing.JTextField(TEXTFIELD_SIZE2);
		jTextField8 = new javax.swing.JTextField(TEXTFIELD_SIZE2);
		jTextField9 = new javax.swing.JTextField(TEXTFIELD_SIZE2);
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jPanel5 = new javax.swing.JPanel();
		jPanel6 = new javax.swing.JPanel();
		jPanel7 = new javax.swing.JPanel();
		jPanel1 = new javax.swing.JPanel();
		jSplitPane1 = new javax.swing.JSplitPane();

		jScrollPane1 = new VaEBomTreePanel(this);// new
		// javax.swing.JScrollPane();

		jPanel3 = new javax.swing.JPanel();
		// jPanel2 = new //javax.swing.JPanel();
		/** init pview **/

		if (VaPViewImpl.isPviewInitialized()) {
			Thread createPPRunner = new Thread() {
				public void run() {
					try {
						jPanel2 = new VaPViewScenesPanel(
								VaPViewFactory.PV_NAME_MBOM,null);

						jSplitPane1.setRightComponent(jPanel2);

					} catch (Exception ex) {
						ex.printStackTrace();
					}

				}
			};
			createPPRunner.start();
		} else
			jSplitPane1.setRightComponent(new VaPVNotInstalledPanel());
		// setBorder(new EmptyBorder(0, 0, 0, 0));

		jTabbedPane4 = new javax.swing.JTabbedPane();

		setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
		setPreferredSize(new java.awt.Dimension(800, 600));

		jPanel4.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel7.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		// jTextField1.setText("jTextField1");
		jLabel1.setText("X1");

		jLabel2.setText("X2");

		// jTextField2.setText("jTextField2");

		jLabel3.setText("Y1");

		jLabel4.setText("Y2");

		// jTextField3.setText("jTextField3");

		// jTextField4.setText("jTextField4");

		// jTextField5.setText("jTextField5");

		// jTextField6.setText("jTextField6");

		jLabel5.setText("Z1");

		jLabel6.setText("Z2");

		jButton1.setText("搜寻");
		jButton2.setText("搜寻");

		jLabel7.setText("参考");
		jLabel8.setText("实例");
		jLabel9.setText("距离");

		jButton1.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				searchButtonPerformed(e);
			}
		});
		jButton2.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				searchButtonPerformed(e);
			}
		});

		jLabel10.setText("mm");

		javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(
				jPanel7);
		jPanel7.setLayout(jPanel7Layout);
		jPanel7Layout
				.setHorizontalGroup(jPanel7Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel7Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel7Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel7Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel9)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jTextField9,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel10)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				456,
																				Short.MAX_VALUE)
																		.addComponent(
																				jButton2))
														.addGroup(
																jPanel7Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel7Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel7Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel7)
																										.addGap(
																												18,
																												18,
																												18)
																										.addComponent(
																												jTextField7,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								jPanel7Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel8)
																										.addGap(
																												18,
																												18,
																												18)
																										.addComponent(
																												jTextField8,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addGap(
																				0,
																				0,
																				Short.MAX_VALUE)))
										.addContainerGap(
												14,
												javax.swing.GroupLayout.PREFERRED_SIZE)));
		jPanel7Layout
				.setVerticalGroup(jPanel7Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel7Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel7Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel7Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel7Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel7)
																						.addComponent(
																								jTextField7,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel7Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel8)
																						.addComponent(
																								jTextField8,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel7Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel9)
																						.addComponent(
																								jTextField9,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel10))
																		.addGap(
																				0,
																				0,
																				Short.MAX_VALUE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel7Layout
																		.createSequentialGroup()
																		.addGap(
																				0,
																				0,
																				Short.MAX_VALUE)
																		.addComponent(
																				jButton2)))
										.addContainerGap()));

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																jLabel2,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																jTextField1)
														.addComponent(
																jTextField2))
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel4)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jTextField4,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				jLabel3)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jTextField3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel5)
														.addComponent(jLabel6))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jTextField5,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addContainerGap())
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jTextField6,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				294,
																				Short.MAX_VALUE)
																		.addComponent(
																				jButton1)
																		.addGap(
																				66,
																				66,
																				66)))));
		jPanel4Layout
				.setVerticalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jLabel1,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addGroup(
																								jPanel4Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.BASELINE)
																										.addComponent(
																												jTextField1)
																										.addComponent(
																												jLabel3)
																										.addComponent(
																												jTextField3,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addComponent(
																												jTextField5,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addComponent(
																												jLabel5)))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				24,
																				Short.MAX_VALUE)
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								jPanel4Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING,
																												false)
																										.addComponent(
																												jLabel2,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												jTextField2,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								jPanel4Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.BASELINE)
																										.addComponent(
																												jTextField4,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addComponent(
																												jTextField6,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addComponent(
																												jLabel6)
																										.addComponent(
																												jLabel4))))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel4Layout
																		.createSequentialGroup()
																		.addGap(
																				0,
																				0,
																				Short.MAX_VALUE)
																		.addComponent(
																				jButton1)))
										.addContainerGap()));

		jTabbedPane1.addTab("空间范围", jPanel4);
		jTabbedPane1.addTab("临近空间", jPanel7);

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
				jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 819,
				Short.MAX_VALUE));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 100,
				Short.MAX_VALUE));

		jTabbedPane1.addTab("属性", jPanel5);

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(
				jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 819,
				Short.MAX_VALUE));
		jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 100,
				Short.MAX_VALUE));

		jTabbedPane1.addTab("其它", jPanel6);

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 100,
				Short.MAX_VALUE));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 365,
				Short.MAX_VALUE));

		// jScrollPane1.setViewportView(jPanel3);

		jSplitPane1.setLeftComponent(jScrollPane1);

		// javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
		// jPanel2);
		// jPanel2.setLayout(jPanel2Layout);
		// jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
		// javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 790,
		// Short.MAX_VALUE));
		// jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
		// javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 356,
		// Short.MAX_VALUE));

		// ////

		// /////
		// jSplitPane1.setRightComponent(jPanel2);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0,
				Short.MAX_VALUE).addGroup(
				jPanel1Layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.LEADING).addGroup(
						jPanel1Layout.createSequentialGroup().addGap(0, 0,
								Short.MAX_VALUE).addComponent(jTabbedPane4,
								javax.swing.GroupLayout.PREFERRED_SIZE, 367,
								javax.swing.GroupLayout.PREFERRED_SIZE).addGap(
								0, 0, Short.MAX_VALUE))));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jSplitPane1,
								javax.swing.GroupLayout.Alignment.TRAILING,
								javax.swing.GroupLayout.DEFAULT_SIZE, 358,
								Short.MAX_VALUE)
						.addGroup(
								jPanel1Layout
										.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												jPanel1Layout
														.createSequentialGroup()
														.addGap(0, 0,
																Short.MAX_VALUE)
														.addComponent(
																jTabbedPane4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																68,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(0, 0,
																Short.MAX_VALUE))));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap().addGroup(
						layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jPanel1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE).addComponent(
										jTabbedPane1)).addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jTabbedPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												132,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addContainerGap()));

		pack();
	}// </editor-fold>

	public void setX1(String x1) {
		jTextField1.setText(x1);
	}

	public String getX1() {
		return jTextField1.getText();
	}

	public void setX2(String x2) {
		jTextField2.setText(x2);
	}

	public String getX2() {
		return jTextField2.getText();
	}

	public void setY1(String x1) {
		jTextField3.setText(x1);
	}

	public String getY1() {
		return jTextField3.getText();
	}

	public void setY2(String x2) {
		jTextField4.setText(x2);
	}

	public String getY2() {
		return jTextField4.getText();
	}

	public void setZ1(String x1) {
		jTextField5.setText(x1);
	}

	public String getZ1() {
		return jTextField5.getText();
	}

	public void setZ2(String x2) {
		jTextField6.setText(x2);
	}

	public String getZ2() {
		return jTextField6.getText();
	}

	public void setReferenceString(String str) {
		jTextField7.setText(str);
	}

	public String getReferenceString() {
		return jTextField7.getText();
	}

	public void setInstanceString(String str) {
		jTextField8.setText(str);
	}

	public String getInstanceString() {
		return jTextField8.getText();
	}

	public void setDistanceString(String str) {
		jTextField9.setText(str);
	}

	public String getDistanceString() {
		return jTextField9.getText();
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/*
		 * Set the Nimbus look and feel
		 */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(VaMainframe.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(VaMainframe.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(VaMainframe.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(VaMainframe.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/*
		 * Create and display the form
		 */
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				new VaPartDialog().setVisible(true);
			}
		});
	}

	public void searchButtonPerformed(ActionEvent e) {
		log.debug("searchButtonPerformed");
		VaTreeNode root = jScrollPane1.getTree().getRoot();
		if (e.getSource().equals(jButton1)) {
			log.debug("jButton1 search");
			String x1s = getX1();
			String x2s = getX2();
			String y1s = getY1();
			String y2s = getY2();
			String z1s = getZ1();
			String z2s = getZ2();

			if (isSpace(x1s) && isSpace(x2s) && isSpace(y1s) && isSpace(y2s)
					&& isSpace(z1s) && isSpace(z2s)) {
				log.debug("空间范围坐标值全部为空，不进行检索操作！");
				return;
			}

			Point3d lower = new Point3d();
			Point3d upper = new Point3d();
			lower.setX(Double.valueOf(isSpace(x1s) ? "0.0" : x1s) / 1000.0);
			lower.setY(Double.valueOf(isSpace(y1s) ? "0.0" : y1s) / 1000.0);
			lower.setZ(Double.valueOf(isSpace(z1s) ? "0.0" : z1s) / 1000.0);
			upper.setX(Double.valueOf(isSpace(x2s) ? "0.0" : x2s) / 1000.0);
			upper.setY(Double.valueOf(isSpace(y2s) ? "0.0" : y2s) / 1000.0);
			upper.setZ(Double.valueOf(isSpace(z2s) ? "0.0" : z2s) / 1000.0);

			BoundingBox bbox = new BoundingBox();
			bbox.setLower(lower);
			bbox.setUpper(upper);

			List<BoundingBox> bboxs = new ArrayList<BoundingBox>();
			bboxs.add(bbox);
			check(root, bboxs);
			
		} else if (e.getSource().equals(jButton2)) {
			log.debug("jButton2 search");
			String referenceStr = getReferenceString();
			String instanceStr = getInstanceString();
			String distanceStr = getDistanceString();

			List<BoundingBox> bboxs = new ArrayList<BoundingBox>();
			getBondingBoxes(root, referenceStr, instanceStr, bboxs);
			double distance = 0.0;
			boolean flag = false;
			if (distanceStr != null && distanceStr.trim().length() > 0) {
				distance = Double.valueOf(distanceStr) / 1000.0;
				flag = true;
			}
			if (flag) {
				for (BoundingBox box : bboxs) {
					Point3d lower = new Point3d();
					Point3d upper = new Point3d();
					box.getLower(lower);
					box.getUpper(upper);

					lower.setX(lower.getX() - distance);
					lower.setY(lower.getY() - distance);
					lower.setZ(lower.getZ() - distance);

					upper.setX(upper.getX() + distance);
					upper.setY(upper.getY() + distance);
					upper.setZ(upper.getZ() + distance);

					box.setLower(lower);
					box.setUpper(upper);
				}
			}
			check(root, bboxs);
		}
		jScrollPane1.getTree().repaint();
	}

	private void getBondingBoxes(VaTreeNode node, String referenceStr,
			String instanceStr, List<BoundingBox> bboxs) {
		boolean isInstanceStrNull = true;
		if (instanceStr != null && instanceStr.trim().length() > 0) {
			isInstanceStrNull = false;
		}
		if (node.getPart().getNumber().equals(referenceStr)) {
			Vector vec = node.getBboxes();
			if (!isInstanceStrNull) {
				if (node.getOccId().equals(instanceStr)) {
					if (vec != null && vec.size() >= 1) {
						BoundingBox box = (BoundingBox) vec.get(0);
						if (box != null) {
							Point3d lower = new Point3d();
							Point3d upper = new Point3d();
							box.getLower(lower);
							box.getUpper(upper);
							BoundingBox boxtoAdd = new BoundingBox(lower, upper);
							bboxs.add(boxtoAdd);
						}
					}
				}
			}else{
				if (vec != null && vec.size() >= 1) {
					BoundingBox box = (BoundingBox) vec.get(0);
					if (box != null) {
						Point3d lower = new Point3d();
						Point3d upper = new Point3d();
						box.getLower(lower);
						box.getUpper(upper);
						BoundingBox boxtoAdd = new BoundingBox(lower, upper);
						bboxs.add(boxtoAdd);
					}
				}
			}
		}
		int count = node.getChildCount();
		for (int i = 0; i < count; i++) {
			VaTreeNode temp = (VaTreeNode) node.getChildAt(i);
			getBondingBoxes(temp, referenceStr, instanceStr, bboxs);
		}
	}

	private void check(VaTreeNode node, List<BoundingBox> bboxs) {
		Vector vec = node.getBboxes();
		node.setSelected(false);
		if (vec != null) {
			BoundingBox tocheckbbox = (BoundingBox) vec.get(0);
			for (BoundingBox box : bboxs) {
//				if (tocheckbbox.intersect(box)) {
					if (box.intersect(tocheckbbox)) {
					node.setSelected(true);
				}
			}
		}
		int count = node.getChildCount();
		for (int i = 0; i < count; i++) {
			VaTreeNode child = (VaTreeNode) node.getChildAt(i);
			check(child, bboxs);
		}
	}

	private boolean isSpace(String str) {
		if (str == null || str.trim().length() == 0) {
			return true;
		}
		return false;
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;

	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	// private javax.swing.JPanel jPanel2;
	private VaPViewScenesPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JLabel jLabel10;
	private VaEBomTreePanel jScrollPane1;
	private javax.swing.JSplitPane jSplitPane1;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTabbedPane jTabbedPane4;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	private javax.swing.JTextField jTextField7;
	private javax.swing.JTextField jTextField8;
	private javax.swing.JTextField jTextField9;
	// End of variables declaration
}
