<%@taglib uri="http://www.ptc.com/windchill/taglib/fmt" prefix="fmt" 
%><%@taglib tagdir="/WEB-INF/tags"                      prefix="wctags" 
%><%@include file="/netmarkets/jsp/util/beginPopup.jspf"
%><fmt:setLocale value="${localeBean.locale}"
/><fmt:setBundle basename="com.ptc.windchill.enterprise.change2.change2ClientResource" 
/><fmt:message var="pickerTitle" key="FIND_AFFECTED_DATA" 
/><wctags:itemPicker componentId="changeableItemPicker"
                     id="affectedItemsPicker"
                     inline="true"
                     pickerCallback="doNothing"
                     pickerTitle="${pickerTitle}"
                     multiSelect="true"
                     typeComponentId="Foundation.changeablePicker"
                     baseWhereClause="(latestIteration='1')"
                     objectType="wt.doc.WTDocument|com.ptc.ReferenceDocument|casc.sast.805.OUTER_DOC"
                     defaultVersionValue="LATEST"
                     singleSelectTypePicker="false"
/><%@include file="/netmarkets/jsp/util/end.jspf" %>