
package com.javaedu;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "LicenseServerService", targetNamespace = "http://www.javaedu.com", wsdlLocation = "http://127.0.0.1:8001/licenseServerPort?wsdl")
public class LicenseServerService
    extends Service
{

    private final static URL LICENSESERVERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.javaedu.LicenseServerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.javaedu.LicenseServerService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:8001/licenseServerPort?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8001/licenseServerPort?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        LICENSESERVERSERVICE_WSDL_LOCATION = url;
    }

    public LicenseServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LicenseServerService() {
        super(LICENSESERVERSERVICE_WSDL_LOCATION, new QName("http://www.javaedu.com", "LicenseServerService"));
    }

    /**
     * 
     * @return
     *     returns LicenseServer
     */
    @WebEndpoint(name = "licenseServerPort")
    public LicenseServer getLicenseServerPort() {
        return super.getPort(new QName("http://www.javaedu.com", "licenseServerPort"), LicenseServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LicenseServer
     */
    @WebEndpoint(name = "licenseServerPort")
    public LicenseServer getLicenseServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.javaedu.com", "licenseServerPort"), LicenseServer.class, features);
    }

}
