
package com.javaedu;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "licenseServer", targetNamespace = "http://www.javaedu.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LicenseServer {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://www.javaedu.com", className = "com.javaedu.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://www.javaedu.com", className = "com.javaedu.HelloResponse")
    public String hello(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "licenseRequest", targetNamespace = "http://www.javaedu.com", className = "com.javaedu.LicenseRequest")
    @ResponseWrapper(localName = "licenseRequestResponse", targetNamespace = "http://www.javaedu.com", className = "com.javaedu.LicenseRequestResponse")
    public Boolean licenseRequest(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "licenseDischarge", targetNamespace = "http://www.javaedu.com", className = "com.javaedu.LicenseDischarge")
    @ResponseWrapper(localName = "licenseDischargeResponse", targetNamespace = "http://www.javaedu.com", className = "com.javaedu.LicenseDischargeResponse")
    public Boolean licenseDischarge(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

}
