CREATE INDEX ChangePackaged$COMPOSITE1 ON ChangePackaged(idA3A2folderingInfo)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX ChangePackaged$COMPOSITE2 ON ChangePackaged(idA3teamId)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX ChangePackaged$COMPOSITE6 ON ChangePackaged(idA3containerReference)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX ChangePackaged$COMPOSITE20 ON ChangePackaged(ChangePackaged)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
