
  drop table GWOPERATIONTOPARAMTABLELINK;

   CREATE TABLE "PDM10"."GWOPERATIONTOPARAMTABLELINK"
   (	"GWKEYID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"TECHNICSNUMBER" VARCHAR2(255 BYTE) NOT NULL ENABLE,
	"OBJTYPE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"OBJNUMBER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PARAMETERTABLEID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"TABLEINDEX" NUMBER,
	"BSOID"            VARCHAR2(200),
  "VERSION"          VARCHAR2(200),
	 CONSTRAINT "PK_GWOPERATIONTOPARAMTABLELINK" PRIMARY KEY ("GWKEYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 24576 NEXT 24576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 24576 NEXT 24576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  drop table GWPARAMETERTABLECOLUMN

    CREATE TABLE "PDM10"."GWPARAMETERTABLECOLUMN"
   (	"GWKEYID" VARCHAR2(100 BYTE) DEFAULT 0 NOT NULL ENABLE,
	"PARAMETERTABLETYPEID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"CHINANAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"DATATYPE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"MAXLONG" VARCHAR2(100 BYTE),
	"ISRECORD" VARCHAR2(100 BYTE),
	"ISFROMPARAM" VARCHAR2(100 BYTE),
	"VALUERANGE" VARCHAR2(100 BYTE),
	"STATUS" VARCHAR2(100 BYTE),
	"ORDERNO" NUMBER DEFAULT 0,
	"VISILESS" VARCHAR2(100 BYTE),
	"VISILESSINMES" VARCHAR2(100 BYTE),
	 CONSTRAINT "PK_GWPARAMETERTABLECOLUMN" PRIMARY KEY ("GWKEYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 24576 NEXT 24576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 24576 NEXT 24576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  drop table GWPARAMETERTABLETYPE;

  CREATE TABLE "PDM10"."GWPARAMETERTABLETYPE"
   (	"GWKEYID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"TABLETYPEMASTERID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"TECHNICSTYPE" VARCHAR2(100 BYTE),
	"ISUSED" VARCHAR2(100 BYTE),
	"VERSION" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 CONSTRAINT "PK_GWPARAMETERTABLETYPE" PRIMARY KEY ("GWKEYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 24576 NEXT 24576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 24576 NEXT 24576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  drop table GWPARAMETERTYPE;


  CREATE TABLE "PDM10"."GWPARAMETERTYPE"
   (	"GWKEYID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PARAMNUMBER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PARENT" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ENNAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"CHINANAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"TECHNICSTYPE" VARCHAR2(100 BYTE),
	"VALUETYPE" VARCHAR2(100 BYTE),
	 CONSTRAINT "PK_GWPARAMETERTYPE" PRIMARY KEY ("GWKEYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 24576 NEXT 24576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 24576 NEXT 24576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  drop table GWPARAMTABLETYPEMASTER;

   CREATE TABLE "PDM10"."GWPARAMTABLETYPEMASTER"
   (	"GWKEYID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"CHINANAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 CONSTRAINT "PK_GWPARAMTABLETYPEMASTER" PRIMARY KEY ("GWKEYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 24576 NEXT 24576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 24576 NEXT 24576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;