CREATE INDEX AnalysisToSourceLink$COMPOSI0 ON AnalysisToSourceLink(idA3A5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX AnalysisToSourceLink$COMPOSI1 ON AnalysisToSourceLink(idA3B5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
