#以下是windchill服务器ftp配置
windchill.ftp.ip=10.123.64.60
windchill.ftp.port=21
windchill.ftp.user=wcadmin
windchill.ftp.password=wcadmin
windchill.ftp.ftpbasepath=/export/home/wcadmin
#ftp上存放签名文件的文件夹名(勿加/或\\)
windchill.ftp.signFolder=DWG
#windchill服务器临时文件存储目录
windchill.download.temppath=/temp
#以下是签字服务器ftp配置
sign.ftp.ip=10.123.102.111
sign.ftp.port=21
sign.ftp.user=root
sign.ftp.password=root
sign.ftp.basepath=d:/ptc/cadworker
sign.unzip.temppath=d:/temp 
#ftp上存放签名文件的文件夹名(勿加/或\\)
sign.ftp.signFolder=DWG
#dwg签名开关
cadsign.enable=false