  CREATE TABLE "PDM10"."GWPRINTAPPLYRECORD"
   (	"GWKEYID" VARCHAR2(20 BYTE) NOT NULL ENABLE,
	"DOCVR" VARCHAR2(20 BYTE),
	"NUMBER" VARCHAR2(20 BYTE) NOT NULL ENABLE,
	"NAME" VARCHAR2(30 BYTE),
	"VERSION" VARCHAR2(20 BYTE),
	"PHASECODE" VARCHAR2(20 BYTE),
	"SECRET" VARCHAR2(20 BYTE),
	"BATCH" VARCHAR2(60 BYTE),
	"APPLIER" VARCHAR2(20 BYTE),
	"APPLYDATE" VARCHAR2(20 BYTE),
	"PRINTOR" VARCHAR2(20 BYTE),
	"PRINTDATE" VARCHAR2(20 BYTE),
	 CONSTRAINT "GWPRINTAPPLYRECORD_PK" PRIMARY KEY ("GWKEYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;