  CREATE TABLE "PDM10"."GWPRINTDISTRIBUTERECORD"
   (	"GWKEYID" VARCHAR2(20 BYTE) NOT NULL ENABLE,
	"DOCVR" VARCHAR2(20 BYTE),
	"APPLYRECORD" VARCHAR2(50 BYTE),
	"DISTRIBUTEDEPT" VARCHAR2(50 BYTE),
	"DISTRIBUTEQUANTITY" VARCHAR2(50 BYTE),
	 CONSTRAINT "GWPRINTDISTRIBUTERECORD_PK" PRIMARY KEY ("GWKEYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;