CREATE UNIQUE INDEX GLSupply$UNIQUE55 ON GLSupply(GLSupplyName)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE UNIQUE INDEX GLSupply$UNIQUE56 ON GLSupply(GLSupplyNumber)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
