CREATE INDEX GLSupplyDescLink$COMPOSITE0 ON GLSupplyDescLink(branchIdA3B5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX GLSupplyDescLink$COMPOSITE1 ON GLSupplyDescLink(idA3A5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
