############PDF\u6587\u4ef6\u6253\u5370\u5750\u6807\u914d\u7f6e##############################

#\u5de5\u827a\u89c4\u7a0b#
PROCESS_PLAN_QRCode_FM=180,120
PROCESS_PLAN_QRCode_FM_SIZE=70
PROCESS_PLAN_QRCodeText_FM=185,105
PROCESS_PLAN_Baseline=610,320
PROCESS_PLAN_Baseline_yOffSet=30
PROCESS_PLAN_Baseline_FONTSIZE=12
PROCESS_PLAN_Seal_FM=110,500
PROCESS_PLAN_QRCodeText_FONTSIZE=8

#SOP\u5de5\u827a#
SOPDOC_QRCode_FM=135,120
SOPDOC_QRCode_FM_SIZE=70
SOPDOC_QRCodeText_FM=140,105
SOPDOC_Baseline=710,320
SOPDOC_Baseline_yOffSet=30
SOPDOC_Baseline_FONTSIZE=12
SOPDOC_Seal_FM=110,500
SOPDOC_QRCodeText_FONTSIZE=8

#\u66f4\u6539\u5355#
CHANGEORDER_QRCode_FM=30,60
CHANGEORDER_QRCode_FM_SIZE=40
CHANGEORDER_QRCodeText_FM=35,48
CHANGEORDER_QRCodeText_FONTSIZE=5
CHANGEORDER_Baseline=610,220
CHANGEORDER_Baseline_yOffSet=30
CHANGEORDER_Baseline_FONTSIZE=8
CHANGEORDER_Seal_FM=110,530

#\u6280\u672f\u901a\u77e5\u5355#
PROCESS_NOTICE_QRCode_FM=33,100
PROCESS_NOTICE_QRCode_FM_SIZE=40
PROCESS_NOTICE_QRCodeText_FM=38,88
PROCESS_NOTICE_QRCodeText_FONTSIZE=5
PROCESS_NOTICE_Baseline=35,670
PROCESS_NOTICE_Baseline_yOffSet=20
PROCESS_NOTICE_Baseline_FONTSIZE=8
PROCESS_NOTICE_Seal_FM=360,745

#\u6280\u672f\u534f\u8bae#
TECHNOLOGY_AGREEMENT_QRCode_FM=120,300
TECHNOLOGY_AGREEMENT_QRCode_FM_SIZE=60
TECHNOLOGY_AGREEMENT_QRCodeText_FM=125,280
TECHNOLOGY_AGREEMENT_QRCodeText_FONTSIZE=7
TECHNOLOGY_AGREEMENT_Baseline=462,400
TECHNOLOGY_AGREEMENT_Baseline_yOffSet=30
TECHNOLOGY_AGREEMENT_Baseline_FONTSIZE=8
TECHNOLOGY_AGREEMENT_Seal_FM=110,730

#\u5176\u4ed6\u7c7b\u6587\u6863#
OTHERREPORT_QRCode_FM=62,300
OTHERREPORT_QRCode_FM_SIZE=50
OTHERREPORT_QRCodeText_FM=67,285
OTHERREPORT_QRCodeText_FONTSIZE=6
OTHERREPORT_Baseline=432,500
OTHERREPORT_Baseline_yOffSet=25
OTHERREPORT_Baseline_FONTSIZE=23
OTHERREPORT_Seal_FM=62,730

#\u901a\u7528\u5de5\u827a#
TONGYONGPROCESS_QRCode_FM=120,300
TONGYONGPROCESS_QRCode_FM_SIZE=50
TONGYONGPROCESS_QRCodeText_FM=120,285
TONGYONGPROCESS_QRCodeText_FONTSIZE=6
TONGYONGPROCESS_Baseline=432,500
TONGYONGPROCESS_Baseline_yOffSet=25
TONGYONGPROCESS_Baseline_FONTSIZE=10
TONGYONGPROCESS_Seal_FM=120,730
