#ClientPropertiesFile
#外来文件录入
外来文件录入_class=String|Boolean|String|String|String|String|String|String|String|Object
外来文件录入_name=oid||文件编号|文件名称|版本|阶段标记|密级|页数|型号类型|object
外来文件录入_editableColumns=1
外来文件录入_buttonColumns=
外来文件录入_columnsWidth=0|50|350|390|200|200|200|200|100|0
外来文件录入_height=105

#基于工艺目录添加
基于工艺目录添加_class=String|String|String|String|String|String|String|String|String|String|Object
基于工艺目录添加_name=oid|文件编号|文件名称|版本|阶段标记|密级|所属产品库|分发状态|受控状态|对象
基于工艺目录添加_editableColumns=
基于工艺目录添加_buttonColumns=
基于工艺目录添加_columnsWidth=0|300|350|150|150|130|200|150|150|0
基于工艺目录添加_height=105

#加盖印章确认
加盖印章确认_class=String|String|String|String|String|String|String|String|String|String|String|Object
加盖印章确认_name=oid|编号|名称|版本|阶段标记|密级|打印时间|分发部门|印章|加盖印章|条码|object
加盖印章确认_editableColumns=
加盖印章确认_buttonColumns=
加盖印章确认_columnsWidth=0|220|270|100|100|100|100|100|100|350|250|0
加盖印章确认_height=105

#加盖印章检查
加盖印章检查_class=String|Boolean|String|String|String|String|String|String|String|String|String|String|Object
加盖印章检查_name=oid||编号|名称|版本|阶段标记|密级|打印时间|分发部门|印章|加盖印章|条码|object
加盖印章检查_editableColumns=1
加盖印章检查_buttonColumns=
加盖印章检查_columnsWidth=0|35|220|270|100|100|100|100|100|100|350|250|0
加盖印章检查_height=105

#加盖印章搜索列表
加盖印章搜索列表_class=String|Boolean|String|String|String|String|String|String|String|String|String|String|String|Object
加盖印章搜索列表_name=oid||编号|名称|版本|阶段标记|密级|打印时间|分发部门|条码|印章|状态|所属产品库|object
加盖印章搜索列表_editableColumns=1
加盖印章搜索列表_buttonColumns=
加盖印章搜索列表_columnsWidth=0|35|200|300|100|100|100|100|100|250|300|110|100|0
加盖印章搜索列表_height=105

#加盖印章管理
加盖印章管理_class=String|Boolean|String|String|String|String|String|String|String|String|String|String|String|String|Object
加盖印章管理_name=oid||编号|名称|版本|阶段标记|密级|打印时间|分发部门|条码|印章|加盖印章|状态|所属产品库|object
加盖印章管理_editableColumns=1|11
加盖印章管理_buttonColumns=11
加盖印章管理_columnsWidth=0|35|200|250|100|100|100|100|100|200|250|250|100|100|0
加盖印章管理_height=105

#领取纸质文件
领取纸质文件_class=String|Boolean|String|String|String|String|String|String|String|String|String|String|String|String|Object
领取纸质文件_name=oid||文件编号|文件名称|版本|阶段标记|密级|印章|条码|状态|分发部门|领用人|领用时间|applyrecordID|object
领取纸质文件_editableColumns=1
领取纸质文件_buttonColumns=
领取纸质文件_columnsWidth=0|35|150|300|100|100|70|250|200|80|100|150|150|0|0
领取纸质文件_height=105

#文件补打申请
文件补打申请_class=String|Boolean|String|String|String|String|String|String|String|String|String|String|String|String|Object
文件补打申请_name=oid||文件编号|文件名称|版本|阶段标记|密级|印章|分发部门及份数|补打|所属产品库|分发状态|受控状态|申请单号|object
文件补打申请_editableColumns=1|9
文件补打申请_buttonColumns=9
文件补打申请_columnsWidth=0|35|200|250|150|100|100|300|300|300|200|150|150|100|0
文件补打申请_height=105

#打印申请补打添加
打印申请补打添加_class=String|Boolean|String|String|String|String|String|String|String|String|String|String|String|Object
打印申请补打添加_name=oid||文件编号|文件名称|版本|阶段标记|密级|印章|分发部门及份数|所属产品库|分发状态|受控状态|申请单号|object
打印申请补打添加_editableColumns=1
打印申请补打添加_buttonColumns=
打印申请补打添加_columnsWidth=0|35|200|250|150|100|100|300|300|200|150|150|100|0
打印申请补打添加_height=105

#文件打印申请
文件打印申请_class=String|Boolean|String|String|String|String|String|String|String|String|String|String|String|Object
文件打印申请_name=oid||文件编号|文件名称|版本|阶段标记|密级|印章|分发部门及份数|所属产品库|分发状态|受控状态|pbooid|object
文件打印申请_editableColumns=1|7|8
文件打印申请_buttonColumns=7|8
文件打印申请_columnsWidth=0|35|200|250|150|100|100|300|300|200|150|150|0|0
文件打印申请_height=105

#执行打印
执行打印_class=String|Boolean|String|String|String|String|String|String|String|String|String|String|String|String|Object
执行打印_name=oid||文件编号|文件名称|版本|阶段标记|密级|印章|分发部门|条码|文件状态|打印人|打印时间|DocVR|object
执行打印_editableColumns=1
执行打印_buttonColumns=
执行打印_columnsWidth=0|35|150|250|100|100|80|250|250|200|100|80|100|0|0
执行打印_height=105

#预览打印
预览打印_class=String|Boolean|String|String|String|String|String|String|String|String|Object
预览打印_name=oid||文件编号|文件名称|版本|阶段标记|密级|印章|分发部门及份数|DocVR|object
预览打印_editableColumns=1
预览打印_buttonColumns=
预览打印_columnsWidth=0|35|300|300|100|100|100|370|380|0|0
预览打印_height=105


#打印申请文件添加
打印申请文件添加_class=String|Boolean|String|String|String|String|String|String|String|String|String|Object
打印申请文件添加_name=oid||文件编号|文件名称|版本|阶段标记|密级|分发情况|所属产品库|分发状态|受控状态|对象
打印申请文件添加_editableColumns=1
打印申请文件添加_buttonColumns=
打印申请文件添加_columnsWidth=0|35|200|250|120|100|200|300|150|120|100|0
打印申请文件添加_height=280

#文件添加
文件添加_class=String|Boolean|String|String|String|String|String|String|Object
文件添加_name=oid||文件编号|文件名称|版本|阶段标记|密级|分发情况|对象
文件添加_editableColumns=1
文件添加_buttonColumns=
文件添加_columnsWidth=0|35|100|150|70|100|200|350|0
文件添加_height=280

#基于BOM文件添加文件/零部件列表
零部件列表_class=String|String|String|String|String|String|String|Object
零部件列表_name=oid|序号|零部件编号|零部件名称|版本|阶段标记|工艺文件目录|对象
零部件列表_editableColumns=
零部件列表_buttonColumns=
零部件列表_columnsWidth=0|75|500|510|200|200|100|0
零部件列表_height=105

#基于BOM文件添加文件/相关文件列表
相关文件列表_class=String|Boolean|String|String|String|String|String|String|String|String|String|Object
相关文件列表_name=oid||文件编号|文件名称|版本|阶段标记|密级|分发情况|所属产品库|分发状态|受控状态|对象
相关文件列表_editableColumns=1
相关文件列表_buttonColumns=
相关文件列表_columnsWidth=0|35|250|300|100|100|200|250|150|100|100|0
相关文件列表_height=105

#申请审批和执行打印
申请审批和执行打印_class=String|Boolean|String|String|String|String|String|String|String|String|String|Boolean|String|String|String|String|String|String|String|String|String|String
申请审批和执行打印_name=oid||序号|文件编号|文件名称|产品代号|版本|阶段标记|文件类型|技术状态基线|页数|是否蓝卡|更改单号|密级|分发部门及份数|打印要求|二维码|驳回备注|驳回状态|打印状态|打印人|打印时间
申请审批和执行打印_editableColumns=1|17
申请审批和执行打印_buttonColumns=
申请审批和执行打印_columnsWidth=0|35|50|150|150|120|50|70|120|240|50|70|150|60|240|240|100|240|80|80|100|120
申请审批和执行打印_height=105

#打印申请驳回
打印申请驳回_class=String|Boolean|String|String|String|String|String|String|String|String|String|Boolean|String|String|String|String|String|String|String|String
打印申请驳回_name=oid||序号|文件编号|文件名称|产品代号|版本|阶段标记|文件类型|技术状态基线|页数|是否蓝卡|更改单号|密级|分发部门及份数|临时章|打印要求|二维码|驳回备注|驳回状态
打印申请驳回_editableColumns=1|9|11|14|15|16
打印申请驳回_buttonColumns=9|14
打印申请驳回_columnsWidth=0|35|50|150|150|100|50|70|120|240|50|70|150|60|240|100|240|100|240|100
打印申请驳回_height=105

#纸质文件分发
纸质文件分发_class=String|Boolean|String|String|String|String|String|String|String|String|String|Boolean|String|String|String|String|String|String
纸质文件分发_name=oid||序号|文件编号|文件名称|产品代号|版本|阶段标记|文件类型|技术状态基线|页数|是否蓝卡|更改单号|密级|分发部门及份数|打印要求|二维码|已领取份数
纸质文件分发_editableColumns=1|17
纸质文件分发_buttonColumns=
纸质文件分发_columnsWidth=0|35|50|150|150|100|50|70|120|240|50|70|150|60|240|240|100|100
纸质文件分发_height=180

#自行打印
自行打印_class=String|Boolean|String|String|String|String|String|String|String|String|String|String|String|String|String|String
自行打印_name=oid||序号|文件编号|文件名称|产品代号|版本|阶段标记|文件类型|页数|密级|临时章|二维码|打印状态|打印人|打印时间
自行打印_editableColumns=1|11
自行打印_buttonColumns=
自行打印_columnsWidth=0|35|50|240|240|200|80|120|150|60|80|150|120|120|120|205
自行打印_height=280

#退回（销毁）申请
退回（销毁）申请_class=String|Boolean|String|String|String|String|String|String|String|String|String
退回（销毁）申请_name=oid||序号|文件编号|文件名称|份数|页数|密级|二维码|退回备注|已领取份数
退回（销毁）申请_editableColumns=1|5|9
退回（销毁）申请_buttonColumns=
退回（销毁）申请_columnsWidth=0|35|50|350|350|100|120|120|180|500|165
退回（销毁）申请_height=180

#已领用文件添加
已领用文件添加_class=String|Boolean|String|String|String|String|String|String|String|String|String|String|String|String|String|String|Object
已领用文件添加_name=oid||序号|文件编号|文件名称|产品代号|版本|阶段标记|文件类型|页数|更改单号|密级|二维码|领取人|领取时间|领取部门|object
已领用文件添加_editableColumns=1
已领用文件添加_buttonColumns=
已领用文件添加_columnsWidth=0|35|50|300|300|100|50|70|100|50|300|70|100|120|150|150|0
已领用文件添加_height=200

#领取纸质文件通知
领取纸质文件通知_class=String|String|String|String|String|String|String|String|String|String|Boolean|String|String|String|String
领取纸质文件通知_name=oid|序号|文件编号|文件名称|产品代号|版本|阶段标记|文件类型|技术状态基线|页数|是否蓝卡|更改单号|密级|分发部门及份数|打印要求
领取纸质文件通知_editableColumns=
领取纸质文件通知_buttonColumns=
领取纸质文件通知_columnsWidth=0|50|200|200|120|50|70|120|300|50|70|180|60|300|240
领取纸质文件通知_height=105

#统一打印文件管理
统一打印文件管理_class=String|String|String|String|String|String|String|String|String|String|Boolean|String|String|String|String|String|String|String|String|String|String|Object
统一打印文件管理_name=oid|序号|编号|名称|产品代号|版本|阶段标记|文件类型|技术状态基线|页数|是否蓝卡|密级|更改单号|打印要求|分发部门及份数|二维码|申请人|申请时间|打印人|打印时间|领取情况|object
统一打印文件管理_editableColumns=20
统一打印文件管理_buttonColumns=
统一打印文件管理_columnsWidth=0|50|200|200|120|50|70|100|240|50|70|80|150|240|240|100|100|100|100|100|80|0
统一打印文件管理_height=325

#自行打印文件管理
自行打印文件管理_class=String|String|String|String|String|String|String|String|String|String|String|String|String
自行打印文件管理_name=oid|序号|编号|名称|产品代号|版本|阶段标记|文件类型|页数|密级|二维码|打印人|打印时间
自行打印文件管理_editableColumns=
自行打印文件管理_buttonColumns=
自行打印文件管理_columnsWidth=0|50|350|350|200|100|100|150|100|100|160|150|150
自行打印文件管理_height=300

#退回文件查看
退回文件查看_class=String|Boolean|String|String|String|String|String|String|String|String
退回文件查看_name=oid||序号|文件编号|文件名称|份数|每份页数|密级|退回备注|二维码
退回文件查看_editableColumns=1
退回文件查看_buttonColumns=
退回文件查看_columnsWidth=0|35|50|400|400|150|150|150|400|260
退回文件查看_height=105

#退回文件确认
退回文件确认_class=String|String|String|String|String|String|String|String|String|String|String|String|String
退回文件确认_name=oid|序号|文件编号|文件名称|份数|每份页数|密级|退回备注|二维码|收件人|收件时间|已回收份数|退回部门
退回文件确认_editableColumns=
退回文件确认_buttonColumns=
退回文件确认_columnsWidth=0|50|260|260|100|100|100|350|150|150|150|150|150
退回文件确认_height=105