######################################################################################################
#
#      文档签审打印方案
#
######################################################################################################
#是否处理附件 
ProcessAttachments=true
ProcessAttachments.WTDocument=true
ProcessAttachments.EPMDocument=true

#proe图幅对应签审格式
prta4.frm=FORMAT1
PRTA4.frm=FORMAT1
prta3.frm=FORMAT2
PRTA3.frm=FORMAT2
prta2.frm=FORMAT3
PRTA2.frm=FORMAT3
prta1x4.frm=FORMAT4
PRTA1x4.frm=FORMAT4
prta1x3.frm=FORMAT5
PRTA1x3.frm=FORMAT5
prta1.frm=FORMAT6
PRTA1.frm=FORMAT6
prta0.frm=FORMAT7
PRTA0.frm=FORMAT7

asma4.frm=FORMAT1
ASMA4.frm=FORMAT1
asma3.frm=FORMAT2
ASMA3.frm=FORMAT2
asma2.frm=FORMAT3
ASMA2.frm=FORMAT3
asma1x4.frm=FORMAT4
ASMA1x4.frm=FORMAT4
asma1x3.frm=FORMAT5
ASMA1x3.frm=FORMAT5
asma1.frm=FORMAT6
ASMA1.frm=FORMAT6
asma0.frm=FORMAT7
ASMA0.frm=FORMAT7

#autocad
autocada4.frm=FORMAT12
AUTOCADA4.frm=FORMAT12
autocada3.frm=FORMAT13
AUTOCADA3.frm=FORMAT13
autocada2.frm=FORMAT14
AUTOCADA2.frm=FORMAT14
autocada1.frm=FORMAT15
AUTOCADA1.frm=FORMAT15
autocada1x3.frm=FORMAT16
AUTOCADA1x3.frm=FORMAT16
autocadA1x4.frm=FORMAT17
AUTOCADA1x4.frm=FORMAT17
autocada0.frm=FORMAT18
AUTOCADA0.frm=FORMAT18

#图幅 属性内码
EPMDocument.tufuAttribute=tufu
WTDocument.tufuAttribute=tufu
  
#不需要处理的签审格式模板
IgnoreTemplate=FORMAT0

#AUTOCAD DWG的PDF文件生成方式
# manual  表示由用户手工生成PDF文件
# worker  表示由pdf worker转换生成PDF文件
AUTOCAD.createpdf=manual

#ProE DRW的PDF文件生成方式
# manual  表示由用户手工处理保存PDF文件至CAD文档的附件
# worker  表示由CAD worker 生成PDF格式的表示法
PROE.createpdf=worker


#PDF文件命名的分隔符
PDF.separator=_

#源PDF文件的命名规则，文件的前缀
# null
# 其它字符
SOURCEPDF.prefix=null
#源PDF文件的命名规则，标记文档对象的关键字
# docnumber
# docnumber_version
#SOURCEPDF.dockey=docnumber
SOURCEPDF.dockey=
#源PDF文件的命名规则，标记文件名 filename or docnumber
# filename
SOURCEPDF.filename=filename
#源PDF文件的命名规则，打印稿文件的前缀
SOURCEPDF.formula=$(SOURCEPDF.prefix)$(SOURCEPDF.dockey)$(SOURCEPDF.filename)


#打印稿PDF文件的命名规则,打印稿文件的前缀
PRINTPDF.prefix=Print
#打印稿PDF文件的命名规则，标记文档对象的关键字
# docnumber
# docnumber_version
PRINTPDF.dockey=docnumber_version
#打印稿PDF文件的命名规则，标记文件名
PRINTPDF.filename=filename
#打印稿PDF文件的命名规则,打印稿文件的前缀
PRINTPDF.formula=$(PRINTPDF.prefix)$(PRINTPDF.dockey)$(PRINTPDF.filename)

fileprint.overWrite=false