CREATE TABLE "PDM10"."ANALYSISOBJENTRY"
(	"CMKEYID" VARCHAR2(255),
     "ANALYSISNUMBER" VARCHAR2(255),
     "VEROID" VARCHAR2(255),
     "DATATYPE" VARCHAR2(255),
     "AFFECTED" VARCHAR2(255),
     "AFFECTEDGYY" VARCHAR2(255),
     "RESPONSER" VARCHAR2(255),
     "UNIT" VARCHAR2(255),
     "PRODUCT" VARCHAR2(255),
     "COUNT" NUMBER(*,0),
     "REPAIRCOUNT" NUMBER(*,0),
     "ZJWXCOUNT" NUMBER(*,0),
     "REQUIREMENT" VARCHAR2(255),
     "COMPLETETIME" VARCHAR2(255),
     "RELATEDORDER" VARCHAR2(255),
     "DEALSTATUS" VARCHAR2(255),
     "SENDSTATUS" VARCHAR2(255),
     "TASKTIME" DATE,
     PRIMARY KEY ("CMKEYID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "USERS"  ENABLE
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"




-- 表注释
COMMENT ON TABLE PDM10.ANALYSISOBJENTRY IS '影响分析对象';

-- 字段注释
COMMENT ON COLUMN PDM10.ANALYSISOBJENTRY.CMKEYID IS '主键ID';
COMMENT ON COLUMN PDM10.ANALYSISOBJENTRY.ANALYSISNUMBER IS '影响分析编号';
COMMENT ON COLUMN PDM10.ANALYSISOBJENTRY.VEROID IS '对象大版本oid';
COMMENT ON COLUMN PDM10.ANALYSISOBJENTRY.DATATYPE IS '对象类型：pbom technics zproduct yproduct';
COMMENT ON COLUMN PDM10.ANALYSISOBJENTRY.AFFECTED IS '主任师意见';
COMMENT ON COLUMN PDM10.ANALYSISOBJENTRY.AFFECTEDGYY IS '工艺员意见';
COMMENT ON COLUMN PDM10.ANALYSISOBJENTRY.RESPONSER IS '责任人';
COMMENT ON COLUMN PDM10.ANALYSISOBJENTRY.UNIT IS '责任部门';
COMMENT ON COLUMN PDM10.ANALYSISOBJENTRY.PRODUCT IS '制品处理意见';
COMMENT ON COLUMN PDM10.ANALYSISOBJENTRY.COUNT IS '制品数量';
COMMENT ON COLUMN PDM10.ANALYSISOBJENTRY.REPAIRCOUNT IS '制品实际返修数量';
COMMENT ON COLUMN PDM10.ANALYSISOBJENTRY.ZJWXCOUNT IS '整件外协数量';
COMMENT ON COLUMN PDM10.ANALYSISOBJENTRY.REQUIREMENT IS '更改要求';
COMMENT ON COLUMN PDM10.ANALYSISOBJENTRY.COMPLETETIME IS '要求完成时间';
COMMENT ON COLUMN PDM10.ANALYSISOBJENTRY.RELATEDORDER IS '关联更改单/工艺';
COMMENT ON COLUMN PDM10.ANALYSISOBJENTRY.DEALSTATUS IS '完成情况';
COMMENT ON COLUMN PDM10.ANALYSISOBJENTRY.SENDSTATUS IS '通知情况';
COMMENT ON COLUMN PDM10.ANALYSISOBJENTRY.TASKTIME IS '任务下发时间';



CREATE TABLE "PDM10"."ANALYSISOBJHISTORYRECORD"
(	"CMKEYID" VARCHAR2(255),
     "ANALYSISNUMBER" VARCHAR2(255),
     "WORKITEMOID" VARCHAR2(255),
     "VEROID" VARCHAR2(255),
     "DATATYPE" VARCHAR2(255),
     "AFFECTED" VARCHAR2(255),
     "AFFECTEDGYY" VARCHAR2(255),
     "RESPONSER" VARCHAR2(255),
     "UNIT" VARCHAR2(255),
     "PRODUCT" VARCHAR2(255),
     "COUNT" NUMBER(*,0),
     "REPAIRCOUNT" NUMBER(*,0),
     "REQUIREMENT" VARCHAR2(255),
     "COMPLETETIME" VARCHAR2(255),
     "RELATEDORDER" VARCHAR2(255),
     "DEALSTATUS" VARCHAR2(255),
     "SENDSTATUS" VARCHAR2(255),
     "TASKTIME" DATE,
     PRIMARY KEY ("CMKEYID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "USERS"  ENABLE
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"




-- 表注释
COMMENT ON TABLE PDM10.ANALYSISOBJHISTORYRECORD IS '影响分析历史记录';

-- 字段注释
COMMENT ON COLUMN PDM10.ANALYSISOBJHISTORYRECORD.CMKEYID IS '主键ID';
COMMENT ON COLUMN PDM10.ANALYSISOBJHISTORYRECORD.ANALYSISNUMBER IS '影响分析编号';
COMMENT ON COLUMN PDM10.ANALYSISOBJHISTORYRECORD.WORKITEMOID IS '流程节点oid';
COMMENT ON COLUMN PDM10.ANALYSISOBJHISTORYRECORD.VEROID IS '对象大版本oid';
COMMENT ON COLUMN PDM10.ANALYSISOBJHISTORYRECORD.DATATYPE IS '对象类型：pbom technics zproduct yproduct';
COMMENT ON COLUMN PDM10.ANALYSISOBJHISTORYRECORD.AFFECTED IS '主任师意见';
COMMENT ON COLUMN PDM10.ANALYSISOBJHISTORYRECORD.AFFECTEDGYY IS '工艺员意见';
COMMENT ON COLUMN PDM10.ANALYSISOBJHISTORYRECORD.RESPONSER IS '责任人';
COMMENT ON COLUMN PDM10.ANALYSISOBJHISTORYRECORD.UNIT IS '责任部门';
COMMENT ON COLUMN PDM10.ANALYSISOBJHISTORYRECORD.PRODUCT IS '制品处理意见';
COMMENT ON COLUMN PDM10.ANALYSISOBJHISTORYRECORD.COUNT IS '制品数量';
COMMENT ON COLUMN PDM10.ANALYSISOBJHISTORYRECORD.REPAIRCOUNT IS '制品实际返修数量';
COMMENT ON COLUMN PDM10.ANALYSISOBJHISTORYRECORD.REQUIREMENT IS '更改要求';
COMMENT ON COLUMN PDM10.ANALYSISOBJHISTORYRECORD.COMPLETETIME IS '要求完成时间';
COMMENT ON COLUMN PDM10.ANALYSISOBJHISTORYRECORD.RELATEDORDER IS '关联更改单/工艺';
COMMENT ON COLUMN PDM10.ANALYSISOBJHISTORYRECORD.DEALSTATUS IS '完成情况';
COMMENT ON COLUMN PDM10.ANALYSISOBJHISTORYRECORD.SENDSTATUS IS '通知情况';
COMMENT ON COLUMN PDM10.ANALYSISOBJHISTORYRECORD.TASKTIME IS '任务下发时间';

