
CREATE TABLE "PDM10"."GLECNCOLLECTDATA"
(	"CMKEYID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
     "PARENTDOCOID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
     "CHILDDOCOID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
     CONSTRAINT "GLECNCOLLECTDATA_PK" PRIMARY KEY ("CMKEYID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
         TABLESPACE "USERS"  ENABLE
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

