
package ext.casc.integrate.pfmea.client;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 *
 */
@WebServiceClient(name = "FMEAImplService", targetNamespace = "http://api.techreqmanager.soft.yt.com/", wsdlLocation = "file:/C:/Users/GHOST/Desktop/api.wsdl")
public class FMEAImplService
        extends Service
{

    private final static URL FMEAIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(FMEAImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = FMEAImplService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/GHOST/Desktop/api.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/GHOST/Desktop/api.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        FMEAIMPLSERVICE_WSDL_LOCATION = url;
    }

    public FMEAImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FMEAImplService() {
        super(FMEAIMPLSERVICE_WSDL_LOCATION, new QName("http://api.techreqmanager.soft.yt.com/", "FMEAImplService"));
    }

    /**
     *
     * @return
     *     returns IFmea
     */
    @WebEndpoint(name = "FMEAImplPort")
    public IFmea getFMEAImplPort() {
        return super.getPort(new QName("http://api.techreqmanager.soft.yt.com/", "FMEAImplPort"), IFmea.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IFmea
     */
    @WebEndpoint(name = "FMEAImplPort")
    public IFmea getFMEAImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.techreqmanager.soft.yt.com/", "FMEAImplPort"), IFmea.class, features);
    }

}
