
package ext.casc.integrate.pfmea.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IFmea", targetNamespace = "http://api.techreqmanager.soft.yt.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IFmea {


    /**
     * 
     * @param pid
     * @return
     *     returns java.lang.String
     * @throws UnsupportedEncodingException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createProject", targetNamespace = "http://api.techreqmanager.soft.yt.com/", className = "pfmea.CreateProject")
    @ResponseWrapper(localName = "createProjectResponse", targetNamespace = "http://api.techreqmanager.soft.yt.com/", className = "pfmea.CreateProjectResponse")
    public String createProject(
            @WebParam(name = "pid", targetNamespace = "")
                    Long pid)
        throws UnsupportedEncodingException_Exception
    ;

}
