[APPURL]
mbom.url=/wtcore/jsp/ext/ideal/samc/openMBomBuilder.jsp
ao.url=/wtcore/jsp/ext/ideal/samc/openAOBuilder.jsp
spsbom.url=/wtcore/jsp/ext/ideal/samc/openSPSBomBuilder.jsp
[MBOM]
pview.download.threadCount=30

ebom.ci.search.types=主部段,部段,ATA章,ATA节,ATA段,DCI
ebom.structure.leaf.type=DCI
ebom.structure.stop.type=TopCI

#MBOM中搜索组件中可搜索的类型
mbom.openMBom.valid.types=AO,AAO

#“新建节点”功能对应的类型业务逻辑
mbom.newNode.configable.types=AO,AAO,工艺组件,CI,DCI,SCI,DM,DDM,SDM

#能创建新节点的MBOM树节点类型
mbom.newNode.canCreate.types=AO,AAO,工艺组件

#AO节点下能创建的部件类型, Alex.Huang 2011-4-20根据要求去掉 AAO类型
mbom.newNode.type.AO=工艺组件

#MBOM中创建组件中可创建的类型
mbom.newPart.type=AO,AAO

#AAO节点下能创建的部件类型
mbom.newNode.type.AAO=工艺组件

#工艺组件节点下能创建的部件类型
mbom.newNode.type.工艺组件=工艺组件

#不能添加到MBOM树上的节点类型
mbom.newNode.unPaste.type=DCI,SCI,CI,DLO,LO,SLO,DDM,DM,SDM

long.time.action.enablePerformanceTraceUI=false

#记录唯一实例标识时，CmInstanceData的类型定义
mbom.instanceData.type.CI=DCI
mbom.instanceData.type.LO=DLO

#EBom视图中可以查看路径的对象类型
ebom.view.node.path.type=DCI

#保存时的节点类型
mbom.saveAttribut.node.type.AO=AO

#Alex.Huang 2011-6-22当部件为这个状态时，结构从系统中获取，否则从xml中获取
mbom.part.state.displayName=已发布,设计中

#Alex.Huang 2011-6-22当工艺组件的状态为这些值时，结构可编辑
mbom.gongyizujian.canEdit.state.displayName=正在工作,修改中

#Alex.Huang 2011-7-01当AO组件的状态为这些值时，结构可编辑
mbom.ao.canEdit.state.displayName=正在工作,修改中

[AO]
empty.row.for.zero=true
ao.mbom_ebom.newNode.unPaste.type=AO,AAO
aoTechnicsmark.ebom_mbom.newNode.unPaste.type=DCI,SCI,CI,DLO,LO,SLO,DDM,DM,SDM

[Effectivity]
DesignView.C919.EffContext=C1
DesignView.C919样机和试验件模型管理与协调空间.EffContext=C0
Manufacturing.C919-SAMC.EffContext=C919-SAMC

effectivity.node.type=DLO

[CAD]
LocatorParentNodeType=com.ptc.Variant

CadAdapter.class.CATIAV5=ext.ideal.samc.jws.cad.CatiaV5CadAdapterImpl
getContent.useCADNameAsURL.CATIAV5=false
getContent.add2workspace.CATIAV5=true
getContent.checkFamilyInstances.CATIAV5=false
CATIAV5.useDlName=false

cadScalingFactor.CATIAV5=1000
RootStrucLevel=Product

getContent.unmatchingAuthApps.useSecondary.CATIAV5=false
getContent.unmatchingAuthApps.secondary.useSuffixFor.CATIAV5=CATPART,CATPRODUCT,MODEL
getContent.unmatchingAuthApps.usePublishLinkedContent.CATIAV5=true


[SPSBOM]
#SPS工作包，部段，散交组件，散交零件 软类型
spsbom.spspackage.softType=wt.part.WTPart|com.ideal.SPSPackage
spsbom.depParagraph.softType=wt.part.WTPart|com.ideal.DepParagraph
spsbom.scatterChiasmaPart.softType=wt.part.WTPart|com.ideal.ScatterChiasmaPart
spsbom.scatterChiasma.softType=wt.part.WTPart|com.ideal.ScatterChiasma

#M视图中可接收拖动节点的节点类型
spsbom.ebom2mbom.darg.objectType=wt.part.WTPart|com.ideal.DepParagraph,wt.part.WTPart|com.ideal.ScatterChiasma,wt.part.WTPart|com.ideal.ScatterChiasmaPart

#不能添加到MBOM树上的节点类型
spsbom.ebom2mbom.unPaste.type=DCI,SCI,CI,DLO,LO,SLO

spsbom.newNode.configable.types=SPS工作分包,工艺组件
spsbom.newNode.types=工艺组件

spsbom.newNode.type.工艺组件=工艺组件

#Alex.Huang 2011-7-20当工艺组件的状态为这些值时，结构可编辑
spsbom.gongyizujian.canEdit.state.displayName=正在工作,修改中

#Alex.Huang 2011-7-20当SPS工作包的状态为这些值时，结构可编辑
spsbom.sps.canEdit.state.displayName=正在工作,修改中

[editAttribute]
#AO零件代码
attr.ao.code=ao零件代码1,零件代码2,零件代码3,零件代码4,零件代码5
#AO制造路线
attr.ao.mfl=ao制造路线1,制造路线2,制造路线3,制造路线4,制造路线5
#AO使用单位
attr.ao.udp=ao使用单位1,使用单位2,使用单位3,使用单位4,使用单位5

#SPS零件代码
attr.sps.code=sps零件代码1,零件代码2,零件代码3,零件代码4,零件代码5
#SPS制造路线
attr.sps.mfl=sps制造路线1,制造路线2,制造路线3,制造路线4,制造路线5
#SPS使用单位
attr.sps.udp=sps使用单位1,使用单位2,使用单位3,使用单位4,使用单位5

#属性是否为空校验
attr.check.column=零件代码,制造路线,物料编码
attr.check.column.gui=零件代码,制造路线,物料编码


[viewBom]
C919.Manufacturing=C919-SAMC
C919.Supplying=SPSBOM