package com.glaway.mpm.qmIntf.viewPanel;

public class GLViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form GLViewPanel
     */
    public GLViewPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        可视化展示 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new GLImagePanel("C:\\Users\\Public\\Pictures\\Sample Pictures\\Hydrangeas.jpg");
        

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        可视化展示.setText("可视化展示");
        jPanel1.add(可视化展示);

        jButton1.setText("jButton1");
        jPanel1.add(jButton1);

        add(jPanel1, java.awt.BorderLayout.NORTH);
        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private GLImagePanel jPanel2;
    private javax.swing.JLabel 可视化展示;
    // End of variables declaration//GEN-END:variables
}
