WCTYPE|wt.part.WTPart=WCTYPE|wt.part.WTPart
WCTYPE|wt.epm.structure.EPMMemberLink|casc.sast.805.DefaultEPMMemberLink=WCTYPE|wt.epm.structure.EPMMemberLink|casc.sast.149.DefaultEPMMemberLink
WCTYPE|wt.epm.EPMDocument|casc.sast.805.DefaultEPMDocument=WCTYPE|wt.epm.EPMDocument|casc.sast.149.DefaultEPMDocument
WCTYPE|wt.epm.structure.EPMMemberLink|casc.sast.805.DefaultEPMMemberLink=WCTYPE|wt.epm.structure.EPMMemberLink||casc.sast.149.DefaultEPMMemberLink
WCTYPE|wt.epm.EPMDocumentMaster|casc.sast.805.DefaultEPMDocumentMaster=WCTYPE|wt.epm.EPMDocumentMaster||casc.sast.149.DefaultEPMDocumentMaster

WCTYPE|wt.change2.WTChangeOrder2|casc.sast.805.CHANGE_ECN=WCTYPE|ext.ases.changepackaged.ChangePackaged

WCTYPE|ext.ases.envelope.ProcessEnvelope|casc.sast.805.APPROVEFORM=WCTYPE|ext.ases.envelope.ProcessEnvelope|casc.sast.149.APPROVEFORM
WCTYPE|ext.ases.envelope.ProcessEnvelope|casc.sast.805.RELEASEFORM=WCTYPE|ext.ases.envelope.ProcessEnvelope|casc.sast.149.RELEASEFORM
WCTYPE|wt.part.WTPartUsageLink=WCTYPE|wt.part.WTPartUsageLink

WCTYPE|wt.doc.WTDocument|casc.sast.805.DRAWING_DOC=WCTYPE|wt.doc.WTDocument|casc.sast.149.DESIGN_DOC|casc.sast.149.DRAWING_DOC
WCTYPE|wt.doc.WTDocument|com.ptc.ReferenceDocument|casc.sast.805.TECHNOTICE_DOC=WCTYPE|wt.doc.WTDocument|casc.sast.149.DESIGN_DOC|casc.sast.149.TECHNOTICE_DOC

wt.series.HarvardSeries.sh805=wt.series.HarvardSeries.newversion149
ASES_\uFFFD\u3CBF\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD=149_Part_LC
ASES_\uFFFD\u0135\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD=149_Doc_LC
ASES_\uFFFD\uFFFD\uFFFD\uFFFD\u01E9\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD=149_Envelope_LC
ASES_CAD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD=149_EPM_LC
ASES_\uFFFD\uFFFD\u04E1\uFFFD\uFFFD\uFFFD\uBD65\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD=149_ReleasedPackaged_LC
ASES_\uFFFD\uFFFD\uFFFD\u0368\uFFFD\uFFFDECN\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD=149_ChangePackaged_LC


UNDERREVIEW=PROCESSCOUNTERSIGN

APPROVED=APPROVED
ISSTANDARDIMPORT=false

#\u022B\uFFFD\uFFFD\uFFFD\uFFFD\u01A5\uFFFD\uFFFD\uFFFD\u01E9\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u05F4\u032C
DESIGN=PROCESSCOUNTERSIGN
ASES_MODIFY=PROCESSCOUNTERSIGN
ASES_CANCELLED=PROCESSCOUNTERSIGN
INWORK=PROCESSCOUNTERSIGN


SERVER_SERVICE_URL=http://pds.805.sast.casc/Windchill/servlet/RPC
SERVER_USERNAME=149
SERVER_USERPASS=149

SERVER_805_URL=http://pds.805.sast.casc/Windchill/servlet/RPC
SERVER_805_USERNAME=149
SERVER_805_PASSWORD=149



#8 \uFFFD\uFFFD


SERVER_No8_URL=http://a4app.no8.sast.casc/avidm/servlet/RPC
SERVER_No8_USERNAME=149
SERVER_No8_PASSWORD=149


ProdCmApproveOrder=WCTYPE|ext.ases.envelope.ProcessEnvelope|casc.sast.149.APPROVEFORM
DisOrder=WCTYPE|ext.ases.envelope.ProcessEnvelope|casc.sast.149.RELEASEFORM


ProdCmEco=WCTYPE|ext.ases.changepackaged.ChangePackaged
ProdCmEcr=WCTYPE|ext.ases.changerequest.ChangeRequest
ProdCmRevieworder=WCTYPE|ext.ases.envelope.ProcessEnvelope|casc.sast.149.PREVIEWPKG


WCTYPE|wt.epm.structure.EPMMemberLink|casc.sast.no8.DefaultEPMMemberLink=WCTYPE|wt.epm.structure.EPMMemberLink|casc.sast.149.DefaultEPMMemberLink
WCTYPE|wt.epm.EPMDocument|casc.sast.no8.DefaultEPMDocumentt=WCTYPE|wt.epm.EPMDocument|casc.sast.149.DefaultEPMDocument
WCTYPE|wt.epm.EPMDocumentMaster|casc.sast.no8.DefaultEPMDocumentMaster=WCTYPE|wt.epm.EPMDocumentMaster||casc.sast.149.DefaultEPMDocumentMaster

WCTYPE|wt.doc.WTDocument|casc.sast.no8.sjwj|casc.sast.no8.CX=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.WRITINGORFORM_DOC
WCTYPE|wt.doc.WTDocument|com.ptc.ReferenceDocument|casc.sast.no8.sjwj1=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.WRITINGORFORM_DOC

WCTYPE|wt.doc.WTDocument|casc.sast.no8.sjwj|casc.sast.no8.BXJPTB=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.WRITINGORFORM_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.sjwj|casc.sast.no8.BWJHZB=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.WRITINGORFORM_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.sjwj|casc.sast.no8.CPPTB=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.WRITINGORFORM_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.sjwj|casc.sast.no8.CX=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.WRITINGORFORM_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.sjwj|casc.sast.no8.DMSBPTB=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.WRITINGORFORM_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.sjwj|casc.sast.no8.GZJHZB=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.WRITINGORFORM_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.sjwj|casc.sast.no8.JSSMS=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.WRITINGORFORM_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.sjwj|casc.sast.no8.JSTJ=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.WRITINGORFORM_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.sjwj|casc.sast.no8.JSWJ=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.WRITINGORFORM_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.sjwj|casc.sast.no8.JKWJ=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.WRITINGORFORM_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.sjwj|casc.sast.no8.JYJHZB=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.WRITINGORFORM_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.sjwj|casc.sast.no8.QTB=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.WRITINGORFORM_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.sjwj|casc.sast.no8.QT=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.WRITINGORFORM_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.sjwj|casc.sast.no8.SJYQ=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.WRITINGORFORM_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.sjwj|casc.sast.no8.SJWJHZB=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.WRITINGORFORM_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.sjwj|casc.sast.no8.SYWHSMS=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.WRITINGORFORM_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.sjwj|casc.sast.no8.SYWJHZB=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.WRITINGORFORM_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.sjwj|casc.sast.no8.SYDG=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.WRITINGORFORM_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.sjwj|casc.sast.no8.TYPTB=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.WRITINGORFORM_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.sjwj|casc.sast.no8.XZ=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.WRITINGORFORM_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.sjwj|casc.sast.no8.YZRWS=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.WRITINGORFORM_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.sjwj|casc.sast.no8.YYWJHZB=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.WRITINGORFORM_DOC


WCTYPE|wt.doc.WTDocument|casc.sast.no8.RJSJWJ|casc.sast.no8.JKSJSM=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.WRITINGORFORM_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.sjwj|casc.sast.no8.SJYQ=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.WRITINGORFORM_DOC

WCTYPE|wt.doc.WTDocument|casc.sast.no8.WLWD=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.WRITINGORFORM_DOC

WCTYPE|wt.doc.WTDocument|casc.sast.no8.TYWJ|casc.sast.no8.LJT=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.DRAWING_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.TYWJ|casc.sast.no8.AZT=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.DRAWING_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.TYWJ|casc.sast.no8.BZT=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.DRAWING_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.TYWJ|casc.sast.no8.BWAPT=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.DRAWING_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.TYWJ|casc.sast.no8.DLT=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.DRAWING_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.TYWJ|casc.sast.no8.JXT=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.DRAWING_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.TYWJ|casc.sast.no8.LLWXT=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.DRAWING_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.TYWJ|casc.sast.no8.MXB=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.DRAWING_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.TYWJ|casc.sast.no8.QTT=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.DRAWING_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.TYWJ|casc.sast.no8.QYYYLT=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.DRAWING_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.TYWJ|casc.sast.no8.SPCLT=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.DRAWING_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.TYWJ|casc.sast.no8.XTT=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.DRAWING_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.TYWJ|casc.sast.no8.ZCDGT=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.DRAWING_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.TYWJ|casc.sast.no8.ZPT=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.DRAWING_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.TYWJ|casc.sast.no8.ZT=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.DRAWING_DOC

WCTYPE|wt.doc.WTDocument|casc.sast.no8.YSWJ=WCTYPE|wt.doc.WTDocument|casc.sast.149.RESEARCH_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.YSWJ|casc.sast.no8.BZHSCBG=WCTYPE|wt.doc.WTDocument|casc.sast.149.RESEARCH_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.YSWJ|casc.sast.no8.CSBG=WCTYPE|wt.doc.WTDocument|casc.sast.149.RESEARCH_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.YSWJ|casc.sast.no8.DXBG=WCTYPE|wt.doc.WTDocument|casc.sast.149.RESEARCH_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.YSWJ|casc.sast.no8.FABG=WCTYPE|wt.doc.WTDocument|casc.sast.149.RESEARCH_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.YSWJ|casc.sast.no8.FXBG=WCTYPE|wt.doc.WTDocument|casc.sast.149.RESEARCH_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.YSWJ|casc.sast.no8.GLGLBG=WCTYPE|wt.doc.WTDocument|casc.sast.149.RESEARCH_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.YSWJ|casc.sast.no8.GLGLGZQKBG=WCTYPE|wt.doc.WTDocument|casc.sast.149.RESEARCH_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.YSWJ|casc.sast.no8.GDSM=WCTYPE|wt.doc.WTDocument|casc.sast.149.RESEARCH_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.YSWJ|casc.sast.no8.JSFXBG=WCTYPE|wt.doc.WTDocument|casc.sast.149.RESEARCH_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.YSWJ|casc.sast.no8.JSGGBG=WCTYPE|wt.doc.WTDocument|casc.sast.149.RESEARCH_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.YSWJ|casc.sast.no8.JSGLBG=WCTYPE|wt.doc.WTDocument|casc.sast.149.RESEARCH_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.YSWJ|casc.sast.no8.JSBG=WCTYPE|wt.doc.WTDocument|casc.sast.149.RESEARCH_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.YSWJ|casc.sast.no8.JDZS=WCTYPE|wt.doc.WTDocument|casc.sast.149.RESEARCH_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.YSWJ|casc.sast.no8.JJXYFX=WCTYPE|wt.doc.WTDocument|casc.sast.149.RESEARCH_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.YSWJ|casc.sast.no8.LCT=WCTYPE|wt.doc.WTDocument|casc.sast.149.RESEARCH_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.YSWJ|casc.sast.no8.LZBG=WCTYPE|wt.doc.WTDocument|casc.sast.149.RESEARCH_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.YSWJ|casc.sast.no8.QTWJ=WCTYPE|wt.doc.WTDocument|casc.sast.149.RESEARCH_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.YSWJ|casc.sast.no8.SYBG=WCTYPE|wt.doc.WTDocument|casc.sast.149.RESEARCH_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.YSWJ|casc.sast.no8.YJBG=WCTYPE|wt.doc.WTDocument|casc.sast.149.RESEARCH_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.YSWJ|casc.sast.no8.YZJH=WCTYPE|wt.doc.WTDocument|casc.sast.149.RESEARCH_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.YSWJ|casc.sast.no8.YZZJ=WCTYPE|wt.doc.WTDocument|casc.sast.149.RESEARCH_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.YSWJ|casc.sast.no8.YSJL=WCTYPE|wt.doc.WTDocument|casc.sast.149.RESEARCH_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.YSWJ|casc.sast.no8.ZLBG=WCTYPE|wt.doc.WTDocument|casc.sast.149.RESEARCH_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.YSWJ|casc.sast.no8.DG=WCTYPE|wt.doc.WTDocument|casc.sast.149.RESEARCH_DOC

WCTYPE|wt.doc.WTDocument|com.ptc.ReferenceDocument|casc.sast.no8.yswj1=WCTYPE|wt.doc.WTDocument|casc.sast.149.Design_Doc|casc.sast.149.DRAWING_DOC|casc.sast.149.WRITINGORFORM_DOC
WCTYPE|wt.doc.WTDocument|casc.sast.no8.PLD=WCTYPE|wt.doc.WTDocument|casc.sast.149.DESIGN_DOC|casc.sast.149.TECHNOTICE_DOC
#\uFFFD\uFFFD\uFFFD\uFFFD
wt.series.HarvardSeries=wt.series.HarvardSeries.newversion149


#\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD
NO8EcaLifecycle=149_Envelope_LC
WTDocument_ObjsLC=149_Doc_LC
WTPart_ObjsLC=149_Part_LC
EPMDocument_ObjsLC=149_EPM_LC
NO8EcoLifecycle=149_ChangePackaged_LC
NO8DisOrderLifecycle=149_Envelope_LC
NO8EcrLifecycle=149_ChangeRequest_LC
NO8ROLifecycle=149_Preview_LC
#\u05F4\u032C
\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD=PROCESSCOUNTERSIGN
DESIGN=PROCESSCOUNTERSIGN
WORKFLOWLOCK=PROCESSCOUNTERSIGN
CONTROL=PROCESSCOUNTERSIGN
WORKFLOWREJECT=PROCESSCOUNTERSIGN
\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u02FB\uFFFD=PROCESSCOUNTERSIGN
DisOrderState=APPROVED
CHANGE=PROCESSCOUNTERSIGN
PROCESSREVIEW=PROCESSCOUNTERSIGN
#\uFFFD\u6C7E
A=a
B=b
C=c
D=d
E=e
F=f


#\uFFFD\uFFFD\uFFFD\uFFFD
ENDITEM=ENDITEMIN
BEIZHU=REMARK

ument_phase=PHASE_CODE
#\uFFFD\u05F6\u03B1\uFFFD\u02B6

CPDH=PINDEX
#\uFFFD\uFFFD\u01B7\uFFFD\uFFFD\uFFFD\uFFFD


GZJBZ=KEYCOMPONENT
#\uFFFD\uFFFD\uFFFD\u063C\uFFFD\uFFFD\uFFFD\u02B6


MJ=SECRET
#\uFFFD\u073C\uFFFD


CLMC=PTC_MATERIAL_NAME
#\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD


CLGG=CSIZE
#\uFFFD\uFFFD\uFFFD\u03F9\uFFFD\uFFFD


BZ=REMARK
BEIZHU=REMARK
#\uFFFD\uFFFD\u05E2


#YZDW=RM_DEPARTMENT
#\uFFFD\uFFFD\uFFFD\u01B5\uFFFD\u03BB


#CLXN
#\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD


TF=SIZE
#\u037C\uFFFD\uFFFD


partkit=SETMARK
#\uFFFD\uFFFD\uFFFD\u05FC\uFFFD\uFFFD\uFFFD\u02B6


#ZL
#PRO_MP_MASS


LBJLX=CTYPE
#\uFFFD\u3CBF\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD


XHDH=MINDEX
#\uFFFD\u037A\u0174\uFFFD\uFFFD\uFFFD

partkit=SETMARK
#\uFFFD\uFFFD\uFFFD\u05FC\uFFFD\uFFFD\uFFFD\u02B6

document_phase=PHASE_CODE
#\uFFFD\uFFFD\u01F0\uFFFD\u05F6\uFFFD

GZJBZ=KEYCOMPONENT
#\uFFFD\uFFFD\uFFFD\u063C\uFFFD\uFFFD\uFFFD\u02B6


#####\uFFFD\u0135\uFFFD


#####\u037C\uFFFD\uFFFD

DOCUMENTDEPARTMENT=DEPT
#\uFFFD\uFFFD\uFFFD\u01B2\uFFFD\uFFFD\uFFFD

CHANPINDAIHAO=PINDEX
#\uFFFD\uFFFD\u01B7\uFFFD\uFFFD\uFFFD\uFFFD

DOCUMENTPHASE=PHASE_CODE
#\uFFFD\u05F6\uFFFD

DOCUMENTSECURITY=SECRET
#\uFFFD\u0135\uFFFD\uFFFD\u073C\uFFFD

SUBTYPE=SUBTYPE
#\uFFFD\u0135\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD

PRODUCTNAME=PRODUCT_NAME
#\uFFFD\uFFFD\u01B7

DOCUMENTPROFESSION=PROFESSION
#\u05E8\u04B5

ZERENZHE=RESPONSOR
#\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD

DOCUMENTDESCRIPTION=REMARK
#\uFFFD\uFFFD\u05E2


#812\u914D\u7F6E

\u53D7\u63A7\u4E2D=APPROVED
812_\u6587\u6863\u751F\u547D\u5468\u671F=149_Doc_LC
812_\u6280\u672F\u6587\u4EF6\u7B7E\u5BA1\u5305\u751F\u547D\u5468\u671F=149_Envelope_LC
812_\u6B63\u5F0F\u53D1\u653E\u5305\u751F\u547D\u5468\u671F=149_Envelope_LC
812_\u96F6\u90E8\u4EF6\u751F\u547D\u5468\u671F=149_Part_LC
812_\u8BBE\u8BA1\u6587\u4EF6\u53D8\u66F4\u751F\u547D\u5468\u671F=149_ChangePackaged_LC
812_\u5DE5\u827A\u901A\u77E5\u5355\u751F\u547D\u5468\u671F=149_Doc_LC

WCTYPE|ext.ases.envelope.rocessEnvelope|casc.sast.812.APPROVEFORM_ZY=WCTYPE|ext.ases.envelope.ProcessEnvelope|casc.sast.149.APPROVEFORM
WCTYPE|wt.doc.WTDocument|casc.sast.812.PROCESSDOC|casc.sast.812.MACHINING_PROCESSPLAN=WCTYPE|wt.doc.WTDocument|casc.sast.149.DESIGN_DOC|casc.sast.149.TECHNOTICE_DOC
WCTYPE|ext.ases.envelope.ProcessEnvelope|casc.sast812.812FFD=WCTYPE|ext.ases.envelope.ProcessEnvelope|casc.sast.149.RELEASEFORM
WCTYPE|wt.change2.WTChangeOrder2|casc.sast.812.PROCESSDOC_ECN=WCTYPE|ext.ases.changepackaged.ChangePackaged
WCTYPE|wt.change2.WTChangeOrder2|casc.sast812.SJWJ_ECN=WCTYPE|ext.ases.changepackaged.ChangePackaged
WCTYPE|wt.doc.WTDocument|casc.sast.812.GYTZD=WCTYPE|wt.doc.WTDocument|casc.sast.149.DESIGN_DOC|casc.sast.149.TECHNOTICE DOC
#509\u914D\u7F6E
509ROLifecycle=149_Preview_LC
