WCTYPE|wt.part.WTPart=WCTYPE|wt.part.WTPart

WCTYPE|wt.epm.EPMDocument|casc.sast.DefaultEPMDocument=WCTYPE|wt.epm.EPMDocument|casc.sast.149.DefaultEPMDocument
WCTYPE|wt.epm.structure.EPMMemberLink|casc.sast.DefaultEPMMemberLink=WCTYPE|wt.epm.structure.EPMMemberLink|casc.sast.149.DefaultEPMMemberLink

WCTYPE|wt.epm.EPMDocumentMaster|casc.sast.DefaultEPMDocumentMaster=WCTYPE|wt.epm.EPMDocumentMaster|casc.sast.149.DefaultEPMDocumentMaster


WCTYPE|wt.part.WTPart|casc.sast.GLCatalogItemPart=WCTYPE|wt.part.WTPart|casc.sast.149.GLCatalogItemPart
WCTYPE|wt.part.WTPart|casc.sast.BZJPart=WCTYPE|wt.part.WTPart
WCTYPE|wt.part.WTPart|casc.sast.JSCLPart=WCTYPE|wt.part.WTPart|casc.sast.149.JSCLPart
WCTYPE|wt.part.WTPart|casc.sast.FJSCLPart=WCTYPE|wt.part.WTPart|casc.sast.149.FJSCLPart
WCTYPE|wt.part.WTPart|casc.sast.FHCLPart=WCTYPE|wt.part.WTPart|casc.sast.149.FHCLPart
WCTYPE|wt.part.WTPart|casc.sast.ElectricalPart=WCTYPE|wt.part.WTPart

#wt.series.HarvardSeries=wt.series.HarvardSeries.newversion149


SAST_标准件生命周期=149_Part_LC
SAST_元器件生命周期=149_Part_LC
SAST_金属材料生命周期=149_Part_LC
SAST_复合材料生命周期=149_Part_LC
Basic=149_Part_LC
SAST_EPM生命周期=149_EPM_LC
SAST_非金属材料生命周期=149_Part_LC
基本=149_Part_LC
BIANZHIZHONG=INWORK
SHENQINGZHONG=INWORK
RELEASED=APPROVED
Gong Yi Hui Qian=INWORK

MATERIAL=CMAT
STANDARD=CSIZE