package com.glaway.mpm.sjzyk;

import com.glaway.mpm.model.UploadTechnics;
import com.glaway.mpm.pdf.PDFBuilder;
import com.glaway.mpm.util.CommonUtil;
import com.glaway.mpm.util.ObjectTransfer;
import com.glaway.mpm.util.WorkSpaceUtil;
import com.glaway.mpm.util.XmlUtility;
import com.glaway.mpm.view.*;
import com.glaway.mpm.visual.view.action.VaActionProgressBar;
import org.dom4j.DocumentHelper;
import org.dom4j.Element;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.io.File;
import java.util.*;
import java.util.List;

public class ShowMatchPartJDialog extends javax.swing.JDialog {

	private static final long serialVersionUID = 1L;
	private NewTechnicsPart frame;
    private XWTreeNode node;
    private Element techEle;

    private JButton jButton1;
    private JButton jButton2;
    private JButton jButton3;
    private JButton jButton4;
    private JButton jButton5;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JScrollPane jScrollPane1;
    private JTable jTable1;
    private JDialog dialog;

    private static VaActionProgressBar progressBar;

	/**
     * Creates new form GydeForSjzykJDialog
     */
    public ShowMatchPartJDialog(NewTechnicsPart frame, XWTreeNode node, boolean modal) {
        super(frame, modal);
        this.frame = frame;
        this.node = node;
        initComponents();
        this.dialog = this;
        setMiddleOnScreenWithDialog(this);
        loadData();
        init();
    }
    private void init() {
    	TableColumn tableColumn = jTable1.getColumn("单位");
        tableColumn.setCellEditor(new DefaultCellEditor(CommonUtil.getDWJComboBox()));
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

    	jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PBOM标准件/元器件匹配设计编码");

        jButton1.setText("匹配标准件编码");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMatchStandardPartJDialog(evt);
            }
        });

        jButton2.setText("匹配元器件编码");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMatchYQJPartJDialog(evt);
            }
        });

        jButton3.setText("移  除");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addGap(38, 38, 38)
                .addComponent(jButton2)
                .addGap(40, 40, 40)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)

                    )

                .addContainerGap(12, Short.MAX_VALUE))
        );

        jButton4.setText("保  存");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save(evt);
            }
        });

        jButton5.setText("取  消");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(60, 60, 60)
                .addComponent(jButton5)
                .addGap(53, 53, 53))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "序号", "图号", "编号", "名称", "工艺数量", "单位", "规格", "类型", "object","备注"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class,java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, false, false, false,false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        CommonUtil.setTableStyle(jTable1);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setMinWidth(50);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(100);
        jTable1.getColumnModel().getColumn(1).setMinWidth(100);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(2).setMinWidth(100);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(3).setMinWidth(100);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(4).setMinWidth(50);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(70);
        jTable1.getColumnModel().getColumn(5).setMinWidth(50);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(70);
        jTable1.getColumnModel().getColumn(6).setMinWidth(50);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(70);
        jTable1.getColumnModel().getColumn(7).setMinWidth(50);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(70);
        jTable1.getColumnModel().getColumn(9).setMinWidth(50);
        jTable1.getColumnModel().getColumn(9).setPreferredWidth(100);
        setHideColumn(jTable1, 8);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }

    private void showMatchStandardPartJDialog(ActionEvent evt) {
    	progressBar = new VaActionProgressBar(null,this, "查询匹配标准件", "正在初始化界面,请等待...", "界面加载中");
    	Thread thread = new Thread() {
			public void run() {
		    	MatchStandardPartJDialog sdialog = new MatchStandardPartJDialog(frame, node, dialog, true,progressBar);
		    	sdialog.setVisible(true);
			}
		};
		thread.start();
		progressBar.setVisible(true);
    }

    private void showMatchYQJPartJDialog(ActionEvent evt) {


    	progressBar = new VaActionProgressBar(null,this, "查询匹配元器件", "正在初始化界面,请等待...", "界面加载中");
    	Thread thread = new Thread() {
			public void run() {
				MatchYQJPartJDialog ydialog = new MatchYQJPartJDialog(frame, node, dialog, true,progressBar);
		    	ydialog.setVisible(true);
			}
		};
		thread.start();
		progressBar.setVisible(true);
    }

    private void remove(ActionEvent evt) {
    	int rows = jTable1.getRowCount();
    	if(rows == 0) {
    		JOptionPane.showMessageDialog(this, "没有需要移除的数据！");
    	} else {
    		int[] sels = jTable1.getSelectedRows();
    		if(sels == null || sels.length == 0) {
    			JOptionPane.showMessageDialog(this, "请选择需要移除的数据！");
    		} else {
    			DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
				Element techEle = null;
				XWTreeNode currentTechNode = frame.technicsTreePanel.getSelectedTreeNode();
				XWTreeObject treeObj = currentTechNode.getObject();
				if(treeObj instanceof XWTechnicsTreeObject) {
					XWTechnicsTreeObject techObj = (XWTechnicsTreeObject)treeObj;
					techEle = techObj.getTreeCellData();
				}

				if(techEle == null) {
					JOptionPane.showMessageDialog(frame, "没有找到工艺数据，请选择工艺文件进行工艺定额！");
					return;
				}
					Map<String, PDFBuilder.CzjPart> czjPartMap = PDFBuilder.getAllCzjMap(techEle);
				String message = "";
    			for (int i : sels) {
					String partNumber = (String) tableModel.getValueAt(i,2);
					if(czjPartMap.containsKey(partNumber)){
						if("".equals(message)){
							message  = partNumber;
						}else{
							message = message + "," + partNumber;
						}
					}
				}
				if("".equals(message)){
					for (int i = 0; i < sels.length; i++) {
						tableModel.removeRow(jTable1.getSelectedRow());
					}
				}else{
					JOptionPane.showMessageDialog(frame, message + "已参与参装，请先取消参装再进行删除！");
					return;
				}
    		}
    	}
    }

    private void loadData() {
		XWTreeNode currentTechNode = frame.technicsTreePanel.getSelectedTreeNode();
		XWTreeObject treeObj = currentTechNode.getObject();
		if(treeObj instanceof XWTechnicsTreeObject) {
			XWTechnicsTreeObject techObj = (XWTechnicsTreeObject)treeObj;
			techEle = techObj.getTreeCellData();
		}

		List<SjzykBean> list = new ArrayList<SjzykBean>();
		//获取工艺定额元素下的标准间/元器件子元素
		Element gyde = XmlUtility.getTechnicsDEElement(techEle);
		List<Element> matchParts = XmlUtility.getTechnicsSJZYKGYDEMatchPart(gyde);
		if(matchParts != null && !matchParts.isEmpty()) {
			for (Element element : matchParts) {
				list.add(CommonUtil.creatSjzykBean(element));
			}
			XWTreeNode partNode = frame.xwPartTreePanel.getSelectedTreeNode().getP();
			buildSyzjkBeans(partNode, list);
		} else {
			XWTreeNode partNode = frame.xwPartTreePanel.getSelectedTreeNode().getP();
			buildSyzjkBeans(partNode, list);
		}

		for (SjzykBean bean : list) {
			setRowValues(bean);
		}
    }

    private void buildSyzjkBeans(XWTreeNode partNode, List<SjzykBean> list) {
    	XWTreeNode childNode = null;
    	XWPartTreeObject partObj = null;
    	String mtype = "";
    	String CTYPE = "";
		Enumeration num = partNode.children();
		while(num.hasMoreElements()) {
			childNode = (XWTreeNode)num.nextElement();
			if(childNode.getObject() instanceof XWPartTreeObject) {
				partObj = (XWPartTreeObject)childNode.getObject();
				mtype = partObj.getTreeCellData().attributeValue("MTYPE");
				CTYPE = partObj.getTreeCellData().attributeValue("CTYPE");
				if("标准件".equals(mtype) || "元器件".equals(mtype)|| "外购件".equals(mtype)||"标准件".equals(CTYPE) || "元器件".equals(CTYPE)|| "外购件".equals(CTYPE)) {
					SjzykBean bean = newSjzykBean(partObj);
					if(!list.contains(bean)){
						list.add(bean);
					}
				}
				//buildSyzjkBeans(childNode, list);
			}
		}
    }

    private SjzykBean newSjzykBean(Object obj) {
    	SjzykBean bean = new SjzykBean();
    	if(obj instanceof XWPartTreeObject) {
    		XWPartTreeObject part = (XWPartTreeObject)obj;
    		bean.setPartNumber(part.getTreeCellData().attributeValue("partNumber"));
    		String usecount_805 =part.getTreeCellData().attributeValue("usecount_805");
    		if(null==usecount_805 || "null".equals(usecount_805) || "".equals(usecount_805)){
    			String usecount=part.getTreeCellData().attributeValue("useCount");
    			if(null==usecount){
    				usecount="";
    			}
    			bean.setSjsl(usecount);
    		}else{
    			bean.setSjsl(usecount_805);
    		}
    		String MTYPE = part.getTreeCellData().attributeValue("MTYPE") ;
    		if("".equals(MTYPE)||"null".equals(MTYPE)){
    			MTYPE = part.getTreeCellData().attributeValue("CTYPE") ;
    		}
    		bean.setDataType(CommonUtil.formatTypeString(MTYPE));
    		//名称
    		bean.setName(part.getTreeCellData().attributeValue("partName"));
    		//标准号
    		bean.setBzh(part.getTreeCellData().attributeValue("STANDARDNUMBER"));
    		//规格
    		bean.setGg(part.getTreeCellData().attributeValue("CSIZE"));
    		//材料
    		bean.setCl(part.getTreeCellData().attributeValue("CMAT"));
    		//型号
    		bean.setXh(part.getTreeCellData().attributeValue("TYPE"));
    		//型号规格
    		bean.setXhgg(part.getTreeCellData().attributeValue("TYPESTANDARD"));
    		bean.setComment(part.getTreeCellData().attributeValue("content"));
    		bean.setGysl(part.getTreeCellData().attributeValue("gysl"));
    		//机械性能等级
    		bean.setJxxndjhyd(part.getTreeCellData().attributeValue("MECHANICALPROPERTYORHARDNESS"));
			//表面处理
			bean.setBmcl(part.getTreeCellData().attributeValue("SURFACETREATMENT"));
			//热处理
			bean.setRcl(part.getTreeCellData().attributeValue("HEATTREATMENT"));
			//产品形式
			bean.setCpxs(part.getTreeCellData().attributeValue("PRODUCTFORM"));
			//产品等级
			bean.setCpdj(part.getTreeCellData().attributeValue("PRODUCTLEVEL"));
			//扳拧形式
			bean.setBnxs(part.getTreeCellData().attributeValue("PLATECSCREWFORM"));
			//是否进口
			bean.setSfjk(part.getTreeCellData().attributeValue("ISIMPORT"));
			//计量单位
			bean.setJldw(part.getTreeCellData().attributeValue("MEASUREUNIT"));
			//特殊说明
			bean.setTssm(part.getTreeCellData().attributeValue(""));
			//优选级别
			bean.setBmyyjb(part.getTreeCellData().attributeValue("YXJB"));
			//编码类型
			bean.setBmlx(part.getTreeCellData().attributeValue("BMLX"));
			//编码状态
			bean.setBmzt(part.getTreeCellData().attributeValue("BMZT"));
			//供应商
			bean.setGys("");
    	} else if (obj instanceof Element) {
    		Element ele = (Element)obj;
    		bean = CommonUtil.creatSjzykBean(ele);
    	}
    	return bean;
    }

    private void save(ActionEvent evt) {

    	if(!CommonUtil.checkValueIsNull(jTable1.getModel(), new int[]{4,5})) {
    		JOptionPane.showMessageDialog(this, "工艺数量、单位不能为空！");
			return;
    	}
    	if(!CommonUtil.checkIsNumeric(jTable1.getModel(), new int[]{4})) {
    		JOptionPane.showMessageDialog(this, "工艺数量只能填写0-9的数字！！");
			return;
    	}

    	int flag = JOptionPane.showConfirmDialog(this, "确定保存吗？","确认", JOptionPane.OK_CANCEL_OPTION);
		if(flag==JOptionPane.YES_OPTION){
			//当前工艺
			Element techEle = null;
			XWTreeNode currentTechNode = frame.technicsTreePanel.getSelectedTreeNode();
			XWTreeObject treeObj = currentTechNode.getObject();
			if(treeObj instanceof XWTechnicsTreeObject) {
				XWTechnicsTreeObject techObj = (XWTechnicsTreeObject)treeObj;
				techEle = techObj.getTreeCellData();
			}

			if(techEle == null) {
				JOptionPane.showMessageDialog(this, "没有找到工艺数据，请选择工艺文件进行工艺定额！");
				return;
			}

			//获取工艺定额元素下查询匹配的标准间/元器件子元素
			Element gyde = XmlUtility.getTechnicsDEElement(techEle);
			Element matchpart = XmlUtility.getChildElements(gyde, "SJZYKMATCHPART");
			if(matchpart == null) {
				matchpart = DocumentHelper.createElement("SJZYKMATCHPART");
			} else {
				Map<String, PDFBuilder.CzjPart> map = PDFBuilder.getAllCzjMap(techEle);
				Map<String, String> newPartMap = new HashMap<String, String>();
				List<Element> matchpartElements = matchpart.elements("SjzykMatchPart");
				for (Element matchpartElement : matchpartElements) {
					newPartMap.put(matchpartElement.attributeValue("sjbm"), matchpartElement.attributeValue("gysl"));
				}
				for (int i = 0; i < jTable1.getRowCount(); i++) {
					String partNumber = (String) jTable1.getModel().getValueAt(i, 2);
					String setCount = (String) jTable1.getModel().getValueAt(i, 4);
					if (map.containsKey(partNumber)) {
						double useCount = map.get(partNumber).getCount();
						if (newPartMap.get(partNumber) != null && useCount > Double.valueOf(setCount)) {
							JOptionPane.showMessageDialog(frame, "参装件:" + partNumber + "，已参装数量为：" + useCount + "，超出当前设置数量：" + setCount + "，保存失败！");
							return;
						}
					}
				}
				XmlUtility.deleteAllChildElements(matchpart);
			}

			DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
			SjzykBean bean = null;
			for(int i=0;i<jTable1.getRowCount();i++){
				bean = (SjzykBean)tableModel.getValueAt(i, 8);
				bean.setGysl((String) jTable1.getValueAt(i, 4));
				bean.setDw((String) jTable1.getValueAt(i, 5));


				Element matchPartEle = CommonUtil.createPartElement(i, bean, "SjzykMatchPart");
				matchpart.add(matchPartEle);
			}

			String techPath = WorkSpaceUtil.getTechnicsDirectory(techEle.attributeValue("technicsNumber"));
			String xmlFilePath = techPath + File.separator + techEle.attributeValue("technicsNumber")+".xml";
			try {
				XmlUtility.saveDocument(techEle.getDocument(), xmlFilePath);
			} catch (Exception e1) {
				e1.printStackTrace();
			}

			UploadTechnics technics = ObjectTransfer.technicsElementToUploadTechnics(techEle);
			if (!frame.editTechnics.contains(technics)) {
				frame.editTechnics.add(technics);
			}
		}

		this.setVisible(false);
    }

    private void close(ActionEvent evt) {
        this.setVisible(false);
    }

    public void setValues(List<Object> list, String dataType) {
    	if(list == null || list.isEmpty()) {
    		return ;
    	}

    	//过滤在该表中已经存在的数据，删除在该表中有而在选择界面中被移除掉的数据
    	//list = processData(list, dataType);

    	SjzykBean bean = null;
    	for (Object obj:list) {
			if(obj instanceof SjzykBean) {
				bean = (SjzykBean)obj;
				//bean.setDataType(dataType);
				resetRowValues(bean);
			}
		}
    }

    private void resetRowValues(SjzykBean bean) {
    	DefaultTableModel tableModel = (DefaultTableModel)jTable1.getModel();
    	int rows = jTable1.getRowCount();
    	for(int i=0;i<rows;i++) {
    		String number = String.valueOf(tableModel.getValueAt(i, 1));
    		if(number.equals(bean.getPartNumber())) {
    			tableModel.setValueAt(bean.getSjbm(), i, 2);
    			tableModel.setValueAt(bean.getName(), i, 3);
    			tableModel.setValueAt(bean.getGysl(), i, 4);
    			tableModel.setValueAt(bean.getDw(), i, 5);
    			tableModel.setValueAt(bean.getGg(), i, 6);
    			tableModel.setValueAt(bean, i, 8);
    			if("".equals(bean.getComment())||bean.getComment()==null||bean.getComment()=="null"){
    				tableModel.setValueAt("", i, 9);
    			}else{
    				tableModel.setValueAt(bean.getComment(), i, 9);
    			}

    		}
    	}
    }

    private void setRowValues(SjzykBean bean) {
    	//新增一行
		DefaultTableModel tableModel = (DefaultTableModel)jTable1.getModel();
		Vector<String> vector = new Vector<String>();
		for (int i = 0; i < tableModel.getColumnCount(); i++) {
			vector.add("");
		}
		tableModel.addRow(vector);

		//写入数据
		int n = jTable1.getRowCount()-1;
       if ("标准件".equals(bean.getDataType())) {

    	   //"序号", "图号", "编号", "名称", "工艺数量", "单位", "规格", "类型", "object"
    	   tableModel.setValueAt(jTable1.getRowCount(), n, 0);
    	   tableModel.setValueAt(bean.getPartNumber(), n, 1);
    	   tableModel.setValueAt(bean.getSjbm(), n, 2);
    	   tableModel.setValueAt(bean.getName(), n, 3);
    	   tableModel.setValueAt(bean.getGysl(), n, 4);
    	   tableModel.setValueAt(bean.getDw(), n, 5);
    	   tableModel.setValueAt(bean.getGg(), n, 6);
    	   tableModel.setValueAt(CommonUtil.formatType(bean.getDataType()), n, 7);
    	   tableModel.setValueAt(bean, n, 8);
    	   tableModel.setValueAt(bean.getComment(), n, 9);
       }else{
    	 //"序号", "图号", "编号", "名称", "工艺数量", "单位", "规格", "类型", "object"
    	   tableModel.setValueAt(jTable1.getRowCount(), n, 0);
    	   tableModel.setValueAt(bean.getPartNumber(), n, 1);
    	   tableModel.setValueAt(bean.getSjbm(), n, 2);
    	   tableModel.setValueAt(bean.getName(), n, 3);
    	   tableModel.setValueAt(bean.getGysl(), n, 4);
    	   tableModel.setValueAt(bean.getDw(), n, 5);
    	   tableModel.setValueAt(bean.getXhgg(), n, 6);
    	   tableModel.setValueAt(CommonUtil.formatType(bean.getDataType()), n, 7);
    	   tableModel.setValueAt(bean, n, 8);
    	   tableModel.setValueAt(bean.getComment(), n, 9);

       }
    }

    private List<Object> processData(List<Object> list, String dataType) {
    	List<String> allData = getAllDataByDataType(dataType);
    	if(allData == null || allData.isEmpty()) {
    		return list;
    	}

    	//保存需要删除的数据
    	List<String> deleteList = new ArrayList<String>(allData);

    	//保存需要新添加的数据
    	List<Object> addList = new ArrayList<Object>(list);

    	SjzykBean bean = null;
    	for (Object object : list) {
			if(object instanceof SjzykBean) {
				bean = (SjzykBean)object;

				//过滤已经存在的数据
				if(allData.contains(bean.getNumber())) {
					addList.remove(object);
					deleteList.remove(bean.getNumber());
				}
			}
		}

    	//从表中删除被移除的数据
    	if(deleteList.isEmpty()) {
    		return addList;
    	}
    	int rows = jTable1.getRowCount();
    	if(rows < 0) {
    		return addList;
    	}

    	List<Integer> delRows = new ArrayList<Integer>();
    	DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
    	for(int i=0;i<rows;i++) {
    		String number = (String)tableModel.getValueAt(i, 1);
    		if(deleteList.contains(number)) {
    			delRows.add(i);
    		}
    	}

    	if(!delRows.isEmpty()) {
    		for (Integer integer : delRows) {
    			tableModel.removeRow(integer);
			}
    	}

    	return addList;
    }

    private List<String> getAllDataByDataType(String dataType) {
    	int rows = jTable1.getRowCount();
    	if(rows < 0) {
    		return null;
    	}
    	List<String> list = new ArrayList<String>();
    	DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
    	SjzykBean bean = null;
    	for(int i=0;i<rows;i++) {
    		bean = (SjzykBean)tableModel.getValueAt(i, 8);
    		if(dataType.equals(bean.getDataType())) {
    			list.add(bean.getNumber());
    		}
    	}
    	return list;
    }

    public List<SjzykBean> getDataByDataType(String dataType) {
    	int rows = jTable1.getRowCount();
    	if(rows < 0) {
    		return null;
    	}
    	List<SjzykBean> list = new ArrayList<SjzykBean>();
    	DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
    	SjzykBean bean = null;
    	for(int i=0;i<rows;i++) {
    		bean = (SjzykBean)tableModel.getValueAt(i, 8);
    		if(dataType.equals(bean.getDataType())) {
    			list.add(bean);
    		}
    	}
    	return list;
    }

    private void setHideColumn(JTable table, int index) {
		table.getColumnModel().getColumn(index).setMinWidth(0);
		table.getColumnModel().getColumn(index).setMaxWidth(0);
	}

    public static void setMiddleOnScreenWithDialog(JDialog dialog){
		int windowWidth = dialog.getWidth();                     //获得窗口宽
	    int windowHeight = dialog.getHeight();                   //获得窗口高
	    Toolkit kit = Toolkit.getDefaultToolkit();              //定义工具包
	    Dimension screenSize = kit.getScreenSize();             //获取屏幕的尺寸
	    int screenWidth = screenSize.width;                     //获取屏幕的宽
	    int screenHeight = screenSize.height;                   //获取屏幕的高
	    dialog.setLocation(screenWidth/2-windowWidth/2, screenHeight/2-windowHeight/2);//设置窗口居中显示
	}

	public Element getTechEle() {
		return techEle;
	}
}
