package com.glaway.mpm.sjzyk;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import com.glaway.mpm.view.NewTechnicsPart;
import com.glaway.mpm.view.TechnicsPaceJDialog;
import com.glaway.mpm.view.TechnicsStepJPanel_XW;
import org.apache.tools.ant.taskdefs.optional.ejb.JbossDeploymentTool;
import org.dom4j.Element;

import com.glaway.mpm.util.XmlUtility;

public class TechnicsDEForSjzykJPanel extends JPanel {

	private Container parentPanel;

	private JButton removeButton;

	private JPanel buttonPanel;

	/**
     * Creates new form TechnicsDEForSjzykJPanel
     */
    public TechnicsDEForSjzykJPanel(Container parentPanel) {
    	this.parentPanel = parentPanel;
    	initComponents();
        setName("sjzykgyde");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

    	jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("添加的标准件/元器件"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "序号", "上级图号", "编号", "名称", "物资简称", "工艺数量", "单位", "特殊说明", "是否进口",
                "计量单位", "标准号", "规格", "材料", "机械性能等级或硬度", "表面处理", "热处理", "产品型式",
                "产品等级", "板拧形式", "型号", "型号规格", "质量等级", "总规范", "详细规范", "封装形式", "外形尺寸", "专用条件",
                "附加协议","供应商","备注",
                "编码等级","抗辐指标TID","抗辐指标SEE","性能参数","是否静电敏感","静电敏感等级","湿敏等级"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                , java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                , java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                , java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                , java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                , java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                , java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                , java.lang.String.class , java.lang.String.class
                , java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                , java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
                , false, false, false, false, false, false
                , false, false, false, false, false, false
                , false, false, false, false, false, false
                , false, false, false, false,false,false
                , false, false, false, false,false,false,false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setMinWidth(50);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(1).setMinWidth(50);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(2).setMinWidth(50);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(3).setMinWidth(50);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(4).setMinWidth(50);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(5).setMinWidth(50);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(70);
        jTable1.getColumnModel().getColumn(6).setMinWidth(50);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(70);
        jTable1.getColumnModel().getColumn(7).setMinWidth(50);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(8).setMinWidth(50);
        jTable1.getColumnModel().getColumn(8).setPreferredWidth(70);
        jTable1.getColumnModel().getColumn(9).setMinWidth(50);
        jTable1.getColumnModel().getColumn(9).setPreferredWidth(70);
        jTable1.getColumnModel().getColumn(10).setMinWidth(50);
        jTable1.getColumnModel().getColumn(10).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(11).setMinWidth(50);
        jTable1.getColumnModel().getColumn(11).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(12).setMinWidth(50);
        jTable1.getColumnModel().getColumn(12).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(13).setMinWidth(50);
        jTable1.getColumnModel().getColumn(13).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(14).setMinWidth(50);
        jTable1.getColumnModel().getColumn(14).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(15).setMinWidth(50);
        jTable1.getColumnModel().getColumn(15).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(16).setMinWidth(50);
        jTable1.getColumnModel().getColumn(16).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(17).setMinWidth(50);
        jTable1.getColumnModel().getColumn(17).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(18).setMinWidth(50);
        jTable1.getColumnModel().getColumn(18).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(19).setMinWidth(50);
        jTable1.getColumnModel().getColumn(19).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(20).setMinWidth(50);
        jTable1.getColumnModel().getColumn(20).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(21).setMinWidth(50);
        jTable1.getColumnModel().getColumn(21).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(22).setMinWidth(50);
        jTable1.getColumnModel().getColumn(22).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(23).setMinWidth(50);
        jTable1.getColumnModel().getColumn(23).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(24).setMinWidth(50);
        jTable1.getColumnModel().getColumn(24).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(25).setMinWidth(50);
        jTable1.getColumnModel().getColumn(25).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(26).setMinWidth(50);
        jTable1.getColumnModel().getColumn(26).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(27).setMinWidth(50);
        jTable1.getColumnModel().getColumn(27).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(28).setMinWidth(50);
        jTable1.getColumnModel().getColumn(28).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(29).setMinWidth(50);
        jTable1.getColumnModel().getColumn(29).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(30).setMinWidth(50);
        jTable1.getColumnModel().getColumn(30).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(31).setMinWidth(50);
        jTable1.getColumnModel().getColumn(31).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(32).setMinWidth(50);
        jTable1.getColumnModel().getColumn(32).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(33).setMinWidth(50);
        jTable1.getColumnModel().getColumn(33).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(34).setMinWidth(50);
        jTable1.getColumnModel().getColumn(34).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(35).setMinWidth(50);
        jTable1.getColumnModel().getColumn(35).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(36).setMinWidth(50);
        jTable1.getColumnModel().getColumn(36).setPreferredWidth(100);
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("匹配的标准件/元器件"));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "序号", "图号", "编号", "名称", "物资简称", "工艺数量", "单位", "特殊说明"
                , "是否进口", "计量单位", "标准号", "规格", "材料", "机械性能等级或硬度"
                , "表面处理", "热处理", "产品型式", "产品等级", "板拧形式", "型号", "型号规格"
                , "质量等级", "总规范", "详细规范", "封装形式", "外形尺寸", "专用条件"
                , "附加协议","供应商","备注",
                "编码等级","抗辐指标TID","抗辐指标SEE","性能参数","是否静电敏感","静电敏感等级","湿敏等级"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                , java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                , java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                , java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                , java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                , java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                , java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                , java.lang.String.class, java.lang.String.class
                , java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                , java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
                , false, false, false, false, false, false, false, false
                , false, false, false, false, false, false, false, false
                , false, false, false, false,false,false
                , false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);
        jTable2.getColumnModel().getColumn(0).setMinWidth(50);
        jTable2.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(1).setMinWidth(50);
        jTable2.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTable2.getColumnModel().getColumn(2).setMinWidth(50);
        jTable2.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTable2.getColumnModel().getColumn(3).setMinWidth(50);
        jTable2.getColumnModel().getColumn(3).setPreferredWidth(150);
        jTable2.getColumnModel().getColumn(4).setMinWidth(50);
        jTable2.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(5).setMinWidth(50);
        jTable2.getColumnModel().getColumn(5).setPreferredWidth(70);
        jTable2.getColumnModel().getColumn(6).setMinWidth(50);
        jTable2.getColumnModel().getColumn(6).setPreferredWidth(70);
        jTable2.getColumnModel().getColumn(7).setMinWidth(50);
        jTable2.getColumnModel().getColumn(7).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(8).setMinWidth(50);
        jTable2.getColumnModel().getColumn(8).setPreferredWidth(70);
        jTable2.getColumnModel().getColumn(9).setMinWidth(50);
        jTable2.getColumnModel().getColumn(9).setPreferredWidth(70);
        jTable2.getColumnModel().getColumn(10).setMinWidth(50);
        jTable2.getColumnModel().getColumn(10).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(11).setMinWidth(50);
        jTable2.getColumnModel().getColumn(11).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(12).setMinWidth(50);
        jTable2.getColumnModel().getColumn(12).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(13).setMinWidth(50);
        jTable2.getColumnModel().getColumn(13).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(14).setMinWidth(50);
        jTable2.getColumnModel().getColumn(14).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(15).setMinWidth(50);
        jTable2.getColumnModel().getColumn(15).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(16).setMinWidth(50);
        jTable2.getColumnModel().getColumn(16).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(17).setMinWidth(50);
        jTable2.getColumnModel().getColumn(17).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(18).setMinWidth(50);
        jTable2.getColumnModel().getColumn(18).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(19).setMinWidth(50);
        jTable2.getColumnModel().getColumn(19).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(20).setMinWidth(50);
        jTable2.getColumnModel().getColumn(20).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(21).setMinWidth(50);
        jTable2.getColumnModel().getColumn(21).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(22).setMinWidth(50);
        jTable2.getColumnModel().getColumn(22).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(23).setMinWidth(50);
        jTable2.getColumnModel().getColumn(23).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(24).setMinWidth(50);
        jTable2.getColumnModel().getColumn(24).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(25).setMinWidth(50);
        jTable2.getColumnModel().getColumn(25).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(26).setMinWidth(50);
        jTable2.getColumnModel().getColumn(26).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(27).setMinWidth(50);
        jTable2.getColumnModel().getColumn(27).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(28).setMinWidth(50);
        jTable2.getColumnModel().getColumn(28).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(28).setMinWidth(50);
        jTable2.getColumnModel().getColumn(28).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(29).setMinWidth(50);
        jTable2.getColumnModel().getColumn(29).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(30).setMinWidth(50);
        jTable2.getColumnModel().getColumn(30).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(31).setMinWidth(50);
        jTable2.getColumnModel().getColumn(31).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(32).setMinWidth(50);
        jTable2.getColumnModel().getColumn(32).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(33).setMinWidth(50);
        jTable2.getColumnModel().getColumn(33).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(34).setMinWidth(50);
        jTable2.getColumnModel().getColumn(34).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(35).setMinWidth(50);
        jTable2.getColumnModel().getColumn(35).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(36).setMinWidth(50);
        jTable2.getColumnModel().getColumn(36).setPreferredWidth(100);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );

        removeButton = new JButton("移  除");
        removeButton.setMaximumSize(new Dimension(130, 23));
        removeButton.setMinimumSize(new Dimension(130, 23));
        removeButton.setPreferredSize(new Dimension(130, 23));
        removeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                removeData();
            }
        });
        buttonPanel = new JPanel();
        buttonPanel.setLayout(new GridBagLayout());
        buttonPanel.add(removeButton,new GridBagConstraints(1, 1, 1, 1, 0.0, 0.0,
                GridBagConstraints.CENTER, GridBagConstraints.NONE, new Insets(
                5, 5, 0, 5), 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>

    private void removeData() {
        int[] rows1 = jTable1.getSelectedRows();
        int[] rows2 = jTable2.getSelectedRows();
        String number;
        String tuhao;
        List<String> newPartList = new ArrayList<String>();
        for (int i = 0; i < rows1.length; i++) {
            number = jTable1.getValueAt(jTable1.getSelectedRow(),2).toString();
            newPartList.add(number);
            ((DefaultTableModel)jTable1.getModel()).removeRow(jTable1.getSelectedRow());
        }
        List<String> matchPartList = new ArrayList<String>();
        for (int j = 0; j < rows2.length; j++) {
            tuhao = jTable2.getValueAt(jTable2.getSelectedRow(),1).toString();
            number = jTable2.getValueAt(jTable2.getSelectedRow(),2).toString();
            matchPartList.add(tuhao + "&" + number);
            ((DefaultTableModel)jTable2.getModel()).removeRow(jTable2.getSelectedRow());
        }
        NewTechnicsPart frame = null;
        Element techele = null;
        if (parentPanel instanceof NewTechnicsPart) {
            frame = (NewTechnicsPart) parentPanel;
            techele = XmlUtility.getTechnicsElement(frame.getCurrentTechnics());
        }else if (parentPanel instanceof TechnicsStepJPanel_XW) {
            frame = (NewTechnicsPart) ((TechnicsStepJPanel_XW) parentPanel).getFrame();
            techele = XmlUtility.getTechnicsElement(frame.getCurrentTechnics());
        } else if (parentPanel instanceof TechnicsPaceJDialog) {
            frame = (NewTechnicsPart) ((TechnicsPaceJDialog) parentPanel).getFrame();
            techele = XmlUtility.getTechnicsElement(frame.getCurrentTechnics());
        }
        Element gyde = XmlUtility.getTechnicsDEElement(techele);
        if (gyde != null) {
            Element newPartEle = gyde.element("SJZYKNEWPART");
            List<Element> technicsSJZYKGYDENewPart = XmlUtility.getTechnicsSJZYKGYDENewPart(gyde);
            for (Element element : technicsSJZYKGYDENewPart) {
                String sjbm = element.attributeValue("sjbm");
                if (newPartList.contains(sjbm)) {
                    newPartEle.remove(element);
                }
            }
            Element matchPartEle = gyde.element("SJZYKMATCHPART");
            List<Element> technicsSJZYKGYDEMatchPart = XmlUtility.getTechnicsSJZYKGYDEMatchPart(gyde);
            for(Element element : technicsSJZYKGYDEMatchPart){
                String partNumber = element.attributeValue("partNumber");
                String sjbm = element.attributeValue("sjbm");
                if (matchPartList.contains(partNumber + "&" + sjbm)) {
                    matchPartEle.remove(element);
                }
            }
        }
        if(frame != null){
            frame.saveProcess(techele);
        }
    }

    public void setTableValues(Element technicsElement) {
 	   clearTable();
 	   Element gyde = XmlUtility.getTechnicsDEElement(technicsElement);
 		if(gyde == null) {
 			return ;
 		}

 		List<Element> newParts = XmlUtility.getTechnicsSJZYKGYDENewPart(gyde);
 		if(newParts != null && !newParts.isEmpty()) {
 			int row = 0;
 			int n = 1;
 			for (Element element : newParts) {
 				Vector vector = new Vector();
 				for (int j = 0; j < jTable1.getColumnCount(); j++) {
 					vector.add("");
 				}
 				//"序号", "上级图号", "编号", "名称", "物资简称", "工艺数量", "单位", "特殊说明", "是否进口",
 				//"计量单位", "标准号", "规格", "材料", "机械性能等级或硬度", "表面处理", "热处理", "产品型式",
 				//"产品等级", "板拧形式", "型号", "型号规格", "质量等级", "总规范", "详细规范", "封装形式", "外形尺寸", "专用条件", "附加协议"
 				//"编码等级","抗辐指标TID","抗辐指标SEE","性能参数","是否静电敏感","静电敏感等级","湿敏等级"
 				((DefaultTableModel)jTable1.getModel()).addRow(vector);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(n, row, 0);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("partNumber"), row, 1);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("sjbm"), row, 2);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("name"), row, 3);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("wzjc"), row, 4);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("gysl"), row, 5);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("dw"), row, 6);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("tssm"), row, 7);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("sfjk"), row, 8);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("jldw"), row, 9);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("bzh"), row, 10);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("gg"), row, 11);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("cl"), row, 12);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("jxxndjhyd"), row, 13);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("bmcl"), row, 14);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("rcl"), row, 15);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("cpxs"), row, 16);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("cpdj"), row, 17);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("bnxs"), row, 18);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("xh"), row, 19);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("xhgg"), row, 20);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("zldj"), row, 21);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("zgf"), row, 22);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("xxgf"), row, 23);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("fzxs"), row, 24);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("wxcc"), row, 25);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("zytj"), row, 26);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("fjxy"), row, 27);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("gys"), row, 28);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("comment"), row, 29);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("bmdj"), row, 30);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("kfzbtid"), row, 31);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("kfzbsee"), row, 32);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("xncs"), row, 33);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("jdmgdj_state"), row, 34);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("jdmgdj"), row, 35);
 				((DefaultTableModel)jTable1.getModel()).setValueAt(element.attributeValue("smdj"), row, 36);
 				row++;
 				n++;
 			}
 		}

 		List<Element> matchParts = XmlUtility.getTechnicsSJZYKGYDEMatchPart(gyde);
 		if(matchParts != null && !matchParts.isEmpty()) {
 			int row = 0;
 			int n = 1;
 			for (Element element : matchParts) {
 				Vector vector = new Vector();
 				for (int j = 0; j < jTable2.getColumnCount(); j++) {
 					vector.add("");
 				}
 				((DefaultTableModel)jTable2.getModel()).addRow(vector);
 				//"序号", "图号", "编号", "名称", "物资简称", "工艺数量", "单位", "特殊说明", "是否进口", "计量单位",
 				//"标准号", "规格", "材料", "机械性能等级或硬度", "表面处理", "热处理", "产品型式", "产品等级", "板拧形式",
 				//"型号", "型号规格", "质量等级", "总规范", "详细规范", "封装形式", "外形尺寸", "专用条件", "附加协议"
 				//"编码等级","抗辐指标TID","抗辐指标SEE","性能参数","是否静电敏感","静电敏感等级","湿敏等级"
 				((DefaultTableModel)jTable2.getModel()).setValueAt(n, row, 0);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("partNumber"), row, 1);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("sjbm"), row, 2);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("name"), row, 3);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("wzjc"), row, 4);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("gysl"), row, 5);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("dw"), row, 6);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("tssm"), row, 7);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("sfjk"), row, 8);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("jldw"), row, 9);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("bzh"), row, 10);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("gg"), row, 11);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("cl"), row, 12);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("jxxndjhyd"), row, 13);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("bmcl"), row, 14);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("rcl"), row, 15);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("cpxs"), row, 16);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("cpdj"), row, 17);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("bnxs"), row, 18);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("xh"), row, 19);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("xhgg"), row, 20);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("zldj"), row, 21);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("zgf"), row, 22);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("xxgf"), row, 23);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("fzxs"), row, 24);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("wxcc"), row, 25);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("zytj"), row, 26);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("fjxy"), row, 27);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("gys"), row, 28);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("comment"), row, 29);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("bmdj"), row, 30);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("kfzbtid"), row, 31);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("kfzbsee"), row, 32);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("xncs"), row, 33);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("jdmgdj_state"), row, 34);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("jdmgdj"), row, 35);
 				((DefaultTableModel)jTable2.getModel()).setValueAt(element.attributeValue("smdj"), row, 36);
 				row++;
 				n++;
 			}
 		}

    }

    public void clearTable() {
 	   ((DefaultTableModel)jTable1.getModel()).setRowCount(0);
 	   ((DefaultTableModel)jTable2.getModel()).setRowCount(0);
 	}


    // Variables declaration - do not modify
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration
}
