package com.glaway.mpm.sjzyk;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import com.glaway.mpm.util.WorkSpaceUtil;
import com.glaway.mpm.view.NewTechnicsPart;
import com.glaway.mpm.view.TechnicsPaceJDialog;
import com.glaway.mpm.view.TechnicsStepJPanel_XW;
import org.dom4j.Element;

import com.glaway.mpm.util.XmlUtility;

public class TechnicsSjzykCLDEJPanel extends JPanel {

    private Container parentPanel;

    private JButton removeButton;

    private JPanel buttonPanel;

    /**
     * Creates new form TechnicsSjzykCLDEJPanel
     */
    public TechnicsSjzykCLDEJPanel(Container parentPanel) {
        this.parentPanel = parentPanel;
        initComponents();
        setName("sjzykclde");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("原材料定额信息"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "序号", "编号", "名称", "物资简称", "下料尺寸", "可制件数", "单位", "材料类型", "换算率", "系数", "牌号", "规格", "采用标准", "供应状态", "精度", "质量特征", "品种规格标准", "是否进口", "计量单位", "特殊说明", "供应商", "备注"

                }
        ) {
            Class[] types = new Class[]{
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                    , java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setMinWidth(50);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(1).setMinWidth(50);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(2).setMinWidth(50);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(3).setMinWidth(50);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(4).setMinWidth(50);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(5).setMinWidth(50);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(70);
        jTable1.getColumnModel().getColumn(6).setMinWidth(50);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(70);
        jTable1.getColumnModel().getColumn(7).setMinWidth(50);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(8).setMinWidth(50);
        jTable1.getColumnModel().getColumn(8).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(9).setMinWidth(50);
        jTable1.getColumnModel().getColumn(9).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(10).setMinWidth(50);
        jTable1.getColumnModel().getColumn(10).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(11).setMinWidth(50);
        jTable1.getColumnModel().getColumn(11).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(12).setMinWidth(50);
        jTable1.getColumnModel().getColumn(12).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(13).setMinWidth(50);
        jTable1.getColumnModel().getColumn(13).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(14).setMinWidth(50);
        jTable1.getColumnModel().getColumn(14).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(15).setMinWidth(50);
        jTable1.getColumnModel().getColumn(15).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(16).setMinWidth(50);
        jTable1.getColumnModel().getColumn(16).setPreferredWidth(130);
        jTable1.getColumnModel().getColumn(17).setMinWidth(50);
        jTable1.getColumnModel().getColumn(17).setPreferredWidth(70);
        jTable1.getColumnModel().getColumn(18).setMinWidth(50);
        jTable1.getColumnModel().getColumn(18).setPreferredWidth(70);
        jTable1.getColumnModel().getColumn(19).setMinWidth(50);
        jTable1.getColumnModel().getColumn(19).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(20).setMinWidth(50);
        jTable1.getColumnModel().getColumn(20).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(20).setMinWidth(50);
        jTable1.getColumnModel().getColumn(20).setPreferredWidth(100);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("主要材料定额信息"));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "序号", "编号", "名称", "物资简称", "数量", "单位"
                        , "材料类型", "换算率", "系数", "牌号", "规格"
                        , "采用标准", "供应状态", "精度", "质量特征", "品种规格标准"
                        , "是否进口", "计量单位", "特殊说明", "供应商",

                        "备注"
                }
        ) {
            Class[] types = new Class[]{
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                    , java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                    , java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                    , java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                    , java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false, false, false, false, false
                    , false, false, false, false, false, false, false, false, false, false
                    , false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(jTable2);
        jTable2.getColumnModel().getColumn(0).setMinWidth(50);
        jTable2.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(1).setMinWidth(50);
        jTable2.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTable2.getColumnModel().getColumn(2).setMinWidth(50);
        jTable2.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTable2.getColumnModel().getColumn(3).setMinWidth(50);
        jTable2.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(4).setMinWidth(50);
        jTable2.getColumnModel().getColumn(4).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(5).setMinWidth(50);
        jTable2.getColumnModel().getColumn(5).setPreferredWidth(70);
        jTable2.getColumnModel().getColumn(6).setMinWidth(50);
        jTable2.getColumnModel().getColumn(6).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(7).setMinWidth(50);
        jTable2.getColumnModel().getColumn(7).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(8).setMinWidth(50);
        jTable2.getColumnModel().getColumn(8).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(9).setMinWidth(50);
        jTable2.getColumnModel().getColumn(9).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(10).setMinWidth(50);
        jTable2.getColumnModel().getColumn(10).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(11).setMinWidth(50);
        jTable2.getColumnModel().getColumn(11).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(12).setMinWidth(50);
        jTable2.getColumnModel().getColumn(12).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(13).setMinWidth(50);
        jTable2.getColumnModel().getColumn(13).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(14).setMinWidth(50);
        jTable2.getColumnModel().getColumn(14).setPreferredWidth(130);
        jTable2.getColumnModel().getColumn(15).setMinWidth(50);
        jTable2.getColumnModel().getColumn(15).setPreferredWidth(70);
        jTable2.getColumnModel().getColumn(16).setMinWidth(50);
        jTable2.getColumnModel().getColumn(16).setPreferredWidth(70);
        jTable2.getColumnModel().getColumn(17).setMinWidth(50);
        jTable2.getColumnModel().getColumn(17).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(18).setMinWidth(50);
        jTable2.getColumnModel().getColumn(18).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(18).setMinWidth(50);
        jTable2.getColumnModel().getColumn(18).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(19).setMinWidth(100);
        jTable2.getColumnModel().getColumn(19).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(20).setMinWidth(100);
        jTable2.getColumnModel().getColumn(20).setPreferredWidth(100);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("试件原材料定额信息"));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "序号", "编号", "名称", "物资简称", "试件尺寸", "试件可制件数", "试件数量", "单位", "材料类型", "换算率"
                        , "系数", "牌号", "规格", "采用标准", "供应状态", "精度", "质量特征", "品种规格标准", "是否进口", "计量单位"
                        , "特殊说明"
                        , "供应商", "备注"
                }
        ) {
            Class[] types = new Class[]{
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                    , java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                    , java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                    , java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                    , java.lang.String.class, java.lang.String.class
                    , java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false, false, false, false, false
                    , false, false, false, false, false, false, false, false, false, false
                    , false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTable3.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane3.setViewportView(jTable3);
        jTable3.getColumnModel().getColumn(0).setMinWidth(50);
        jTable3.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable3.getColumnModel().getColumn(1).setMinWidth(50);
        jTable3.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTable3.getColumnModel().getColumn(2).setMinWidth(50);
        jTable3.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTable3.getColumnModel().getColumn(3).setMinWidth(50);
        jTable3.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTable3.getColumnModel().getColumn(4).setMinWidth(50);
        jTable3.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTable3.getColumnModel().getColumn(5).setMinWidth(50);
        jTable3.getColumnModel().getColumn(5).setPreferredWidth(100);
        jTable3.getColumnModel().getColumn(6).setMinWidth(50);
        jTable3.getColumnModel().getColumn(6).setPreferredWidth(70);
        jTable3.getColumnModel().getColumn(7).setMinWidth(50);
        jTable3.getColumnModel().getColumn(7).setPreferredWidth(70);
        jTable3.getColumnModel().getColumn(8).setMinWidth(50);
        jTable3.getColumnModel().getColumn(8).setPreferredWidth(100);
        jTable3.getColumnModel().getColumn(9).setMinWidth(50);
        jTable3.getColumnModel().getColumn(9).setPreferredWidth(100);
        jTable3.getColumnModel().getColumn(10).setMinWidth(50);
        jTable3.getColumnModel().getColumn(10).setPreferredWidth(100);
        jTable3.getColumnModel().getColumn(11).setMinWidth(50);
        jTable3.getColumnModel().getColumn(11).setPreferredWidth(100);
        jTable3.getColumnModel().getColumn(12).setMinWidth(50);
        jTable3.getColumnModel().getColumn(12).setPreferredWidth(100);
        jTable3.getColumnModel().getColumn(13).setMinWidth(50);
        jTable3.getColumnModel().getColumn(13).setPreferredWidth(100);
        jTable3.getColumnModel().getColumn(14).setMinWidth(50);
        jTable3.getColumnModel().getColumn(14).setPreferredWidth(100);
        jTable3.getColumnModel().getColumn(15).setMinWidth(50);
        jTable3.getColumnModel().getColumn(15).setPreferredWidth(100);
        jTable3.getColumnModel().getColumn(16).setMinWidth(50);
        jTable3.getColumnModel().getColumn(16).setPreferredWidth(100);
        jTable3.getColumnModel().getColumn(17).setMinWidth(50);
        jTable3.getColumnModel().getColumn(17).setPreferredWidth(130);
        jTable3.getColumnModel().getColumn(18).setMinWidth(50);
        jTable3.getColumnModel().getColumn(18).setPreferredWidth(70);
        jTable3.getColumnModel().getColumn(19).setMinWidth(50);
        jTable3.getColumnModel().getColumn(19).setPreferredWidth(70);
        jTable3.getColumnModel().getColumn(20).setMinWidth(50);
        jTable3.getColumnModel().getColumn(20).setPreferredWidth(100);
        jTable3.getColumnModel().getColumn(21).setMinWidth(50);
        jTable3.getColumnModel().getColumn(21).setPreferredWidth(100);
        jTable3.getColumnModel().getColumn(22).setMinWidth(50);
        jTable3.getColumnModel().getColumn(22).setPreferredWidth(100);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3)
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );

        removeButton = new JButton("移  除");
        removeButton.setMaximumSize(new Dimension(130, 23));
        removeButton.setMinimumSize(new Dimension(130, 23));
        removeButton.setPreferredSize(new Dimension(130, 23));
        removeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                removeData();
            }
        });
        buttonPanel = new JPanel();
        buttonPanel.setLayout(new GridBagLayout());
        buttonPanel.add(removeButton, new GridBagConstraints(1, 1, 1, 1, 0.0, 0.0,
                GridBagConstraints.CENTER, GridBagConstraints.NONE, new Insets(
                5, 5, 0, 5), 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>

    private void removeData() {

        int[] rows1 = jTable1.getSelectedRows();
        int[] rows2 = jTable2.getSelectedRows();
        int[] rows3 = jTable3.getSelectedRows();
        String number;
        List<String> yclList = new ArrayList<String>();
        for (int i = 0; i < rows1.length; i++) {
            number = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
            yclList.add(number);
            ((DefaultTableModel) jTable1.getModel()).removeRow(jTable1.getSelectedRow());
        }
        List<String> zyclList = new ArrayList<String>();
        for (int j = 0; j < rows2.length; j++) {
            number = jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString();
            zyclList.add(number);
            ((DefaultTableModel) jTable2.getModel()).removeRow(jTable2.getSelectedRow());
        }
        List<String> sjyclList = new ArrayList<String>();
        for (int k = 0; k < rows3.length; k++) {
            number = jTable3.getValueAt(jTable3.getSelectedRow(), 1).toString();
            sjyclList.add(number);
            ((DefaultTableModel) jTable3.getModel()).removeRow(jTable3.getSelectedRow());
        }

        NewTechnicsPart frame = null;
        Element techele = null;
        if (parentPanel instanceof NewTechnicsPart) {
            frame = (NewTechnicsPart) parentPanel;
            techele = XmlUtility.getTechnicsElement(frame.getCurrentTechnics());
        }else if (parentPanel instanceof TechnicsStepJPanel_XW) {
            frame = (NewTechnicsPart) ((TechnicsStepJPanel_XW) parentPanel).getFrame();
            techele = XmlUtility.getTechnicsElement(frame.getCurrentTechnics());
        } else if (parentPanel instanceof TechnicsPaceJDialog) {
            frame = (NewTechnicsPart) ((TechnicsPaceJDialog) parentPanel).getFrame();
            techele = XmlUtility.getTechnicsElement(frame.getCurrentTechnics());
        }
        Element clde = XmlUtility.getTechnicsCLDEElement(techele);
        if (clde != null) {
            Element yclEle = clde.element("SJZYKYCLDE");
            List<Element> technicsSJZYKYCLDE = XmlUtility.getTechnicsSJZYKYCLDE(clde);
            for (Element element : technicsSJZYKYCLDE) {
                String sjbm = element.attributeValue("sjbm");
                if (yclList.contains(sjbm)) {
                    yclEle.remove(element);
                }
            }
            Element zyclEle = clde.element("SJZYKZYCLDE");
            List<Element> technicsSJZYKZYCLDE = XmlUtility.getTechnicsSJZYKZYCLDE(clde);
            for (Element element : technicsSJZYKZYCLDE) {
                String sjbm = element.attributeValue("sjbm");
                if (zyclList.contains(sjbm)) {
                    zyclEle.remove(element);
                }
            }
            Element sjyclEle = clde.element("SJZYKSJYCLDE");
            List<Element> technicsSJZYKSJYCLDE = XmlUtility.getTechnicsSJZYKSJYCLDE(clde);
            for (Element element : technicsSJZYKSJYCLDE) {
                String sjbm = element.attributeValue("sjbm");
                if (sjyclList.contains(sjbm)) {
                    sjyclEle.remove(element);
                }
            }
        }
        if (frame != null) {
            frame.saveProcess(techele);
        }
    }

    public void setTableValues(Element technicsElement) {
        clearTable();
//		System.out.println("-----------clde info------------");
//		System.out.println(technicsElement.asXML());
        Element clde = XmlUtility.getTechnicsCLDEElement(technicsElement);
        if (clde == null) {
            return;
        }

        int row = 0;
        int n = 1;
        //"序号", "编号", "名称", "物资简称", "下料尺寸", "可制件数", "单位", "材料类型", "换算率",
        //"系数", "牌号", "规格", "采用标准", "供应状态", "精度", "质量特征", "品种规格标准", "是否进口", "计量单位", "特殊说明"
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        List<Element> ycl = XmlUtility.getTechnicsSJZYKYCLDE(clde);
        if (ycl != null && !ycl.isEmpty()) {
            for (Element element : ycl) {
                Vector vector = new Vector();
                for (int j = 0; j < jTable1.getColumnCount(); j++) {
                    vector.add("");
                }
                tableModel.addRow(vector);
                tableModel.setValueAt(n, row, 0);
                tableModel.setValueAt(element.attributeValue("sjbm"), row, 1);
                tableModel.setValueAt(element.attributeValue("name"), row, 2);
                tableModel.setValueAt(element.attributeValue("wzjc"), row, 3);
                tableModel.setValueAt(element.attributeValue("xlcc"), row, 4);
                tableModel.setValueAt(element.attributeValue("kzjs"), row, 5);
                tableModel.setValueAt(element.attributeValue("dw"), row, 6);
                tableModel.setValueAt(element.attributeValue("cllx"), row, 7);
                tableModel.setValueAt(element.attributeValue("hsl"), row, 8);
                tableModel.setValueAt(element.attributeValue("xs"), row, 9);
                tableModel.setValueAt(element.attributeValue("ph"), row, 10);
                tableModel.setValueAt(element.attributeValue("gg"), row, 11);
                tableModel.setValueAt(element.attributeValue("cybz"), row, 12);
                tableModel.setValueAt(element.attributeValue("gyzt"), row, 13);
                tableModel.setValueAt(element.attributeValue("jd"), row, 14);
                tableModel.setValueAt(element.attributeValue("zltz"), row, 15);
                tableModel.setValueAt(element.attributeValue("pzggbz"), row, 16);
                tableModel.setValueAt(element.attributeValue("sfjk"), row, 17);
                tableModel.setValueAt(element.attributeValue("jldw"), row, 18);
                tableModel.setValueAt(element.attributeValue("tssm"), row, 19);
                tableModel.setValueAt(element.attributeValue("gys"), row, 20);
                tableModel.setValueAt(element.attributeValue("comment"), row, 21);
                row++;
                n++;
            }
        }

        tableModel = (DefaultTableModel) jTable2.getModel();
        List<Element> zycl = XmlUtility.getTechnicsSJZYKZYCLDE(clde);
        if (zycl != null && !zycl.isEmpty()) {
            row = 0;
            n = 1;
            for (Element element : zycl) {
                Vector vector = new Vector();
                for (int j = 0; j < jTable2.getColumnCount(); j++) {
                    vector.add("");
                }
                //"序号", "编号", "名称", "物资简称", "数量", "单位", "材料类型", "换算率", "系数", "牌号",
                //"规格", "采用标准", "精度", "质量特征", "品种规格标准", "是否进口", "计量单位", "特殊说明"
                tableModel.addRow(vector);
                tableModel.setValueAt(n, row, 0);
                tableModel.setValueAt(element.attributeValue("sjbm"), row, 1);
                tableModel.setValueAt(element.attributeValue("name"), row, 2);
                tableModel.setValueAt(element.attributeValue("wzjc"), row, 3);
                tableModel.setValueAt(element.attributeValue("sl"), row, 4);
                tableModel.setValueAt(element.attributeValue("dw"), row, 5);
                tableModel.setValueAt(element.attributeValue("cllx"), row, 6);
                tableModel.setValueAt(element.attributeValue("hsl"), row, 7);
                tableModel.setValueAt(element.attributeValue("xs"), row, 8);
                tableModel.setValueAt(element.attributeValue("ph"), row, 9);
                tableModel.setValueAt(element.attributeValue("gg"), row, 10);
                tableModel.setValueAt(element.attributeValue("cybz"), row, 11);
                tableModel.setValueAt(element.attributeValue("gyzt"), row, 12);
                tableModel.setValueAt(element.attributeValue("jd"), row, 13);
                tableModel.setValueAt(element.attributeValue("zltz"), row, 14);
                tableModel.setValueAt(element.attributeValue("pzggbz"), row, 15);
                tableModel.setValueAt(element.attributeValue("sfjk"), row, 16);
                tableModel.setValueAt(element.attributeValue("jldw"), row, 17);
                tableModel.setValueAt(element.attributeValue("tssm"), row, 18);
                tableModel.setValueAt(element.attributeValue("gys"), row, 19);
                tableModel.setValueAt(element.attributeValue("comment"), row, 20);
                row++;
                n++;
            }
        }

        tableModel = (DefaultTableModel) jTable3.getModel();
        List<Element> sjycl = XmlUtility.getTechnicsSJZYKSJYCLDE(clde);
        if (sjycl != null && !sjycl.isEmpty()) {
            row = 0;
            n = 1;
            for (Element element : sjycl) {
                Vector vector = new Vector();
                for (int j = 0; j < jTable3.getColumnCount(); j++) {
                    vector.add("");
                }
                //"序号", "编号", "名称", "物资简称", "试件尺寸", "试件可制件数", "试件数量", "单位", "材料类型",
                //"换算率", "系数", "牌号", "规格", "采用标准", "供应状态", "精度", "质量特征", "品种规格标准",
                //"是否进口", "计量单位", "特殊说明"
                tableModel.addRow(vector);
                tableModel.setValueAt(n, row, 0);
                tableModel.setValueAt(element.attributeValue("sjbm"), row, 1);
                tableModel.setValueAt(element.attributeValue("name"), row, 2);
                tableModel.setValueAt(element.attributeValue("wzjc"), row, 3);
                tableModel.setValueAt(element.attributeValue("sjcc"), row, 4);
                tableModel.setValueAt(element.attributeValue("sjkzjs"), row, 5);
                tableModel.setValueAt(element.attributeValue("sl"), row, 6);
                tableModel.setValueAt(element.attributeValue("dw"), row, 7);
                tableModel.setValueAt(element.attributeValue("cllx"), row, 8);
                tableModel.setValueAt(element.attributeValue("hsl"), row, 9);
                tableModel.setValueAt(element.attributeValue("xs"), row, 10);
                tableModel.setValueAt(element.attributeValue("ph"), row, 11);
                tableModel.setValueAt(element.attributeValue("gg"), row, 12);
                tableModel.setValueAt(element.attributeValue("cybz"), row, 13);
                tableModel.setValueAt(element.attributeValue("gyzt"), row, 14);
                tableModel.setValueAt(element.attributeValue("jd"), row, 15);
                tableModel.setValueAt(element.attributeValue("zltz"), row, 16);
                tableModel.setValueAt(element.attributeValue("pzggbz"), row, 17);
                tableModel.setValueAt(element.attributeValue("sfjk"), row, 18);
                tableModel.setValueAt(element.attributeValue("jldw"), row, 19);
                tableModel.setValueAt(element.attributeValue("tssm"), row, 20);
                tableModel.setValueAt(element.attributeValue("gys"), row, 21);
                tableModel.setValueAt(element.attributeValue("comment"), row, 22);
                row++;
                n++;
            }
        }
    }

    public void clearTable() {
        ((DefaultTableModel) jTable1.getModel()).setRowCount(0);
        ((DefaultTableModel) jTable2.getModel()).setRowCount(0);
        ((DefaultTableModel) jTable3.getModel()).setRowCount(0);
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration
}
