[APPURL]
mbom.url=/wtcore/jsp/ext/ideal/samc/openMBomBuilder.jsp
ao.url=/wtcore/jsp/ext/ideal/samc/openAOBuilder.jsp
spsbom.url=/wtcore/jsp/ext/ideal/samc/openSPSBomBuilder.jsp
[MBOM]
pview.download.threadCount=30

ebom.ci.search.types=主部段,部段,ATA章,ATA节,ATA段,AD_CI
ebom.structure.leaf.type=AD_CI
ebom.structure.stop.type=CI

mbom.instanceData.type.DLO=AD_LO
mbom.instanceData.type.CI=AD_CI

#MBOM中搜索组件中可搜索的类型
mbom.openMBom.valid.types=AO,AAO

#“新建节点”功能对应的类型业务逻辑
mbom.newNode.configable.types=AO,AAO,工艺组件,CI,AD_CI,SYS_CI,DS,AD_DS,SYS_DS

#能创建新节点的MBOM树节点类型
mbom.newNode.canCreate.types=AO,AAO,工艺组件

#AO节点下能创建的部件类型, Alex.Huang 2011-4-20根据要求去掉 AAO类型
mbom.newNode.type.AO=工艺组件,

#MBOM中创建组件中可创建的类型
mbom.newPart.type=AO,AAO

#AAO节点下能创建的部件类型
mbom.newNode.type.AAO=工艺组件

#查找并添加可见于下面的类型 Allen Yang 2012/2/8：
mbom.searchAndAddNode.configable.types=AO,AAO,工艺组件,制造部段,散交零件,散交组件,特制件

#查找并添加的下拉列表类型 Allen Yang 2012/2/8：
mbom.searchAndAddNode.type.AO=工艺组件,制造部段,散交零件,散交组件,特制件
mbom.searchAndAddNode.type.AAO=工艺组件,制造部段,散交零件,散交组件,特制件
mbom.searchAndAddNode.type.工艺组件=工艺组件,制造部段,散交零件,散交组件,特制件
mbom.searchAndAddNode.type.制造部段=工艺组件,制造部段,散交零件,散交组件
mbom.searchAndAddNode.type.散交零件=工艺组件,制造部段,散交零件,散交组件
mbom.searchAndAddNode.type.散交组件=工艺组件,制造部段,散交零件,散交组件

#工艺组件节点下能创建的部件类型
mbom.newNode.type.工艺组件=工艺组件

#不能添加到MBOM树上的节点类型
#删掉了DDM,DS Allen Yang 2012/2/9
#mbom.newNode.unPaste.type=AD_CI,SYS_CI,CI,AD_LO,LO,SYS_LO,AD_DS,DS,SYS_DS
mbom.newNode.unPaste.type=AD_CI,SYS_CI,CI,AD_LO,LO,SYS_LO,SYS_DS

long.time.action.enablePerformanceTraceUI=false

#记录唯一实例标识时，CmInstanceData的类型定义
mbom.instanceData.type.CI=AD_CI
mbom.instanceData.type.LO=AD_LO

#EBom视图中可以查看路径的对象类型
ebom.view.node.path.type=AD_CI

#保存时的节点类型
mbom.saveAttribut.node.type.AO=AO

#Alex.Huang 2011-6-22当部件为这个状态时，结构从系统中获取，否则从xml中获取
mbom.part.state.displayName=已发布,设计中

#Alex.Huang 2011-6-22当工艺组件的状态为这些值时，结构可编辑
mbom.gongyizujian.canEdit.state.displayName=正在工作,修改中

#Allen Yang 2012/2/22 当节点的状态为这些值时，可以被删除
mbom.gongyizujian.canDelete.state.displayName=正在工作,修改中,已发布

#Alex.Huang 2011-7-01当AO组件的状态为这些值时，结构可编辑
mbom.ao.canEdit.state.displayName=正在工作,修改中

#Allen Yang 2012/2/15 MBOM菜单栏里用于检测的类型
mbom.type.工艺组件=工艺组件
mbom.type.制造部段=制造部段
mbom.type.散交零件=散交零件
mbom.type.散交组件=散交组件

[AO]
empty.row.for.zero=false
ao.mbom_ebom.newNode.unPaste.type=AO,AAO
aoTechnicsmark.ebom_mbom.newNode.unPaste.type=AD_CI,SYS_CI,CI,AD_LO,LO,SYS_LO,AD_DS,DS,SYS_DS

[Effectivity]
DesignView.C919.EffContext=C1
DesignView.C919样机和试验件模型管理与协调空间.EffContext=C0
Manufacturing.C919-SAMC.EffContext=C919-SAMC

effectivity.node.type=AD_LO

[CAD]
LocatorParentNodeType=com.ptc.Variant

CadAdapter.class.CATIAV5=ext.ideal.samc.jws.cad.CatiaV5CadAdapterImpl
getContent.useCADNameAsURL.CATIAV5=false
getContent.add2workspace.CATIAV5=true
getContent.checkFamilyInstances.CATIAV5=false
CATIAV5.useDlName=false

cadScalingFactor.CATIAV5=1000
RootStrucLevel=Product

getContent.unmatchingAuthApps.useSecondary.CATIAV5=false
getContent.unmatchingAuthApps.secondary.useSuffixFor.CATIAV5=CATPART,CATPRODUCT,MODEL
getContent.unmatchingAuthApps.usePublishLinkedContent.CATIAV5=true


[SPSBOM]
#SPS工作包，制造部段，散交组件，散交零件 软类型
spsbom.spspackage.softType=wt.part.WTPart|com.ideal.SPSPackage
spsbom.DepParagraphMFG.softType=wt.part.WTPart|com.ideal.DepParagraphMFG
spsbom.scatterChiasmaPart.softType=wt.part.WTPart|com.ideal.ScatterChiasmaPart
spsbom.scatterChiasma.softType=wt.part.WTPart|com.ideal.ScatterChiasma

#M视图中可接收拖动节点的节点类型
spsbom.ebom2mbom.darg.objectType=wt.part.WTPart|com.ideal.DepParagraphMFG,wt.part.WTPart|com.ideal.ScatterChiasma,wt.part.WTPart|com.ideal.ScatterChiasmaPart

#不能添加到SPSBOM树上的节点类型
spsbom.ebom2mbom.unPaste.type=AD_CI,SYS_CI,CI,AD_LO,LO,SYS_LO

spsbom.newNode.configable.types=SPS工作分包,工艺组件,制造部段,散交零件,散交组件
spsbom.newNode.types=工艺组件

spsbom.newNode.type.工艺组件=工艺组件
spsbom.newNode.type.制造部段=制造部段
spsbom.newNode.type.散交零件=散交零件
spsbom.newNode.type.散交组件=散交组件

spsbom.searchAndAddNode.types=工艺组件,制造部段,散交零件,散交组件
spsbom.searchAndAddNode.type.工艺组件=工艺组件
spsbom.searchAndAddNode.type.制造部段=制造部段
spsbom.searchAndAddNode.type.散交零件=散交零件
spsbom.searchAndAddNode.type.散交组件=散交组件

#Alex.Huang 2011-7-20当工艺组件的状态为这些值时，结构可编辑
spsbom.gongyizujian.canEdit.state.displayName=正在工作,修改中

#Alex.Huang 2011-7-20当SPS工作包的状态为这些值时，结构可编辑
spsbom.sps.canEdit.state.displayName=正在工作,修改中

[editAttribute]
#AO零件代码
attr.ao.code=AC,AO,AAO,CCAC,CHAIG,CASIC,D,DS,E,E1,E2,FAC,FB,FBL,FC,FH,FMC,FNC,FP,FPT,FST,FW,HAIG,HDIG,JGE,JRC,JLT,JPF,JPH,JHSA,JHSE,JHL,JPFC,JHSH,JSG,JLL,JKA,JGRL,JEA,JEVAC,JFACC,JZAC,JB/E,JSAS,JRMTAERO,JSGS,JPC,MU,PCA,PCB,PCF,RWK,RISAC,SACC,XAIC,XIZIUHC
#AO制造路线
attr.ao.mfl=1K,2K,8K,9K,12K,15K,21K,8K-15K,8K-16K,12K-15K,12K-16K,外购,外协,CCAC,CASIC,CHAIG,HAIG,HDIG,RISAC,SACC,XAIC,XIZIUHC,物流中心
#AO使用单位
attr.ao.udp=1K,2K,8K,12K,15K,21K

#SPS零件代码
attr.sps.code= ,AC,AO,AAO,CCAC,CHAIG,CASIC,D,DS,E,E1,E2,FAC,FB,FBL,FC,FH,FMC,FNC,FP,FPT,FST,FW,HAIG,HDIG,JGE,JRC,JLT,JPF,JPH,JHSA,JHSE,JHL,JPFC,JHSH,JSG,JLL,JKA,JGRL,JEA,JEVAC,JFACC,JZAC,JB/E,JSAS,JRMTAERO,JSGS,JPC,MU,PCA,PCB,PCF,RWK,RISAC,SACC,XAIC,XIZIUHC
#SPS制造路线
attr.sps.mfl=CCAC,CASIC,CHAIG,HAIG,HDIG,RISAC,SACC,XAIC,XIZIUHC,SAMC
#SPS使用单位
attr.sps.udp=CCAC,CASIC,CHAIG,HAIG,HDIG,RISAC,SACC,XAIC,XIZIUHC,SAMC

#属性是否为空校验
mbom.attr.check.column=零件代码,制造路线
mbom.attr.check.column.gui=零件代码,制造路线

spsbom.attr.check.column=制造路线,使用单位
spsbom.attr.check.column.gui=制造路线,使用单位

#DM模块（零件类型为DM\AD_DS）在MBOM上出现,如果零件代码为一下供应商代码（说明是由供应商交付的零组件或参装件），则放弃检查该模块下所有零件的属性（零件代码、制造路线、使用单位、物料编码） --Allen Yang 2012/2/10
mbom.attr.check.dm.SupplierCode=CCAC,CASIC,CHAIG,HAIG,HDIG,RISAC,SACC,XAIC,XIZIUHC,E1,E2,E


[viewBom]
C919.Manufacturing=C919-SAMC
C919.Supplying=SPSBOM

[MaterialIntegration]
material.integration.address=10.8.8.26
material.integration.targetEendPoint=http://10.8.8.26/logistic/services/MatCodeImp