-- Create table
create table BD_INVBASDOC
(
  asset             CHAR(1),
  assistunit        CHAR(1) default 'N' not null,
  autobalancemeas   CHAR(1) default 'Y',
  createtime        CHAR(19),
  creator           CHAR(20),
  def1              VARCHAR2(100),
  def10             VARCHAR2(100),
  def11             VARCHAR2(100),
  def12             VARCHAR2(100),
  def13             VARCHAR2(100),
  def14             VARCHAR2(100),
  def15             VARCHAR2(100),
  def16             VARCHAR2(100),
  def17             VARCHAR2(100),
  def18             VARCHAR2(100),
  def19             VARCHAR2(100),
  def2              VARCHAR2(100),
  def20             VARCHAR2(100),
  def3              VARCHAR2(100),
  def4              VARCHAR2(100),
  def5              VARCHAR2(100),
  def6              VARCHAR2(100),
  def7              VARCHAR2(100),
  def8              VARCHAR2(100),
  def9              VARCHAR2(100),
  discountflag      CHAR(1) default 'N',
  dr                NUMBER(10) default 0,
  forinvname        VARCHAR2(200),
  free1             CHAR(20),
  free2             CHAR(20),
  free3             CHAR(20),
  free4             CHAR(20),
  free5             CHAR(20),
  graphid           VARCHAR2(50),
  height            VARCHAR2(20),
  invbarcode        VARCHAR2(30),
  invcode           VARCHAR2(200) not null,
  invmnecode        VARCHAR2(50),
  invname           VARCHAR2(200) not null,
  invpinpai         VARCHAR2(100),
  invshortname      VARCHAR2(200),
  invspec           VARCHAR2(200),
  invtype           VARCHAR2(200),
  ismngstockbygrswt CHAR(1) default '0',
  isretail          CHAR(1),
  isstorebyconvert  CHAR(1),
  laborflag         CHAR(1) default 'N',
  length            VARCHAR2(20),
  memo              VARCHAR2(100),
  modifier          CHAR(20),
  modifytime        CHAR(19),
  pk_assetcategory  CHAR(20),
  pk_corp           CHAR(4) not null,
  pk_invbasdoc      CHAR(20) not null,
  pk_invcl          CHAR(20) not null,
  pk_measdoc        CHAR(20) not null,
  pk_measdoc1       CHAR(20),
  pk_measdoc2       CHAR(20),
  pk_measdoc3       CHAR(20),
  pk_measdoc5       CHAR(20),
  pk_measdoc6       CHAR(20),
  pk_prodline       CHAR(20),
  pk_taxitems       CHAR(20),
  sealflag          VARCHAR2(10),
  setpartsflag      CHAR(1) default 'N',
  shipunitnum       NUMBER(20,8),
  storeunitnum      NUMBER(20,8),
  ts                CHAR(19) default to_char(sysdate,'yyyy-mm-dd hh24:mi:ss'),
  unitvolume        NUMBER(20,8),
  unitweight        NUMBER(20,8),
  weitunitnum       NUMBER(20,8),
  width             VARCHAR2(20)
);


-- Create table
create table BD_CUBASDOC
(
  bp1               VARCHAR2(30),
  bp2               VARCHAR2(30),
  bp3               VARCHAR2(30),
  conaddr           VARCHAR2(60),
  correspondunit    CHAR(20),
  createtime        CHAR(19),
  creator           CHAR(20),
  creditmny         NUMBER(20,8),
  custcode          VARCHAR2(40) not null,
  custname          VARCHAR2(200) not null,
  custprop          NUMBER(38),
  custshortname     VARCHAR2(200) not null,
  def1              VARCHAR2(100),
  def10             VARCHAR2(100),
  def11             VARCHAR2(100),
  def12             VARCHAR2(100),
  def13             VARCHAR2(100),
  def14             VARCHAR2(100),
  def15             VARCHAR2(100),
  def16             VARCHAR2(100),
  def17             VARCHAR2(100),
  def18             VARCHAR2(100),
  def19             VARCHAR2(100),
  def2              VARCHAR2(100),
  def20             VARCHAR2(100),
  def3              VARCHAR2(100),
  def4              VARCHAR2(100),
  def5              VARCHAR2(100),
  def6              VARCHAR2(100),
  def7              VARCHAR2(100),
  def8              VARCHAR2(100),
  def9              VARCHAR2(100),
  dr                NUMBER(10) default 0,
  drpnodeflag       CHAR(1),
  ecotypesincevfive CHAR(20),
  email             VARCHAR2(50),
  engname           VARCHAR2(60),
  fax1              VARCHAR2(30),
  fax2              VARCHAR2(30),
  freecustflag      CHAR(1),
  isconnflag        CHAR(1),
  legalbody         VARCHAR2(16),
  linkman1          VARCHAR2(25),
  linkman2          VARCHAR2(25),
  linkman3          VARCHAR2(25),
  memo              VARCHAR2(100),
  mnecode           VARCHAR2(50),
  mobilephone1      VARCHAR2(30),
  mobilephone2      VARCHAR2(30),
  mobilephone3      VARCHAR2(30),
  modifier          CHAR(20),
  modifytime        CHAR(19),
  phone1            VARCHAR2(30),
  phone2            VARCHAR2(30),
  phone3            VARCHAR2(30),
  pk_areacl         CHAR(20) not null,
  pk_corp           CHAR(4) not null,
  pk_corp1          CHAR(4),
  pk_cubasdoc       CHAR(20) not null,
  pk_cubasdoc1      CHAR(20),
  pk_pricegroup     CHAR(20),
  registerfund      NUMBER(20,8),
  saleaddr          VARCHAR2(60),
  sealflag          CHAR(10),
  taxpayerid        VARCHAR2(20),
  trade             CHAR(20),
  ts                CHAR(19) default to_char(sysdate,'yyyy-mm-dd hh24:mi:ss'),
  url               VARCHAR2(60),
  zipcode           CHAR(6)
);

create table BD_INVCL
(
  averagecost     NUMBER(20,8),
  averagemmahead  NUMBER(38),
  averagepurahead NUMBER(38),
  avgprice        NUMBER(20,8),
  dr              NUMBER(10) default 0,
  endflag         CHAR(1),
  forinvname      VARCHAR2(240),
  invclasscode    VARCHAR2(50) not null,
  invclasslev     NUMBER(38) not null,
  invclassname    VARCHAR2(240) not null,
  pk_corp         CHAR(4) default '0001',
  pk_invcl        CHAR(20) not null,
  sealdate        CHAR(10),
  ts              CHAR(19) default to_char(sysdate,'yyyy-mm-dd hh24:mi:ss')
);

create table BD_MEASDOC
(
  basecodeflag CHAR(1) not null,
  dr           NUMBER(10) default 0,
  measname     VARCHAR2(200) not null,
  oppdimen     VARCHAR2(20) not null,
  pk_measdoc   CHAR(20) not null,
  scalefactor  NUMBER(20,8),
  shortname    VARCHAR2(40) not null,
  ts           CHAR(19) default to_char(sysdate,'yyyy-mm-dd hh24:mi:ss')
);


