
CREATE TABLE "PDM10"."GLERPPEITAOPARTBEAN"
(	"CMKEYID" VARCHAR2(64 BYTE) NOT NULL ENABLE,
     "DOCOID" VARCHAR2(36 BYTE) NOT NULL ENABLE,
     "CHILDNUMBER" VARCHAR2(600 BYTE),
     "CHILDNAME" VARCHAR2(600 BYTE),
     "CHILDVERSION" VARCHAR2(200 BYTE),
     "PARTTYPE" VARCHAR2(200 BYTE),
     "CHILDPHASE" VARCHAR2(200 BYTE),
     "AMOUNT" VARCHAR2(20 BYTE),
     "UNIT" VARCHAR2(100 BYTE),
     "BATCH" VARCHAR2(100 BYTE),
     "ZZCJ" VARCHAR2(100 BYTE),
     "SETMARK" VARCHAR2(20 BYTE),
     "DEPT" VARCHAR2(30 BYTE),
     "TECHNUMBER" VARCHAR2(200 BYTE),
     "TECHNAME" VARCHAR2(200 BYTE),
     "PPLANNUMBER" VARCHAR2(200 BYTE),
     "VERSION" VARCHAR2(20 BYTE),
     "PPLANTYPE" VARCHAR2(20 BYTE),
     "ZFFLAG" VARCHAR2(20 BYTE),
     "SYNCHTIME" VARCHAR2(100 BYTE),
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


CREATE INDEX "PDM10"."GLERPPEITAOPARTBEAN_DOCOID" ON "PDM10"."GLERPPEITAOPARTBEAN" ("DOCOID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


