/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.glaway.mpm.qmIntf.material;

import java.util.HashMap;
import java.util.Map;

import javax.swing.GroupLayout;

import com.glaway.mpm.model.Material;

/**
 *
 * @author ylshao
 */
public class MtInfoPanel extends javax.swing.JPanel {

	/**
	 * Creates new form EpInfoPanel
	 */
	public MtInfoPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	private void initComponents() {

		numberLabel = new javax.swing.JLabel();
		materialNumber = new javax.swing.JLabel();
		nameLabel = new javax.swing.JLabel();
		materialName = new javax.swing.JLabel();
		brandLabel = new javax.swing.JLabel();
		materialBrand = new javax.swing.JLabel();
		categoryLabel = new javax.swing.JLabel();
		materialCategory = new javax.swing.JLabel();
		crisionLabel = new javax.swing.JLabel();
		materialCrision = new javax.swing.JLabel();
		unitLabel = new javax.swing.JLabel();
		materialUnit = new javax.swing.JLabel();
		imageLabel = new javax.swing.JLabel();

		csizeLabel = new javax.swing.JLabel();
		csizeValue = new javax.swing.JLabel();
		mindexLabel = new javax.swing.JLabel();
		mindexValue = new javax.swing.JLabel();
		jstjLabel = new javax.swing.JLabel();
		jstjValue = new javax.swing.JLabel();
		fjtjLabel = new javax.swing.JLabel();
		fjtjValue = new javax.swing.JLabel();

		numberLabel.setText("编码");
		materialNumber.setText(" ");

		nameLabel.setText("名称");
		materialName.setText(" ");

		brandLabel.setText("材料牌号");
		materialBrand.setText(" ");

		categoryLabel.setText("材料规格");
		materialCategory.setText(" ");

		crisionLabel.setText("材料标准");
		materialCrision.setText(" ");

		unitLabel.setText("计量单位");
		materialUnit.setText(" ");

		csizeLabel.setText("规格");
		csizeValue.setText("");

		mindexLabel.setText("型号");
		mindexValue.setText("");

		jstjLabel.setText("技术条件");
		jstjValue.setText("");

		fjtjLabel.setText("附加条件");
		fjtjValue.setText("");

		GroupLayout layout = new GroupLayout(this);
		this.setLayout(layout);

		GroupLayout.SequentialGroup hGroup = layout.createSequentialGroup();
		hGroup.addGroup(
				layout.createParallelGroup().addComponent(
						numberLabel,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						nameLabel,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						unitLabel,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						csizeLabel,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						mindexLabel,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jstjLabel,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						fjtjLabel,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				);
		hGroup.addGroup(
				layout.createParallelGroup().addComponent(
						materialNumber,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						materialName,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						materialUnit,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						csizeValue,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						mindexValue,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						jstjValue,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(
						fjtjValue,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				);

		GroupLayout.SequentialGroup vGroup = layout.createSequentialGroup();

        vGroup.addGroup(layout.createParallelGroup().addComponent(numberLabel).addComponent(materialNumber));
        vGroup.addGroup(layout.createParallelGroup().addComponent(nameLabel).addComponent(materialName));
        vGroup.addGroup(layout.createParallelGroup().addComponent(unitLabel).addComponent(materialUnit));
        vGroup.addGroup(layout.createParallelGroup().addComponent(csizeLabel).addComponent(csizeValue));
        vGroup.addGroup(layout.createParallelGroup().addComponent(mindexLabel).addComponent(mindexValue));
        vGroup.addGroup(layout.createParallelGroup().addComponent(jstjLabel).addComponent(jstjValue));
        vGroup.addGroup(layout.createParallelGroup().addComponent(fjtjLabel).addComponent(fjtjValue));

		layout.setHorizontalGroup(hGroup);
		layout.setVerticalGroup(vGroup);
	}

	private javax.swing.JLabel brandLabel;
	private javax.swing.JLabel categoryLabel;
	private javax.swing.JLabel crisionLabel;
	private javax.swing.JLabel imageLabel;
	private javax.swing.JLabel materialBrand;
	private javax.swing.JLabel materialCategory;
	private javax.swing.JLabel materialCrision;
	private javax.swing.JLabel materialName;
	private javax.swing.JLabel materialNumber;
	private javax.swing.JLabel materialUnit;
	private javax.swing.JLabel nameLabel;
	private javax.swing.JLabel numberLabel;
	private javax.swing.JLabel unitLabel;

	private javax.swing.JLabel csizeLabel;
	private javax.swing.JLabel csizeValue;
	private javax.swing.JLabel mindexLabel;
	private javax.swing.JLabel mindexValue;
	private javax.swing.JLabel jstjLabel;
	private javax.swing.JLabel jstjValue;
	private javax.swing.JLabel fjtjLabel;
	private javax.swing.JLabel fjtjValue;

	public javax.swing.JLabel getBrandLabel() {
		return brandLabel;
	}

	public void setBrandLabel(javax.swing.JLabel brandLabel) {
		this.brandLabel = brandLabel;
	}

	public javax.swing.JLabel getCategoryLabel() {
		return categoryLabel;
	}

	public void setCategoryLabel(javax.swing.JLabel categoryLabel) {
		this.categoryLabel = categoryLabel;
	}

	public javax.swing.JLabel getCrisionLabel() {
		return crisionLabel;
	}

	public void setCrisionLabel(javax.swing.JLabel crisionLabel) {
		this.crisionLabel = crisionLabel;
	}

	public javax.swing.JLabel getImageLabel() {
		return imageLabel;
	}

	public void setImageLabel(javax.swing.JLabel imageLabel) {
		this.imageLabel = imageLabel;
	}

	public javax.swing.JLabel getMaterialBrand() {
		return materialBrand;
	}

	public void setMaterialBrand(javax.swing.JLabel materialBrand) {
		this.materialBrand = materialBrand;
	}

	public javax.swing.JLabel getMaterialCategory() {
		return materialCategory;
	}

	public void setMaterialCategory(javax.swing.JLabel materialCategory) {
		this.materialCategory = materialCategory;
	}

	public javax.swing.JLabel getMaterialCrision() {
		return materialCrision;
	}

	public void setMaterialCrision(javax.swing.JLabel materialCrision) {
		this.materialCrision = materialCrision;
	}

	public javax.swing.JLabel getMaterialName() {
		return materialName;
	}

	public void setMaterialName(javax.swing.JLabel materialName) {
		this.materialName = materialName;
	}

	public javax.swing.JLabel getMaterialNumber() {
		return materialNumber;
	}

	public void setMaterialNumber(javax.swing.JLabel materialNumber) {
		this.materialNumber = materialNumber;
	}

	public javax.swing.JLabel getMaterialUnit() {
		return materialUnit;
	}

	public void setMaterialUnit(javax.swing.JLabel materialUnit) {
		this.materialUnit = materialUnit;
	}

	public javax.swing.JLabel getNameLabel() {
		return nameLabel;
	}

	public void setNameLabel(javax.swing.JLabel nameLabel) {
		this.nameLabel = nameLabel;
	}

	public javax.swing.JLabel getNumberLabel() {
		return numberLabel;
	}

	public void setNumberLabel(javax.swing.JLabel numberLabel) {
		this.numberLabel = numberLabel;
	}

	public javax.swing.JLabel getUnitLabel() {
		return unitLabel;
	}

	public void setUnitLabel(javax.swing.JLabel unitLabel) {
		this.unitLabel = unitLabel;
	}

	public javax.swing.JLabel getCsizeLabel() {
		return csizeLabel;
	}

	public void setCsizeLabel(javax.swing.JLabel csizeLabel) {
		this.csizeLabel = csizeLabel;
	}

	public javax.swing.JLabel getCsizeValue() {
		return csizeValue;
	}

	public void setCsizeValue(javax.swing.JLabel csizeValue) {
		this.csizeValue = csizeValue;
	}

	public javax.swing.JLabel getMindexLabel() {
		return mindexLabel;
	}

	public void setMindexLabel(javax.swing.JLabel mindexLabel) {
		this.mindexLabel = mindexLabel;
	}

	public javax.swing.JLabel getMindexValue() {
		return mindexValue;
	}

	public void setMindexValue(javax.swing.JLabel mindexValue) {
		this.mindexValue = mindexValue;
	}

	public javax.swing.JLabel getJstjLabel() {
		return jstjLabel;
	}

	public void setJstjLabel(javax.swing.JLabel jstjLabel) {
		this.jstjLabel = jstjLabel;
	}

	public javax.swing.JLabel getJstjValue() {
		return jstjValue;
	}

	public void setJstjValue(javax.swing.JLabel jstjValue) {
		this.jstjValue = jstjValue;
	}

	public javax.swing.JLabel getFjtjLabel() {
		return fjtjLabel;
	}

	public void setFjtjLabel(javax.swing.JLabel fjtjLabel) {
		this.fjtjLabel = fjtjLabel;
	}

	public javax.swing.JLabel getFjtjValue() {
		return fjtjValue;
	}

	public void setFjtjValue(javax.swing.JLabel fjtjValue) {
		this.fjtjValue = fjtjValue;
	}

	private Map<String, byte[]> imageCache = new HashMap<String, byte[]>();

	public void initDatas(Material material) {
//		materialNumber.setText(material.getMaterialNumber());
//		materialName.setText(material.getMaterialName());
//		materialBrand.setText(material.getMaterialBrand());
//		materialCategory.setText(material.getMaterialCategory());
//		materialCrision.setText(material.getMaterialCrision());
//		materialUnit.setText(material.getMaterialUnit());
//		String oid = material.getOid();
//		byte[] bytes = imageCache.get(oid);
//		if (bytes == null) {
//			bytes = ResourceIntf.getResourceImage(oid);
//			imageCache.put(oid, bytes);
//		}
//		SwingUtil.setIcon(imageLabel, bytes);
		//812
		materialNumber.setText(material.getMaterialNumber());
		materialName.setText(material.getMaterialName());
		materialBrand.setText(material.getClph());
		materialCategory.setText(material.getClgg());
		materialCrision.setText(material.getClbz());
		materialUnit.setText(material.getJldw());
		csizeValue.setText(material.getCsize());
		mindexValue.setText(material.getMindex());
		jstjValue.setText(material.getJstj());
		fjtjValue.setText(material.getFjtj());
	}
}
