package com.glaway.mpm.pbombuilder.tree.dialog;

import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.SwingUtilities;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

import com.glaway.mpm.pbombuilder.util.CmCommonStringUtil;
import com.glaway.mpm.pbombuilder.util.CmUtil;

/**
*
* @author LongXiuChuan 2014-2-23
*/
public class SearchAddPartJDoalog {

	private JButton jButton1;
	   private JButton jButton2;
	   private JButton jButton3;
	   private JLabel jLabel1;
	   private JLabel jLabel2;
	   private JPanel jPanel1;
	   private JPanel jPanel2;
	   private JPanel jPanel3;
	   private JScrollPane jScrollPane1;
	   private JTable jTable1;
	   private JTextField jTextField1;
	   private JTextField jTextField2;

	   private JDialog dialog;

   /**
    * Creates new form SearchAddPartJDoalog
    */
   public SearchAddPartJDoalog(Frame parent, boolean modal) {
       super();
       showDialog();
   }

	public void showDialog() {
		// 新增对话框
		newJDialog();
		initComponents();
	}

	/**
	 * 新增对话框jdialog
	 */
	public void newJDialog() {
		dialog = new JDialog();
		dialog.setTitle("查询零部件");
		dialog.setSize(300, 150);
		dialog.setIconImage(CmUtil.getImageFromServer("edit.gif"));
		dialog.setResizable(false);
		dialog.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
		CmCommonStringUtil.setMiddleOnScreenWithDialog(dialog);
	}

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   private void initComponents() {

       jPanel1 = new JPanel();
       jLabel1 = new JLabel();
       jTextField1 = new JTextField();
       jLabel2 = new JLabel();
       jTextField2 = new JTextField();
       jButton1 = new JButton();
       jPanel2 = new JPanel();
       jScrollPane1 = new JScrollPane();
       jTable1 = new JTable();
       jPanel3 = new JPanel();
       jButton2 = new JButton();
       jButton3 = new JButton();

       jPanel1.setBorder(BorderFactory.createTitledBorder("查询条件"));

       jLabel1.setText("编号：");

       jTextField1.setText("jTextField1");

       jLabel2.setText("名称：");

       jTextField2.setText("jTextField2");

       jButton1.setText("查  询");
       jButton1.addActionListener(new ActionListener() {
           public void actionPerformed(ActionEvent evt) {
               jButton1ActionPerformed(evt);
           }
       });

       GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
       jPanel1.setLayout(jPanel1Layout);
       jPanel1Layout.setHorizontalGroup(
           jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addGap(19, 19, 19)
               .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                   .addComponent(jLabel2)
                   .addComponent(jLabel1))
               .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                   .addComponent(jTextField1, GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                   .addComponent(jTextField2))
               .addGap(42, 42, 42)
               .addComponent(jButton1)
               .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );
       jPanel1Layout.setVerticalGroup(
           jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel1)
                   .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
               .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
               .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel2)
                   .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                   .addComponent(jButton1))
               .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );

       jPanel2.setBorder(BorderFactory.createTitledBorder("查询结果"));

       jTable1.setModel(new DefaultTableModel(
           new Object [][] {
               {null, null, null},
               {null, null, null},
               {null, null, null},
               {null, null, null},
               {null, null, null},
               {null, null, null},
               {null, null, null},
               {null, null, null},
               {null, null, null},
               {null, null, null},
               {null, null, null}
           },
           new String [] {
               "编号", "名称", "版本"
           }
       ) {
           Class[] types = new Class [] {
               String.class, String.class, String.class
           };

           public Class getColumnClass(int columnIndex) {
               return types [columnIndex];
           }
       });
       jTable1.getTableHeader().setReorderingAllowed(false);
       jScrollPane1.setViewportView(jTable1);

       GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
       jPanel2.setLayout(jPanel2Layout);
       jPanel2Layout.setHorizontalGroup(
           jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
           .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
       );
       jPanel2Layout.setVerticalGroup(
           jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
           .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
       );

       jButton2.setText("添  加");
       jButton2.addActionListener(new ActionListener() {
           public void actionPerformed(ActionEvent evt) {
               jButton2ActionPerformed(evt);
           }
       });

       jButton3.setText("取  消");
       jButton3.addActionListener(new ActionListener() {
           public void actionPerformed(ActionEvent evt) {
               jButton3ActionPerformed(evt);
           }
       });

       GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
       jPanel3.setLayout(jPanel3Layout);
       jPanel3Layout.setHorizontalGroup(
           jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
           .addGroup(GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
               .addContainerGap(55, Short.MAX_VALUE)
               .addComponent(jButton2)
               .addGap(44, 44, 44)
               .addComponent(jButton3)
               .addContainerGap())
       );
       jPanel3Layout.setVerticalGroup(
           jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
           .addGroup(jPanel3Layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                   .addComponent(jButton2)
                   .addComponent(jButton3))
               .addContainerGap(16, Short.MAX_VALUE))
       );

       GroupLayout layout = new GroupLayout(dialog.getContentPane());
       dialog.getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(GroupLayout.Alignment.LEADING)
           .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
               .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                   .addGroup(layout.createSequentialGroup()
                       .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                       .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                   .addGroup(layout.createSequentialGroup()
                       .addGap(21, 21, 21)
                       .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                           .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
               .addGap(27, 27, 27))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
               .addGap(42, 42, 42))
       );

       SwingUtilities.invokeLater(new Runnable() {
			@Override
			public void run() {
				dialog.setModal(true);
				dialog.setVisible(true);
			}
		});
   }

   private void jButton1ActionPerformed(ActionEvent evt) {
       // TODO add your handling code here:
   }

   private void jButton2ActionPerformed(ActionEvent evt) {
       // TODO add your handling code here:
   }

   private void jButton3ActionPerformed(ActionEvent evt) {
	   dialog.setVisible(false);
   }

}
