		# log for glaway  Project
		log4j.logger.glawayLogger=DEBUG,glawayFile
		# Define glawayLogger appender, which sends log events to a file
		log4j.appender.glawayFile=wt.log4j.jmx.DailyRollingFileAppender
		log4j.appender.glawayFile.File=${wt.logs.dir}/${wt.manager.serviceName}-${wt.jvm.startTime.formatted.short}-${wt.jvm.id}-glaway.log
		log4j.appender.glawayFile.DatePattern='.'yyyy-MM-dd
		log4j.appender.glawayFile.layout=org.apache.log4j.PatternLayout
		log4j.appender.glawayFile.layout.ConversionPattern=%d{ISO8601} %-5p [%t] %c %X{user} - %m%nu636E/0801\u751F\u4EA7BOM\u8868