CREATE INDEX PreMemberLink$COMPOSITE0 ON PreMemberLink(idA3A5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX PreMemberLink$COMPOSITE1 ON PreMemberLink(idA3B5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
