#Data Utility
wt.services/svc/default/com.ptc.core.components.descriptor.DataUtility/MPMResourceInfoDatautility/java.lang.Object/0=com.glaway.mpm.mpmresource.datautilities.MPMResourceInfoDatautility/singleton

#MPMPlan Validation Filter
wt.services/svc/default/com.ptc.core.ui.validation.SimpleValidationFilter/ProcessPlanActionsValidator/null/0=com.glaway.mpm.processplan.ProcessPlanActionsValidator/duplicate

wt.services/svc/default/com.ptc.core.ui.validation.SimpleValidationFilter/WorkflowPboAttachmentsValidator/null/0=ext.casc.validator.WorkflowPboAttachmentsValidator/duplicate

#datautility
wt.services/svc/default/com.ptc.core.components.descriptor.DataUtility/PbomBuilderFlowDataUtility/java.lang.Object/0=com.glaway.mpm.mpmresource.datautilities.PbomBuilderFlowDataUtility/singleton
wt.services/svc/default/com.ptc.core.components.descriptor.DataUtility/CreateMPMResourceDatautility/java.lang.Object/0=com.glaway.mpm.mpmresource.datautilities.CreateMPMResourceDatautility/singleton
wt.services/svc/default/com.ptc.core.components.descriptor.DataUtility/CreateSOPZYDatautility/java.lang.Object/0=com.glaway.mpm.mvc.builders.sop.CreateSOPZYDatautility/singleton
wt.services/svc/default/com.ptc.core.components.descriptor.DataUtility/PbomTechnicsReportDataUtility/java.lang.Object/0=com.glaway.mpm.pbom.datautilities.PbomTechnicsReportDataUtility/singleton

#validator
wt.services/svc/default/com.ptc.core.ui.validation.SimpleValidationFilter/PBOMStartFlowZJPartValidator/null/0=com.glaway.mpm.pbom.validator.PBOMStartFlowZJPartValidator/duplicate

wt.services/svc/default/com.ptc.core.ui.validation.SimpleValidationFilter/ProcessPlanActionsValidator/null/0=com.glaway.mpm.processplan.ProcessPlanActionsValidator/duplicate
wt.services/svc/default/com.ptc.core.ui.validation.SimpleValidationFilter/CreateMPMResourceValidator/null/0=com.glaway.mpm.mpmresource.validator.CreateMPMResourceValidator/duplicate
wt.services/svc/default/com.ptc.core.ui.validation.SimpleValidationFilter/DownloadTechnicsReportValidtor/null/0=ext.casc.validator.DownloadTechnicsReportValidtor/duplicate
wt.services/svc/default/com.ptc.core.ui.validation.SimpleValidationFilter/TechnicPreviewValidationFilter/null/0=com.glaway.mpm.pbom.validator.TechnicPreviewValidationFilter/duplicate
