DJ=com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Knife
LJ=com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Measure
SB=com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Equipment
GZhuang=com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Frock
GJ=com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Tool
GXMC=com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.ProceduceName
GYCYY=com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.CommonString
ZZDW=com.ptc.windchill.mpml.resource.MPMPlant
GW=com.ptc.windchill.mpml.resource.MPMWorkCenter
GZhong=com.ptc.windchill.mpml.resource.MPMSkill
GYFL=com.ptc.windchill.mpml.resource.MPMProcessMaterial
