
  drop table GL_ZHUFULINKMASTER;

    CREATE TABLE "PDM10"."GL_ZHUFULINKMASTER" 
   (	"GWKEY" VARCHAR2(100 BYTE) DEFAULT sys_guid() NOT NULL ENABLE, 
	"FZTECHNICSNUMBER" VARCHAR2(100 BYTE), 
	"FZTECHNICSVERSION" VARCHAR2(100 BYTE), 
	"ZZTECHNICSNUMBER" VARCHAR2(100 BYTE), 
	"ZZTECHNICSVERSION" VARCHAR2(20 BYTE), 
	"ZZPROCEDUREBSOID" VARCHAR2(100 BYTE), 
	"PICIHAO" VARCHAR2(100 BYTE), 
	"CREATOR" VARCHAR2(50 BYTE), 
	"CREATETIME" VARCHAR2(100 BYTE), 
	 CONSTRAINT "GL_ZHUFULINKMASTER_PK" PRIMARY KEY ("GWKEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  commit;