
  drop table GL_ZHUFULINK;

  CREATE TABLE "PDM10"."GL_ZHUFULINK"
   (	"GWKEY" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"FZTECHNICSNUMBER" VARCHAR2(100 BYTE),
	"FZTECHNICSVERSION" VARCHAR2(100 BYTE),
	"FZPROCEDURENUMBER" VARCHAR2(100 BYTE),
	"ZZTECHNICSNUMBER" VARCHAR2(100 BYTE),
	"ZZTECHNICSVERSION" VARCHAR2(100 BYTE),
	"ZZPROCEDURENUMBER" VARCHAR2(100 BYTE),
	"PICIHAO" VARCHAR2(100 BYTE),
	 CONSTRAINT "GL_ZHUFULINK_PK" PRIMARY KEY ("GWKEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;