
  drop table GL_ZHUFULINKRECORD;

    CREATE TABLE "PDM10"."GL_ZHUFULINKRECORD"
   (	"GWKEY" VARCHAR2(100 BYTE) DEFAULT sys_guid() NOT NULL ENABLE, 
	"ZSTEPNUMBER" VARCHAR2(100 BYTE),
	"ZSTEPNAME" VARCHAR2(100 BYTE),
	"ZSTEPBSOID" VARCHAR2(200 BYTE),
	"ZTECHNICSNUMBER" VARCHAR2(100 BYTE),
	"ZPLANVERSION" VARCHAR2(50 BYTE),
	"FPLANNUMBER" VARCHAR2(300 BYTE),
	"FPLANNAME" VARCHAR2(500 BYTE),
	"FTECHNICSNUMBER" VARCHAR2(100 BYTE),
	"FPLANVERSION" VARCHAR2(50 BYTE),
	"CREATOR" VARCHAR2(100 BYTE),
	"CREATETIME" VARCHAR2(100 BYTE),
	"OPERATION" VARCHAR2(100 BYTE),
	 CONSTRAINT "GL_ZHUFULINKRECORD_PK" PRIMARY KEY ("GWKEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  commit;