######################################################################
#DFMPro集成注册配置
######################################################################
#
wt.services/svc/default/com.ptc.core.components.descriptor.DataUtility/rulePackageDataUtility/java.lang.Object/0=ext.casc.dfmRule.handler.RulePackageDataUtility/duplicate
wt.services/svc/default/com.ptc.core.components.beans.TreeHandler/rulePackageTreeHandler/java.lang.Object/0=ext.casc.dfmRule.handler.RulePackageTreeHandler/duplicate
