package com.glaway.mpm.erp;

import com.glaway.mpm.util.ValueCache;
import com.glaway.mpm.util.XmlUtility;
import com.glaway.mpm.view.NewTechnicsPart;
import com.glaway.mpm.view.XWPartTreeObject;
import com.glaway.mpm.view.XWTreeNode;
import com.glaway.mpm.view.XWTreeObject;
import org.dom4j.Element;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import java.awt.*;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import java.util.Vector;

/**
 * 用于显示工艺定额的数据
 *
 * @author LongXiuChuan 2014/6/3
 */
public class GWTechnicsDEJPanel extends javax.swing.JPanel {

    private Container parentPanel;

    /**
     * Creates new form TechnicsDEJPanel
     */
    public GWTechnicsDEJPanel(Container parentPanel) {
        this.parentPanel = parentPanel;
        initComponents();
        setName("gyde");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        jPanel4 = new javax.swing.JPanel();
        jScrollPane4= new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        jPanel5 = new javax.swing.JPanel();
        jScrollPane5= new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();

        jPanel6 = new javax.swing.JPanel();
        jScrollPane6= new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();

        //jPanel1    jScrollPane1     jTable1
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("添加的标准件/元器件/外购件"));

        jTable1.setModel(new DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "序号","是否已匹配" ,"历史数据","上级图号", "图号", "存货编码", "存货名称", "工艺数量", "单位", "型号牌号", "规格", "技术条件", "生产厂家", "主计量单位", "附加条件", "螺纹规格/公称尺寸", "机械性能等级", "质量等级", "封装形式", "精度等级", "产品代号", "电参数特选要求", "备注"
                }
        ) {
            Class[] types = new Class[]{
                    String.class,Boolean.class ,String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class
            };
            boolean[] canEdit = new boolean[]{
                    false,true,false, false, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1035, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
        );

        //jPanel2     jScrollPane2    jTable2
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("匹配的标准件/元器件/外购件"));

        jTable2.setModel(new DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "序号","是否已匹配" , "历史数据", "图号", "存货编码", "存货名称", "设计数量", "工艺数量", "单位", "型号牌号", "规格", "技术条件", "生产厂家", "主计量单位", "附加条件", "螺纹规格/公称尺寸", "机械性能等级", "质量等级", "封装形式", "精度等级", "产品代号", "电参数特选要求", "备注"
                }
        ) {
            Class[] types = new Class[]{
                    String.class, Boolean.class ,String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class
            };
            boolean[] canEdit = new boolean[]{
                    false, true,false,false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1047, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 178, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
        );

        //jpanel3

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("主要材料"));

        jTable3.setModel(new DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "序号","是否已匹配" , "历史数据", "定额类型", "存货编码", "存货名称", "下料尺寸", "可制件数", "数量", "试件尺寸","试件可制件数","试件数量", "单位", "型号牌号", "规格", "技术条件", "生产厂家", "主计量单位", "附加条件", "供应状态/热处理", "质量等级", "封装形式", "精度等级", "螺纹规格/公称尺寸", "机械性能等级","电参考特选要求","备注"
                }
        ) {
            Class[] types = new Class[]{
                    String.class, Boolean.class ,String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class
            };
            boolean[] canEdit = new boolean[]{
                    false, true,false, false,false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTable3.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1047, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 178, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
        );



        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("试件原材料"));

        jTable4.setModel(new DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "序号","是否已匹配" , "历史数据", "定额类型", "存货编码", "存货名称", "下料尺寸", "可制件数", "数量", "试件尺寸","试件可制件数","试件数量", "单位", "型号牌号", "规格", "技术条件", "生产厂家", "主计量单位", "附加条件", "供应状态/热处理", "质量等级", "封装形式", "精度等级", "螺纹规格/公称尺寸", "机械性能等级","电参考特选要求","备注"
                }
        ) {
            Class[] types = new Class[]{
                    String.class, Boolean.class ,String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class
            };
            boolean[] canEdit = new boolean[]{
                    false, true,false,false,false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTable4.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jTable4);


        TableColumnModel columnModel1 = jTable1.getColumnModel();
        columnModel1.getColumn(1).setCellEditor(jTable1.getDefaultEditor(Boolean.class));
        columnModel1.getColumn(1).setCellRenderer(jTable1.getDefaultRenderer(Boolean.class));
        TableColumnModel columnModel2 = jTable2.getColumnModel();
        columnModel2.getColumn(1).setCellEditor(jTable2.getDefaultEditor(Boolean.class));
        columnModel2.getColumn(1).setCellRenderer(jTable2.getDefaultRenderer(Boolean.class));
        TableColumnModel columnModel3 = jTable3.getColumnModel();
        columnModel3.getColumn(1).setCellEditor(jTable3.getDefaultEditor(Boolean.class));
        columnModel3.getColumn(1).setCellRenderer(jTable3.getDefaultRenderer(Boolean.class));
        TableColumnModel columnModel4 = jTable4.getColumnModel();
        columnModel4.getColumn(1).setCellEditor(jTable4.getDefaultEditor(Boolean.class));
        columnModel4.getColumn(1).setCellRenderer(jTable4.getDefaultRenderer(Boolean.class));



        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1047, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 178, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
        );


        //layout
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );



    }

    public void setTableValues(Element technicsElement) {
        clearTable();
        Element gyde = XmlUtility.getTechnicsDEElement(technicsElement);
        if (gyde == null) {
            return;
        }
        List<Element> newParts = XmlUtility.getTechnicsGYDENewPart(gyde);
        if (newParts != null && !newParts.isEmpty()) {
            int row = 0;
            int n = 1;
            for (Element element : newParts) {
                Vector vector = new Vector();
                for (int j = 0; j < jTable1.getColumnCount(); j++) {
                    if(j==1){
                        vector.add(false);
                    }else{
                        vector.add("");
                    }
                }
                ((DefaultTableModel) jTable1.getModel()).addRow(vector);
                ((DefaultTableModel) jTable1.getModel()).setValueAt(n, row, 0);
                String tabType = element.attributeValue("tabType");
                if (!"".equals(tabType)&&!"null".equals(tabType)&&tabType!=null) {
                    ((DefaultTableModel) jTable1.getModel()).setValueAt(true, row, 1);
                    ((DefaultTableModel) jTable1.getModel()).setValueAt("否", row, 2);
                }else{
                    ((DefaultTableModel) jTable1.getModel()).setValueAt(false, row, 1);
                    ((DefaultTableModel) jTable1.getModel()).setValueAt("是", row, 2);
                }

                ((DefaultTableModel) jTable1.getModel()).setValueAt(element.attributeValue("parentNumber"), row, 3);
                ((DefaultTableModel) jTable1.getModel()).setValueAt(element.attributeValue("number"), row, 4);
                ((DefaultTableModel) jTable1.getModel()).setValueAt(element.attributeValue("chbm"), row, 5);
                ((DefaultTableModel) jTable1.getModel()).setValueAt(element.attributeValue("chmc"), row, 6);
                ((DefaultTableModel) jTable1.getModel()).setValueAt(element.attributeValue("sl"), row, 7);
                ((DefaultTableModel) jTable1.getModel()).setValueAt(element.attributeValue("dw2"), row, 8);
                ((DefaultTableModel) jTable1.getModel()).setValueAt(element.attributeValue("xhph"), row, 9);
                ((DefaultTableModel) jTable1.getModel()).setValueAt(element.attributeValue("gg"), row, 10);
                ((DefaultTableModel) jTable1.getModel()).setValueAt(element.attributeValue("jstj"), row, 11);
                ((DefaultTableModel) jTable1.getModel()).setValueAt(element.attributeValue("sccj"), row, 12);
                ((DefaultTableModel) jTable1.getModel()).setValueAt(element.attributeValue("dw"), row, 13);
                ((DefaultTableModel) jTable1.getModel()).setValueAt(element.attributeValue("fjtj"), row, 14);
                ((DefaultTableModel) jTable1.getModel()).setValueAt(element.attributeValue("lwgggccc"), row, 15);
                ((DefaultTableModel) jTable1.getModel()).setValueAt(element.attributeValue("jxxndj"), row, 16);
                ((DefaultTableModel) jTable1.getModel()).setValueAt(element.attributeValue("zldj"), row, 17);
                ((DefaultTableModel) jTable1.getModel()).setValueAt(element.attributeValue("fzxs"), row, 18);
                ((DefaultTableModel) jTable1.getModel()).setValueAt(element.attributeValue("jddj"), row, 19);
                ((DefaultTableModel) jTable1.getModel()).setValueAt(element.attributeValue("cpdh"), row, 20);
                ((DefaultTableModel) jTable1.getModel()).setValueAt(element.attributeValue("dcstxyq"), row, 21);
                ((DefaultTableModel) jTable1.getModel()).setValueAt(element.attributeValue("comment"), row, 22);

                row++;
                n++;
            }
        }
        List<Element> matchParts = XmlUtility.getTechnicsGYDEMatchPart(gyde);
        if (matchParts != null && !matchParts.isEmpty()) {
            int row = 0;
            int n = 1;
            List<String> selNodesNumber = getSelNodesNumber();
            for (Element element : matchParts) {
                if(!selNodesNumber.contains(element.attributeValue("number"))){
                    continue;
                }
                Vector vector = new Vector();
                for (int j = 0; j < jTable2.getColumnCount(); j++) {
                    if(j==1){
                        vector.add(false);
                    }else{
                        vector.add("");
                    }
                }
                ((DefaultTableModel) jTable2.getModel()).addRow(vector);
                //"序号", "图号", "存货编码", "存货名称", "设计数量","工艺数量", "型号牌号", "规格", "技术条件",
                //"生产厂家", "主计量单位", "附加条件", "螺纹规格/公称尺寸", "机械性能等级", "质量等级", "封装形式", "精度等级","备注"
                ((DefaultTableModel) jTable2.getModel()).setValueAt(n, row, 0);
                String tabType = element.attributeValue("tabType");
                if (!"".equals(tabType)&&!"null".equals(tabType)&&tabType!=null) {
                    ((DefaultTableModel) jTable2.getModel()).setValueAt(true, row, 1);
                    ((DefaultTableModel) jTable2.getModel()).setValueAt("否", row, 2);
                }else{
                    ((DefaultTableModel) jTable2.getModel()).setValueAt(false, row, 1);
                    ((DefaultTableModel) jTable2.getModel()).setValueAt("是", row, 2);
                }
                ((DefaultTableModel) jTable2.getModel()).setValueAt(element.attributeValue("number"), row, 3);
                ((DefaultTableModel) jTable2.getModel()).setValueAt(element.attributeValue("chbm"), row, 4);
                ((DefaultTableModel) jTable2.getModel()).setValueAt(element.attributeValue("chmc"), row, 5);
                ((DefaultTableModel) jTable2.getModel()).setValueAt(element.attributeValue("useCount"), row, 6);
                ((DefaultTableModel) jTable2.getModel()).setValueAt(element.attributeValue("gyCount"), row, 7);
                ((DefaultTableModel) jTable2.getModel()).setValueAt(element.attributeValue("dw2"), row, 8);
                ((DefaultTableModel) jTable2.getModel()).setValueAt(element.attributeValue("xhph"), row, 9);
                ((DefaultTableModel) jTable2.getModel()).setValueAt(element.attributeValue("gg"), row, 10);
                ((DefaultTableModel) jTable2.getModel()).setValueAt(element.attributeValue("jstj"), row, 11);
                ((DefaultTableModel) jTable2.getModel()).setValueAt(element.attributeValue("sccj"), row, 12);
                ((DefaultTableModel) jTable2.getModel()).setValueAt(element.attributeValue("dw"), row, 13);
                ((DefaultTableModel) jTable2.getModel()).setValueAt(element.attributeValue("fjtj"), row, 14);
                ((DefaultTableModel) jTable2.getModel()).setValueAt(element.attributeValue("lwgggccc"), row, 15);
                ((DefaultTableModel) jTable2.getModel()).setValueAt(element.attributeValue("jxxndj"), row, 16);
                ((DefaultTableModel) jTable2.getModel()).setValueAt(element.attributeValue("zldj"), row, 17);
                ((DefaultTableModel) jTable2.getModel()).setValueAt(element.attributeValue("fzxs"), row, 18);
                ((DefaultTableModel) jTable2.getModel()).setValueAt(element.attributeValue("jddj"), row, 19);
                ((DefaultTableModel) jTable2.getModel()).setValueAt(element.attributeValue("cpdh"), row, 20);
                ((DefaultTableModel) jTable2.getModel()).setValueAt(element.attributeValue("dcstxyq"), row, 21);
                ((DefaultTableModel) jTable2.getModel()).setValueAt(element.attributeValue("comment"), row, 22);
                row++;
                n++;
            }
        }
        List<Element> zycl = XmlUtility.getTechnicsZYCLDE(gyde);
        if(zycl != null && !zycl.isEmpty()) {
            int row = 0;
            int n = 1;
            for (Element element : zycl) {
                Vector vector = new Vector();
                for (int j = 0; j < jTable3.getColumnCount(); j++) {
                    if(j==1){
                        vector.add(false);
                    }else{
                        vector.add("");
                    }
                }
                ((DefaultTableModel) jTable3.getModel()).addRow(vector);
                ((DefaultTableModel) jTable3.getModel()).setValueAt(n, row, 0);
                String tabType = element.attributeValue("tabType");
                if (!"".equals(tabType)&&!"null".equals(tabType)&&tabType!=null) {
                    ((DefaultTableModel) jTable3.getModel()).setValueAt(true, row, 1);
                    ((DefaultTableModel) jTable3.getModel()).setValueAt("否", row, 2);
                }else{
                    ((DefaultTableModel) jTable3.getModel()).setValueAt(false, row, 1);
                    ((DefaultTableModel) jTable3.getModel()).setValueAt("是", row, 2);
                }
                ((DefaultTableModel) jTable3.getModel()).setValueAt("主要材料", row, 3);
                ((DefaultTableModel) jTable3.getModel()).setValueAt(element.attributeValue("chbm"), row, 4);
                ((DefaultTableModel) jTable3.getModel()).setValueAt(element.attributeValue("chmc"), row, 5);
                ((DefaultTableModel) jTable3.getModel()).setValueAt("", row, 6);
                ((DefaultTableModel) jTable3.getModel()).setValueAt("", row, 7);
                ((DefaultTableModel) jTable3.getModel()).setValueAt(element.attributeValue("sl"), row, 8);
                ((DefaultTableModel) jTable3.getModel()).setValueAt("", row, 9);
                ((DefaultTableModel) jTable3.getModel()).setValueAt("", row, 10);
                ((DefaultTableModel) jTable3.getModel()).setValueAt("", row, 11);
                ((DefaultTableModel) jTable3.getModel()).setValueAt(element.attributeValue("dw"), row, 12);
                ((DefaultTableModel) jTable3.getModel()).setValueAt(element.attributeValue("xhph"), row, 13);
                ((DefaultTableModel) jTable3.getModel()).setValueAt(element.attributeValue("gg"), row, 14);
                ((DefaultTableModel) jTable3.getModel()).setValueAt(element.attributeValue("jstj"), row, 15);
                ((DefaultTableModel) jTable3.getModel()).setValueAt(element.attributeValue("sccj"), row, 16);
                ((DefaultTableModel) jTable3.getModel()).setValueAt(element.attributeValue("zjldw"), row, 17);
                ((DefaultTableModel) jTable3.getModel()).setValueAt(element.attributeValue("fjtj"), row, 18);
                ((DefaultTableModel) jTable3.getModel()).setValueAt(element.attributeValue("gyztrcl"), row, 19);

                ((DefaultTableModel) jTable3.getModel()).setValueAt(element.attributeValue("zldj"), row, 20);
                ((DefaultTableModel) jTable3.getModel()).setValueAt(element.attributeValue("fzxs"), row, 21);
                ((DefaultTableModel) jTable3.getModel()).setValueAt(element.attributeValue("jddj"), row, 22);
                ((DefaultTableModel) jTable3.getModel()).setValueAt(element.attributeValue("lwgg"), row, 23);
                ((DefaultTableModel) jTable3.getModel()).setValueAt(element.attributeValue("jxxndj"), row, 24);
                ((DefaultTableModel) jTable3.getModel()).setValueAt(element.attributeValue("dcstxyq"), row, 25);
                ((DefaultTableModel) jTable3.getModel()).setValueAt(element.attributeValue("comment"), row, 26);

                row++;
                n++;
            }
        }
        //试件原材料信息
        List<Element> sjycl = XmlUtility.getTechnicsSJYCLDE(gyde);
        if(sjycl != null && !sjycl.isEmpty()) {
            int row = 0;
            int n = 1;
            for (Element element : sjycl) {
                Vector vector = new Vector();
                for (int j = 0; j < jTable4.getColumnCount(); j++) {
                    if(j==1){
                        vector.add(false);
                    }else{
                        vector.add("");
                    }
                }
                ((DefaultTableModel) jTable4.getModel()).addRow(vector);
                ((DefaultTableModel) jTable4.getModel()).setValueAt(n, row, 0);
                String tabType = element.attributeValue("tabType");
                if (!"".equals(tabType)&&!"null".equals(tabType)&&tabType!=null) {
                    ((DefaultTableModel) jTable4.getModel()).setValueAt(true, row, 1);
                    ((DefaultTableModel) jTable4.getModel()).setValueAt("否", row, 2);
                }else{
                    ((DefaultTableModel) jTable4.getModel()).setValueAt(false, row, 1);
                    ((DefaultTableModel) jTable4.getModel()).setValueAt("是", row, 2);
                }
                ((DefaultTableModel) jTable4.getModel()).setValueAt("试件原材料", row, 3);
                ((DefaultTableModel) jTable4.getModel()).setValueAt(element.attributeValue("chbm"), row, 4);
                ((DefaultTableModel) jTable4.getModel()).setValueAt(element.attributeValue("chmc"), row, 5);
                ((DefaultTableModel) jTable4.getModel()).setValueAt("", row, 6);
                ((DefaultTableModel) jTable4.getModel()).setValueAt("", row, 7);
                ((DefaultTableModel) jTable4.getModel()).setValueAt("", row, 8);
                ((DefaultTableModel) jTable4.getModel()).setValueAt(element.attributeValue("sjcc"), row, 9);
                ((DefaultTableModel) jTable4.getModel()).setValueAt(element.attributeValue("sjkzjs"), row, 10);
                ((DefaultTableModel) jTable4.getModel()).setValueAt(element.attributeValue("sjsl"), row, 11);
                ((DefaultTableModel) jTable4.getModel()).setValueAt(element.attributeValue("dw"), row, 12);
                ((DefaultTableModel) jTable4.getModel()).setValueAt(element.attributeValue("xhph"), row, 13);
                ((DefaultTableModel) jTable4.getModel()).setValueAt(element.attributeValue("gg"), row, 14);
                ((DefaultTableModel) jTable4.getModel()).setValueAt(element.attributeValue("jstj"), row, 15);
                ((DefaultTableModel) jTable4.getModel()).setValueAt(element.attributeValue("sccj"), row, 16);
                ((DefaultTableModel) jTable4.getModel()).setValueAt(element.attributeValue("zjldw"), row, 17);
                ((DefaultTableModel) jTable4.getModel()).setValueAt(element.attributeValue("fjtj"), row, 18);
                ((DefaultTableModel) jTable4.getModel()).setValueAt(element.attributeValue("gyztrcl"), row, 19);
                ((DefaultTableModel) jTable4.getModel()).setValueAt(element.attributeValue("zldj"), row, 20);
                ((DefaultTableModel) jTable4.getModel()).setValueAt(element.attributeValue("fzxs"), row, 21);
                ((DefaultTableModel) jTable4.getModel()).setValueAt(element.attributeValue("jddj"), row, 22);
                ((DefaultTableModel) jTable4.getModel()).setValueAt(element.attributeValue("lwgg"), row, 23);
                ((DefaultTableModel) jTable4.getModel()).setValueAt(element.attributeValue("jxxndj"), row, 24);
                ((DefaultTableModel) jTable4.getModel()).setValueAt(element.attributeValue("dcstxyq"), row, 25);
                ((DefaultTableModel) jTable4.getModel()).setValueAt(element.attributeValue("comment"), row, 26);
                row++;
                n++;
            }
        }




    }

    public void clearTable() {
        ((DefaultTableModel) jTable1.getModel()).setRowCount(0);
        ((DefaultTableModel) jTable2.getModel()).setRowCount(0);
        ((DefaultTableModel) jTable3.getModel()).setRowCount(0);
        ((DefaultTableModel) jTable4.getModel()).setRowCount(0);
    }

    public List<String> getSelNodesNumber() {
        List<String> selNodesNumber = new ArrayList<String>();
        XWTreeNode node = ((NewTechnicsPart) parentPanel).xwPartTreePanel.getSelectedTreeNode();
        Enumeration<XWTreeNode> enu = node.getP().children();
        XWTreeNode partNode = enu.nextElement();
        XWTreeObject treeObj = partNode.getObject();
        if (treeObj instanceof XWPartTreeObject) {
            XWPartTreeObject partObj = (XWPartTreeObject) treeObj;
            Element partEle = partObj.getTreeCellData();
            String mtype = partEle.attributeValue("MTYPE");
            String number = partEle.attributeValue("partNumber");
            String ctype = partEle.attributeValue("CTYPE");
            String partNumber = partEle.attributeValue("partNumber");
            ValueCache.allPartsType.put(number, mtype);
            if ("标准件".equals(mtype) || "元器件".equals(mtype) || "外购件".equals(mtype)) {
                selNodesNumber.add(partNumber);
            } else if ("标准件".equals(ctype) || "元器件".equals(ctype) || "外购件".equals(ctype)) {
                selNodesNumber.add(partNumber);
            }
        }
        return selNodesNumber;
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;

    // End of variables declaration


    public JTable getjTable1() {
        return jTable1;
    }

    public JTable getjTable2() {
        return jTable2;
    }

    public JTable getjTable3() {
        return jTable3;
    }

    public JTable getjTable4() {
        return jTable4;
    }
}
