isNeedSearchButton=true
workflow_config_file=codebase\\ext\\ases\\workflow\\setparticipant\\workflow_config.xls
\u7f16\u5236=SUBMITTER
\u6821\u5bf9=ASES_JIAODUI
\u5ba1\u6838=ASES_SHENHE
\u5185\u90e8\u4f1a\u7b7e=ASES_HUIQIAN
\u5916\u90e8\u4f1a\u7b7e=ASES_WAIBUPM
\u5185\u90e8\u5de5\u827a=ASES_GONGYI
\u5916\u90e8\u5de5\u827a=ASES_WAIBUGONGYI
\u6807\u5ba1=ASES_BIAOSHEN
\u6279\u51c6=APPROVER
\u7528\u6237\u4f1a\u7b7e=ASES_CONFIRMER
