CREATE INDEX SignActivityLink$COMPOSITE0 ON SignActivityLink(idA3A5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX SignActivityLink$COMPOSITE1 ON SignActivityLink(idA3B5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
