CREATE INDEX ProcessTaskItem$COMPOSITE1 ON ProcessTaskItem(idA3A2folderingInfo)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX ProcessTaskItem$COMPOSITE2 ON ProcessTaskItem(idA3teamId)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX ProcessTaskItem$COMPOSITE6 ON ProcessTaskItem(idA3containerReference)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX ProcessTaskItem$COMPOSITE20 ON ProcessTaskItem(ProcessTaskItemNumber)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
