CREATE INDEX ProcessPlan$COMPOSITE1 ON ProcessPlan(idA3A2folderingInfo)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX ProcessPlan$COMPOSITE2 ON ProcessPlan(idA3teamId)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX ProcessPlan$COMPOSITE6 ON ProcessPlan(idA3containerReference)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX ProcessPlan$COMPOSITE20 ON ProcessPlan(ProcessTaskNumber)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
