CREATE INDEX ProcessTaskLink$COMPOSITE0 ON ProcessTaskLink(idA3A5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX ProcessTaskLink$COMPOSITE1 ON ProcessTaskLink(idA3B5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
