CREATE INDEX ProcessTask$COMPOSITE1 ON ProcessTask(idA3A2folderingInfo)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX ProcessTask$COMPOSITE2 ON ProcessTask(idA3teamId)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX ProcessTask$COMPOSITE6 ON ProcessTask(idA3containerReference)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX ProcessTask$COMPOSITE20 ON ProcessTask(ProcessTaskNumber)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
