package com.glaway.mpm.view;

import com.glaway.mpm.model.CMatBean;
import com.glaway.mpm.util.CommonUIUtil;
import com.glaway.mpm.util.TechnicsUtil;
import com.glaway.mpm.wcIntf.TechnicsIntf;
import org.dom4j.Element;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.lang.reflect.InvocationTargetException;
import java.rmi.RemoteException;
import java.util.List;
import java.util.*;

/**
* 用户批量提交材料定额签审流程
* 入口在PBOM的右键菜单，收集该PBOM及其所有子件的属于当前用户创建的工艺文件
*
* @author LongXiuChuan 2014/6/26
*/
public class BatchCldeSubmitJDialog {

	private JButton jButton1;
	private JButton jButton2;
	private JButton jButton3;
	private JButton jButton4;
	private JPanel jPanel1;
	private JPanel jPanel2;
	private JScrollPane jScrollPane2;
	private JTable jTable2;
	private JDialog dialog;
	private NewTechnicsPart frame;
	private XWTreeNode node;
	private Map<String, Element> map;
	private Map<String, Element> partEleMap;
	private Map<Element, XWTreeNode> partMap;
	private JComboBox comboBox;
	private Map<String, String> taskMap = new HashMap<String, String>();
	private int lastSelect = -1;

	/**
	 * Creates new form BatchCldeSubmitJDialog
	 */
	public BatchCldeSubmitJDialog(NewTechnicsPart frame, XWTreeNode node) {
		super();
		this.frame = frame;
		this.node = node;
		showDialog();
	}

	public void showDialog() {
		newJDialog();
		initComponents();
		loadDataNew();
		dialog.setModal(true);
		dialog.setResizable(false);
		setMiddleOnScreenWithDialog(dialog);
		dialog.setVisible(true);
	}

	/**
	 * 新增对话框jdialog
	 */
	public void newJDialog() {
		dialog = new JDialog();
		dialog.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
		dialog.setTitle("批量提交材料定额签审流程");
		dialog.setSize(1600, 800);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		jPanel1 = new JPanel();
		jScrollPane2 = new JScrollPane();
		jTable2 = new JTable();
		jPanel2 = new JPanel();
		jButton1 = new JButton();
		jButton2 = new JButton();
		jButton3 = new JButton();
		jButton4 = new JButton();

		jTable2.setModel(new DefaultTableModel(
				new Object[][]{},
				new String[]{"选择", "零件编号", "工艺文件编号", "工艺文件名称", "工艺文件状态", "材料定额状态", "工艺任务","partOid","docNumber","taskOid","docVersion"}
		) {
			private static final long serialVersionUID = 1L;
			Class[] types = new Class[]{
					Boolean.class, String.class, String.class, String.class, String.class, String.class, String.class,String.class, String.class,String.class,String.class
			};
			boolean[] canEdit = new boolean[]{true, false, false, false, false, false, true, false, false,false,false};

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		comboBox = new JComboBox();
		comboBox.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {

				String selectedTask = (String)comboBox.getSelectedItem();
				if(selectedTask == null){
					return;
				}
				String taskid = taskMap.get(selectedTask);
				int row = jTable2.getSelectedRow();
				if(row != -1 && lastSelect != row){
					jTable2.setValueAt(taskid,row,9);
				}
				lastSelect = row;
				jTable2.clearSelection();
			}
		});
		jTable2.getColumnModel().getColumn(6).setCellEditor(new CldeSubmitTableCellEditor(comboBox));
		CommonUIUtil.hiddenCell(jTable2, 7);
		CommonUIUtil.hiddenCell(jTable2, 8);
		CommonUIUtil.hiddenCell(jTable2, 9);
		CommonUIUtil.hiddenCell(jTable2, 10);
		jTable2.getTableHeader().setReorderingAllowed(false);
		jScrollPane2.setViewportView(jTable2);
		jTable2.getColumnModel().getColumn(0).setMinWidth(40);
		jTable2.getColumnModel().getColumn(0).setMaxWidth(40);
		jTable2.getColumnModel().getColumn(6).setMinWidth(350);
		jTable2.getColumnModel().getColumn(6).setMaxWidth(400);
//       jTable2.getColumnModel().getColumn(4).setMinWidth(85);
//       jTable2.getColumnModel().getColumn(4).setMaxWidth(85);
//       jTable2.getColumnModel().getColumn(5).setMinWidth(100);
//       jTable2.getColumnModel().getColumn(5).setMaxWidth(100);

		GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addComponent(jScrollPane2)
		);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 304, GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE))
		);

		jButton1.setText("确  定");
		jButton1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("取  消");
		jButton2.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setText("全  选");
		jButton3.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setText("取消选择");
		jButton4.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addGap(201, 201, 201)
								.addComponent(jButton1)
								.addGap(18, 18, 18)
								.addComponent(jButton2)
								.addGap(18, 18, 18)
								.addComponent(jButton3)
								.addGap(18, 18, 18)
								.addComponent(jButton4)
								.addContainerGap(165, Short.MAX_VALUE))
		);
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addGap(19, 19, 19)
								.addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
										.addComponent(jButton1)
										.addComponent(jButton2)
										.addComponent(jButton3)
										.addComponent(jButton4))
								.addContainerGap(21, Short.MAX_VALUE))
		);

		GroupLayout layout = new GroupLayout(dialog.getContentPane());
		dialog.getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		);

	}

	private void loadDataNew() {
		try {
			if (node != null) {
				List<Element> techElementList = getAllCldeProcessPlan();
				if (techElementList != null && techElementList.size() > 0) {
					map = new HashMap<String, Element>();
					for (Element techElement : techElementList) {
						String technicNumber = techElement.attributeValue("technicsNumber");
						map.put(technicNumber, techElement);
					}
					partEleMap = new HashMap<String, Element>();
					loopNodeNew(node);
					DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
					for (Element element : techElementList) {
						setTableValues(element, tableModel);
					}
				}
			}

		} catch (InvocationTargetException e) {
			e.printStackTrace();
		} catch (RemoteException e) {
			e.printStackTrace();
		}
	}

	private void loopNodeNew(XWTreeNode node) {
		Element partElement = node.getObject().getTreeCellData();
		String partNumber = partElement.attributeValue("partNumber");
		partEleMap.put(partNumber, partElement);
		Enumeration<XWTreeNode> num = node.children();
		while (num.hasMoreElements()) {
			XWTreeNode childNode = num.nextElement();
			if(childNode.getObject() instanceof TechnicsMessageTreeObject){

			}else{
				loopNodeNew(childNode);
			}
		}
	}


	private void loadData() {
		if (node != null) {
			List<Element> list = new ArrayList<Element>();
			map = new HashMap<String, Element>();
			partMap = new HashMap<Element, XWTreeNode>();
			loopNode(node, list);
			if (list != null && !list.isEmpty()) {
				DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
				for (Element element : list) {
					setTableValues(element, tableModel);
				}
			}
		}
	}

	private List<Element> getAllCldeProcessPlan() throws InvocationTargetException, RemoteException {
		String partOid = node.getObject().getTreeCellData().attributeValue("oid");
		return TechnicsIntf.getAllCldeProcessPlan(partOid, NewTechnicsPart.currentUser);
	}

	private void loopNode(XWTreeNode node, List<Element> list) {
		Enumeration<XWTreeNode> num = node.children();
		while (num.hasMoreElements()) {
			XWTreeNode childNode = num.nextElement();
			if (childNode.getObject() instanceof TechnicsMessageTreeObject) {
				TechnicsMessageTreeObject obj = (TechnicsMessageTreeObject) childNode.getObject();
				Element ele = obj.getTreeCellData();
				if (ele != null) {
					String creator = ele.attributeValue("creator");
					//String state = ele.attributeValue("lifecycle");
					if (creator.equals(frame.currentUser)) {
						list.add(ele);
						map.put(ele.attributeValue("technicsNumber"), ele);
						partMap.put(ele, node);
					}
				}
			} else {
				loopNode(childNode, list);
			}
		}
	}

	private void setTableValuesNew(Map<String, String> processAttrMap, DefaultTableModel tableModel){
		Vector vector = new Vector();
		for (int j = 0; j < jTable2.getColumnCount(); j++) {
			if (j == 0) {
				vector.add(false);
			} else {
				vector.add("");
			}
		}
		tableModel.addRow(vector);
		tableModel.setValueAt(processAttrMap.get("partNumber"), jTable2.getRowCount() - 1, 1);
		tableModel.setValueAt(processAttrMap.get("pplanNumber"), jTable2.getRowCount() - 1, 2);
		tableModel.setValueAt(processAttrMap.get("pplanName"), jTable2.getRowCount() - 1, 3);
		tableModel.setValueAt(processAttrMap.get("lifecycle"), jTable2.getRowCount() - 1, 4);
		tableModel.setValueAt(processAttrMap.get("version"), jTable2.getRowCount() - 1, 10);
		tableModel.setValueAt(processAttrMap.get("taskOid"), jTable2.getRowCount() - 1, 6);
		tableModel.setValueAt(processAttrMap.get("taskDisPlay"), jTable2.getRowCount() - 1, 9);
		tableModel.setValueAt(processAttrMap.get("partOid"), jTable2.getRowCount() - 1, 7);
		tableModel.setValueAt(processAttrMap.get("technicsNumber"), jTable2.getRowCount() - 1, 8);
		tableModel.setValueAt(processAttrMap.get("cldeState"), jTable2.getRowCount() - 1, 5);

	}
	private void setTableValues(Element ele, DefaultTableModel tableModel) {
		Vector vector = new Vector();
		for (int j = 0; j < jTable2.getColumnCount(); j++) {
			if (j == 0) {
				vector.add(false);
			} else {
				vector.add("");
			}

		}
		tableModel.addRow(vector);

		tableModel.setValueAt(ele.attributeValue("partNumber"), jTable2.getRowCount() - 1, 1);
		tableModel.setValueAt(ele.attributeValue("pplanNumber"), jTable2.getRowCount() - 1, 2);
		tableModel.setValueAt(ele.attributeValue("pplanName"), jTable2.getRowCount() - 1, 3);
		tableModel.setValueAt(ele.attributeValue("lifecycle"), jTable2.getRowCount() - 1, 4);
		tableModel.setValueAt(ele.attributeValue("version"), jTable2.getRowCount() - 1, 10);
		try {
			Map<String, String> allProcessTask = TechnicsIntf.getAllProcessTask(ele.attributeValue("technicsNumber"), ele.attributeValue("partOid"), NewTechnicsPart.currentUser);
			if(allProcessTask.entrySet().iterator().hasNext() && allProcessTask.entrySet().size() == 1){
				Map.Entry<String, String> next = allProcessTask.entrySet().iterator().next();
				String disPlay = next.getKey();
				String taskOid = next.getValue();
				tableModel.setValueAt(taskOid, jTable2.getRowCount() - 1, 6);
				tableModel.setValueAt(disPlay, jTable2.getRowCount() - 1, 9);
			}
		} catch (InvocationTargetException e) {
			e.printStackTrace();
		} catch (RemoteException e) {
			e.printStackTrace();
		}

		tableModel.setValueAt(ele.attributeValue("partOid"), jTable2.getRowCount() - 1, 7);
		tableModel.setValueAt(ele.attributeValue("technicsNumber"), jTable2.getRowCount() - 1, 8);

		String cldeState = "";
		try {
			cldeState = TechnicsIntf.getCLDEState(ele.attributeValue("technicsNumber"));
		} catch (RemoteException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (InvocationTargetException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		if (cldeState == null || "null".equals(cldeState)) {
			cldeState = "";
		}
		tableModel.setValueAt(cldeState, jTable2.getRowCount() - 1, 5);
	}

	private void jButton1ActionPerformed(ActionEvent evt) {
		Map<String, List<CMatBean>> result = new HashMap<String, List<CMatBean>>();
		Map<String, String> taskMap = new HashMap<String, String>();
		String partNumber = "";
		XWTreeNode node = frame.xwPartTreePanel.getSelectedTreeNode();
		if (node != null) {
			XWTreeObject xo = node.getObject();
			if ((xo instanceof XWPartTreeObject)) {
				Element ele = xo.getTreeCellData();
				partNumber = ele.attributeValue("partNumber");
				System.out.println(partNumber);
			}
		}
		int rows = jTable2.getRowCount();
		if (rows > 0) {
			for (int n = 0; n < rows; n++) {
				boolean b = (Boolean) jTable2.getValueAt(n, 0);
				if (b) {
					String pplanNumber = String.valueOf(jTable2.getValueAt(n, 2));
					String docNumber = String.valueOf(jTable2.getValueAt(n, 8));
					String cldeState = String.valueOf(jTable2.getValueAt(n, 5));
					/*if("提交签审中".equals(cldeState)){
						JOptionPane.showMessageDialog(dialog, "工艺文件" + pplanNumber + "提交的材料定额正在签审中，无法继续提交签审！");
						return;
					}*/
					Element ele = map.get(docNumber);
					String partCode = ele.attributeValue("partNumber");
					Element partElement = partEleMap.get(partCode);
//					XWTreeNode partNode = partMap.get(ele);
//					XWPartTreeObject partObject = (XWPartTreeObject) partNode.getObject();
//					Element partEle = partObject.getTreeCellData();
					String partUseCount = partElement.attributeValue("useCount");
					String cindex = partElement.attributeValue("CINDEX");
					List<CMatBean> list = TechnicsUtil.generateSubmitList(ele, partUseCount, cindex);
					if (list != null && !list.isEmpty()) {
						String taskOid = (String) jTable2.getValueAt(n,9);
						String taskName = (String) jTable2.getValueAt(n,6);
						result.put(ele.attributeValue("technicsNumber"), list);
						if(taskName != null && !taskName.isEmpty()){
							taskMap.put(ele.attributeValue("technicsNumber"), taskOid);
						}
					} else {
						JOptionPane.showMessageDialog(dialog, "工艺文件" + pplanNumber + "无材料定额信息！");
						return;
					}
				}
			}
		}
		if (result.isEmpty()) {
			JOptionPane.showMessageDialog(dialog, "请选择需要提交材料定额签审流程的工艺文件！");
		} else {
			System.out.println("------result-----" + result);
//		   if(NewTechnicsPart.workItemOid == null || NewTechnicsPart.workItemOid.isEmpty()){
//			   JOptionPane.showMessageDialog(dialog, "未获取到相关工艺任务，请尝试从工艺编制任务启动工艺编辑器，重新提交材料定额");
//			   return;
//		   }
			frame.commitForBatchCmatSignedThread(result, taskMap, NewTechnicsPart.workItemOid,partNumber);
			dialog.setVisible(false);
		}
	}

	private void jButton2ActionPerformed(ActionEvent evt) {
		dialog.setVisible(false);
	}

	private void jButton3ActionPerformed(ActionEvent evt) {
		int rows = jTable2.getRowCount();
		if (rows > 0) {
			DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
			for (int n = 0; n < rows; n++) {
				tableModel.setValueAt(true, n, 0);
			}
		}
	}

	private void jButton4ActionPerformed(ActionEvent evt) {
		int rows = jTable2.getRowCount();
		if (rows > 0) {
			DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
			for (int n = 0; n < rows; n++) {
				tableModel.setValueAt(false, n, 0);
			}
		}
	}

	public static void setMiddleOnScreenWithDialog(JDialog dialog) {
		int windowWidth = dialog.getWidth();                     //获得窗口宽
		int windowHeight = dialog.getHeight();                   //获得窗口高
		Toolkit kit = Toolkit.getDefaultToolkit();              //定义工具包
		Dimension screenSize = kit.getScreenSize();             //获取屏幕的尺寸
		int screenWidth = screenSize.width;                     //获取屏幕的宽
		int screenHeight = screenSize.height;                   //获取屏幕的高
		dialog.setLocation(screenWidth / 2 - windowWidth / 2, screenHeight / 2 - windowHeight / 2);//设置窗口居中显示
	}

	class CldeSubmitTableCellEditor extends DefaultCellEditor {

		private static final long serialVersionUID = 1L;
		JComboBox combox = null;

		public CldeSubmitTableCellEditor(JComboBox comboBox) {
			super(comboBox);
			this.combox = comboBox;
			this.setClickCountToStart(1);

		}

		@Override
		public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row,int column) {
			combox.removeAllItems();
			taskMap.clear();
			jTable2.clearSelection();
			String partOid = (String) table.getValueAt(row,7);
			String docNumber = (String) table.getValueAt(row,8);
			String docVersion = (String) table.getValueAt(row,10);
			if(!docVersion.contains("space")){
				return combox;
			}
			String user = NewTechnicsPart.currentUser;
			try {
				combox.addItem("");
				Map<String, String> processTaskList = TechnicsIntf.getAllProcessTask(docNumber, partOid, user);
				for(Map.Entry<String, String> entry : processTaskList.entrySet()){
					String taskId = entry.getKey();
					String display = entry.getValue();
					taskMap.put(display,taskId);
					combox.addItem(display);
				}
				combox.setSelectedItem(1);
			} catch (Exception e) {
				e.printStackTrace();
			}
			return combox;
		}
	}
}
