package com.glaway.mpm.view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.rmi.RemoteException;
import java.util.List;
import java.util.Map;
import java.util.Vector;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

import org.dom4j.Element;

import com.glaway.mpm.util.PbomUtil;
import com.glaway.mpm.visual.log.VaLogger;
import com.glaway.mpm.wcIntf.TechnicsIntf;


/**
 * 显示PBOM的历史版本信息
 *
 * @author LongXiuChuan
 */
public class ChangeParentPartDialog {

    private JButton jButton1;
    private JButton jButton2;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JScrollPane jScrollPane1;
    private JTable jTable1;
    private JDialog dialog;
    private NewTechnicsPart frame;
    private XWTreeNode node;
    private String currentversion;
    private static VaLogger logger = VaLogger.getLogger(ChangeParentPartDialog.class);

	/**
     * Creates new form ShowPbomBatchsDialog
     */
    public ChangeParentPartDialog(NewTechnicsPart frame) {
        super();
        this.frame = frame;
        showDialog();
    }

    public void showDialog() {
    	newJDialog();
    	initComponents();
    	loadData();
    }

    /**
	 * 新增对话框jdialog
	 */
	public void newJDialog() {
		dialog = new JDialog(frame);
		dialog.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
		dialog.setTitle("PBOM父节点");
		dialog.setSize(665, 400);
		dialog.setVisible(true);
		dialog.setModal(true);
		setMiddleOnScreenWithDialog(dialog);
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new JPanel();
        jScrollPane1 = new JScrollPane();
        jTable1 = new JTable();
        jPanel2 = new JPanel();
        jButton1 = new JButton();
        jButton2 = new JButton();

        jTable1.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
            		"序号", "编号", "名称", "版本", "阶段", "批次", "状态", "OID"
            }
        ) {
			private static final long serialVersionUID = 1L;
			Class[] types = new Class [] {
                String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionBackground(new Color(51, 204, 255));
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(5);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setResizable(false);

        setHiddenColumn(7);

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 313, GroupLayout.PREFERRED_SIZE)
        );

        jButton1.setText("确定");
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("取消");
        jButton2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(41, 41, 41)
                .addComponent(jButton2)
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
        );

        GroupLayout layout = new GroupLayout(dialog.getContentPane());
        dialog.getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SwingUtilities.invokeLater(new Runnable() {
			@Override
			public void run() {
				dialog.setModal(true);
				dialog.setVisible(true);
			}
		});
    }

    private void loadData() {
//    	String partOid = "3283829";
    	String partOid = frame.childPartOid;
    	try {
			List<Map<String,String>> partInfoList = TechnicsIntf.getHasPbomXmlParentPartIda2a2List(partOid);
			setTableValues(partInfoList);
		} catch (RemoteException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (InvocationTargetException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }

    private void setTableValues(List<Map<String, String>> partInfoList) {
    	DefaultTableModel tableModel = (DefaultTableModel)jTable1.getModel();
    	for (int n=0; n < partInfoList.size(); n++) {
    		Vector vector = new Vector();
			for (int j = 0; j < jTable1.getColumnCount(); j++) {
				vector.add("");
			}
			Map<String, String> partInfo = partInfoList.get(n);
			//blist:0为批次,1为版本,2为状态,3为OID,4为阶段标记
			tableModel.addRow(vector);
			//"序号", "编号", "名称", "版本", "阶段", "批次", "状态", "OID"
			tableModel.setValueAt(n+1, n, 0);
			tableModel.setValueAt(partInfo.get("partNumber"), n, 1);
			tableModel.setValueAt(partInfo.get("partName"), n, 2);
			tableModel.setValueAt(partInfo.get("partVersion"), n, 3);
			tableModel.setValueAt(partInfo.get("partPhase_code"), n, 4);
			tableModel.setValueAt(partInfo.get("partBatch"), n, 5);
			tableModel.setValueAt(partInfo.get("partState"), n, 6);
			tableModel.setValueAt(partInfo.get("partOid"), n, 7);
		}
    }

    private void jButton2ActionPerformed(ActionEvent evt) {
    	dialog.setVisible(false);
    }

    private void jButton1ActionPerformed(ActionEvent evt) {
    	int row = jTable1.getSelectedRow();
    	String pbomOid = String.valueOf(jTable1.getValueAt(row, 7));
    	String partNumber = String.valueOf(jTable1.getValueAt(row, 1));
    	try {
    		int option = JOptionPane.showConfirmDialog(dialog, "是否确认切换PBOM父节点到："+partNumber +" ？", "提示", JOptionPane.OK_CANCEL_OPTION);
			if(option == 0){
				frame.resetPbomBatch(pbomOid);
				JOptionPane.showMessageDialog(dialog, "PBOM父节点已经切换到：" + partNumber);
			}
		} catch (Exception e) {
			JOptionPane.showMessageDialog(dialog, "PBOM父节点切换失败，请联系管理员！\r\n" + e.getLocalizedMessage());
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	dialog.setVisible(false);
    }

	public void setHiddenColumn(int columnIndex) {
		if (columnIndex >= 0 && columnIndex < jTable1.getColumnCount()) {
			// 隐藏ID列
			jTable1.getTableHeader().getColumnModel().getColumn(columnIndex).setMaxWidth(0);
			jTable1.getTableHeader().getColumnModel().getColumn(columnIndex).setMinWidth(0);
			jTable1.getColumnModel().getColumn(columnIndex).setMaxWidth(0);
			jTable1.getColumnModel().getColumn(columnIndex).setPreferredWidth(0);
			jTable1.getColumnModel().getColumn(columnIndex).setWidth(0);
			jTable1.getColumnModel().getColumn(columnIndex).setMinWidth(0);
		}
	}

	/**
	 * 将dialog屏幕居中显示
	 * @author chenyunlong
	 * @date  2013-6-13
	 * @param dialog
	 *
	 */
	public static void setMiddleOnScreenWithDialog(JDialog dialog){
		int windowWidth = dialog.getWidth();                     //获得窗口宽
	    int windowHeight = dialog.getHeight();                   //获得窗口高
	    Toolkit kit = Toolkit.getDefaultToolkit();              //定义工具包
	    Dimension screenSize = kit.getScreenSize();             //获取屏幕的尺寸
	    int screenWidth = screenSize.width;                     //获取屏幕的宽
	    int screenHeight = screenSize.height;                   //获取屏幕的高
	    dialog.setLocation(screenWidth/2-windowWidth/2, screenHeight/2-windowHeight/2);//设置窗口居中显示
	}
}
