package com.glaway.mpm.view;

import com.glaway.mpm.util.XmlUtility;
import com.glaway.mpm.wcIntf.ResourceIntf;
import com.glaway.mpm.wcIntf.TechnicsIntf;
import org.dom4j.Element;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.lang.reflect.InvocationTargetException;
import java.rmi.RemoteException;
import java.util.List;
import java.util.*;

/**
 *
 * 用于复制工艺文件时设置新的工艺文件属性
 *
 * @author LongXiuChuan
 */
public class CopyTechnicsDialog {

	private JDialog dialog;
	private JButton jButton1;
    private JButton jButton2;
    private JComboBox jComboBox1;
    private JComboBox jComboBox2;
    private JComboBox jComboBox3;
    private JComboBox jComboBox4;
    private JComboBox jComboBox5;
    private JComboBox jComboBox6;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel14;
    private JLabel jLabel15;
    private JLabel jLabel16;
    private JLabel jLabel17;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JTextField jTextField1;
    private JTextField jTextField10;
    private JTextField jTextField11;
    private JTextField jTextField2;
    private JTextField jTextField3;
    private JTextField jTextField4;
    private JTextField jTextField5;
    private JTextField jTextField6;
    private JTextField jTextField7;
    private JTextField jTextField8;
    private JTextField jTextField9;

    private String[] pplantype_array = {"正式工艺文件","临时工艺文件"};
	private String[] zfflag_array = {"Z","F"};
	private String[] secret_array = {"公开","内部"};
//	private String[] secret_array = {"公开","内部","秘密★10年","机密★20年"};
	private Vector<String> batchs;
	private List<String> ibaList = new ArrayList<String>();
	private Map<String,String> ibasMap = new HashMap<String,String>();
	private Map<String,String> typesMap = new HashMap<String,String>();
	private Map<String,String> pplanIdMap = new HashMap<String,String>();
	private static final String ID = "Rz";

    private NewTechnicsPart frame;
    private XWTreeNode node;
    private Element techElement;
    private Element partElement;
    private String newTechNumber;
    public Map<String,String> map = new HashMap<String,String>();

	/**
     * Creates new form CopyTechnicsDialog
     */
    public CopyTechnicsDialog(NewTechnicsPart frame, XWTreeNode node,Element techElement,String newTechNumber) {
        super();
        this.frame = frame;
        this.node = node;
        this.techElement = techElement;
        this.newTechNumber = newTechNumber;
        showDialog();
    }

    public void showDialog() {
    	newJDialog();
    	initComponents();
    	loadData();
    }

    /**
	 * 新增对话框jdialog
	 */
	public void newJDialog() {
		dialog = new JDialog();
		dialog.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
		dialog.setTitle("设置工艺文件属性");
		dialog.setSize(600, 720);
		dialog.setVisible(true);
		dialog.setModal(true);
		setMiddleOnScreenWithDialog(dialog);
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jPanel1 = new JPanel();

        //产品型号代号
        jLabel1 = new JLabel();
        jTextField1 = new JTextField();
        jLabel1.setText("产品型号代号：");
		jTextField1.setText(ibasMap.get("MINDEX"));
		jTextField1.setEditable(false);

        //产品代号
        jLabel2 = new JLabel();
        jTextField2 = new JTextField();
        jLabel2.setText("产品代号：");
		jTextField2.setText(ibasMap.get("PINDEX"));
		jTextField2.setEditable(false);

        //设计图样代号
        jLabel3 = new JLabel();
        jTextField3 = new JTextField();
        jTextField3.setEditable(false);

        //设计图样名称
        jLabel4 = new JLabel();
        jTextField4 = new JTextField();
        jTextField4.setEditable(false);

        //关重件标记
        jLabel5 = new JLabel();
        jTextField5 = new JTextField();
        jTextField5.setEditable(false);

        //产品阶段标记
        jLabel6 = new JLabel();
        jTextField6 = new JTextField();
        jTextField6.setEditable(false);

        //部门
        jLabel7 = new JLabel();
        jComboBox1 = new JComboBox();

        //工艺文件类别
        jLabel8 = new JLabel();
        jComboBox2 = new JComboBox();

        //临时工艺顺序号
        jLabel16 = new JLabel();
        jTextField7 = new JTextField();

        //主辅制类别
        jLabel9 = new JLabel();
        jComboBox3 = new JComboBox();

        //工艺文件顺序号
        jLabel17 = new JLabel();
        jTextField8 = new JTextField();

        //工艺类型
        jLabel10 = new JLabel();
        jComboBox4 = new JComboBox();

        //工艺特征编码
        jLabel11 = new JLabel();
        jTextField9 = new JTextField();
        jTextField9.setEditable(false);

        //工艺文件编号
        jLabel12 = new JLabel();
        jTextField10 = new JTextField();
        jTextField10.setEditable(true);

        //工艺文件名称
        jLabel13 = new JLabel();
        jTextField11 = new JTextField();
        jTextField11.setEditable(true);

        //文件密级
        jLabel14 = new JLabel();
        jComboBox5 = new JComboBox();

        //批次号
        jLabel15 = new JLabel();
        jComboBox6 = new JComboBox();

        jPanel2 = new JPanel();

        jButton1 = new JButton();
        jButton2 = new JButton();

        jPanel1.setToolTipText("设置工艺文件属性");

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel17)
                    .addComponent(jLabel9)
                    .addComponent(jLabel16)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4)
                    .addComponent(jTextField5)
                    .addComponent(jTextField6)
                    .addComponent(jComboBox1, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField7)
                    .addComponent(jComboBox3, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField8)
                    .addComponent(jComboBox4, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField9)
                    .addComponent(jTextField10)
                    .addComponent(jTextField11)
                    .addComponent(jComboBox5, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox6, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jTextField11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jComboBox5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jComboBox6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jButton1.setText("确  定");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("取  消");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(dialog.getContentPane());
        dialog.getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SwingUtilities.invokeLater(new Runnable() {
			@Override
			public void run() {
				dialog.setModal(true);
				dialog.setVisible(true);
			}
		});
        //pack();
    }

    private void loadData() {
    	XWPartTreeObject partObject = (XWPartTreeObject)node.getObject();
        partElement = partObject.getTreeCellData();

        String dept = XmlUtility.getAttributeValue(techElement, "DEPT");
        String pplanType = XmlUtility.getAttributeValue(techElement, "PPLANTYPE");
        String technicsType = XmlUtility.getAttributeValue(techElement, "technicsType");
        String zfFlag = XmlUtility.getAttributeValue(techElement, "ZFFLAG");
        String secret = XmlUtility.getAttributeValue(techElement, "SECRET");
        String batch = XmlUtility.getAttributeValue(techElement, "PCNO");
        String techNumber = XmlUtility.getAttributeValue(techElement, "pplanNumber");
        String tempNo = "";
        if("临时工艺文件".equals(pplanType)) {
        	if(techNumber != null && techNumber.endsWith(")")) {
        		tempNo = techNumber.substring(techNumber.lastIndexOf("(")+1, techNumber.lastIndexOf(")"));
            }
        }
        String techFileNo = "";
        if("F".equals(zfFlag)) {
        	if("临时工艺文件".equals(pplanType)) {
        		techFileNo = techNumber.substring(techNumber.lastIndexOf("-")+1, techNumber.lastIndexOf("("));
        	} else {
        		techFileNo = techNumber.substring(techNumber.lastIndexOf("-")+1, techNumber.length());
        	}
        }

		//获取零部件的IBA属性值
		initIBAList();
		if(ibasMap.isEmpty()) {
			try {
				ibasMap = TechnicsIntf.getPartIBAValuesByNumber(XmlUtility.getAttributeValue(partElement, "partNumber"), ibaList);
			} catch (RemoteException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			} catch (InvocationTargetException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
		}

		jLabel3.setText("设计图样代号：");
        jTextField3.setText(XmlUtility.getAttributeValue(partElement, "partNumber"));

        jLabel4.setText("设计图样名称：");
        jTextField4.setText(XmlUtility.getAttributeValue(partElement, "partName"));

        jLabel5.setText("关重件标记：");
        jTextField5.setText(ibasMap.get("KEYCOMPONENT"));

        jLabel6.setText("产品阶段标记：");
        jTextField6.setText(ibasMap.get("PHASE_CODE"));

		//获取到所有的车间组，然后自动定位到当前用户所在的组
        jLabel7.setText("部门：");
		List<String> allList = new ArrayList<String>();
		Map<String,String> workShop = ResourceIntf.getWorkShops();
		if (workShop != null && workShop.size() > 0) {
			Collection<String> coll = workShop.values();
			Iterator<String> it = coll.iterator();
			while (it.hasNext()) {
				String temp = (String) it.next();
				if (temp != null && temp.trim().length() > 0) {
					allList.add(temp);
				}
			}
			Collections.sort(allList);
		}
        jComboBox1.setModel(new DefaultComboBoxModel(allList.toArray()));
        jComboBox1.setSelectedItem(dept);

        jLabel8.setText("工艺文件类别：");
        jComboBox2.setModel(new DefaultComboBoxModel(pplantype_array));
        jComboBox2.setSelectedItem(pplanType);
        jComboBox2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
            	if(jComboBox2.getSelectedItem().toString().equals("临时工艺文件")) {
            		jLabel16.setVisible(true);
            		jTextField7.setVisible(true);

            		jTextField8.setText("");
					jLabel17.setVisible(false);
					jTextField8.setVisible(false);
				} else {
					jLabel16.setVisible(false);
					jTextField7.setVisible(false);

					if(jComboBox3.getSelectedItem().toString().equals("Z")) {
						jLabel17.setVisible(false);
						jTextField8.setVisible(false);
					} else if(jComboBox3.getSelectedItem().toString().equals("F")) {
						jLabel17.setVisible(true);
						jTextField8.setVisible(true);
					}
				}

				String number = ID+"/"+XmlUtility.getAttributeValue(partElement, "partNumber")+jComboBox3.getSelectedItem().toString();
				String pplanidValue = jTextField9.getText();
				String techFileNoValue = jTextField8.getText();
				String tempnoValue = jTextField7.getText();
				String newValue = number+pplanidValue;

				if(jComboBox2.getSelectedItem().toString().equals("正式工艺文件")
						&&jComboBox3.getSelectedItem().toString().equals("F")) {
					if(techFileNoValue!=null && !"".equals(techFileNoValue)) {
						newValue = newValue+"-"+techFileNoValue;
					}
				}

				if(jComboBox2.getSelectedItem().toString().equals("临时工艺文件")) {
					if(tempnoValue!=null && !"".equals(tempnoValue)) {
						newValue = newValue+"("+tempnoValue+")";
					}
				}

				jTextField10.setText(newValue);
            }
        });

        jLabel16.setText("临时工艺顺序号：");
        jTextField7.setText("");
        if("临时工艺文件".equals(pplanType)) {
        	jLabel16.setVisible(true);
        	jTextField7.setVisible(true);
        	if(tempNo != null) {
        		jTextField7.setText(tempNo);
        	}
        } else {
        	jLabel16.setVisible(false);
        	jTextField7.setVisible(false);
        }
        jTextField7.getDocument().addDocumentListener(new DocumentListener() {

			@Override
			public void removeUpdate(DocumentEvent e) {
				String number = ID+"/"+XmlUtility.getAttributeValue(partElement, "partNumber")+jComboBox3.getSelectedItem().toString();
				String pplanidValue = jTextField9.getText();
				String techFileNoValue = jTextField8.getText();
				String tempnoValue = jTextField7.getText();
				String newValue = number+pplanidValue;
				if(techFileNoValue!=null && !"".equals(techFileNoValue)) {
					newValue = newValue+"-"+techFileNoValue;
				}
				if(tempnoValue!=null && !"".equals(tempnoValue)) {
					newValue = newValue+"("+tempnoValue+")";
				}
				jTextField10.setText(newValue);
			}

			@Override
			public void insertUpdate(DocumentEvent e) {
				String number = ID+"/"+XmlUtility.getAttributeValue(partElement, "partNumber")+jComboBox3.getSelectedItem().toString();
				String pplanidValue = jTextField9.getText();
				String techFileNoValue = jTextField8.getText();
				String tempnoValue = jTextField7.getText();
				String newValue = number+pplanidValue;
				if(jComboBox3.getSelectedItem().toString().equals("F")) {
					if(techFileNoValue!=null && !"".equals(techFileNoValue)) {
						newValue = newValue+"-"+techFileNoValue;
					}
				}

				if(tempnoValue!=null && !"".equals(tempnoValue)) {
					newValue = newValue+"("+tempnoValue+")";
				}
				jTextField10.setText(newValue);
			}

			@Override
			public void changedUpdate(DocumentEvent e) {}

		});

        jLabel9.setText("主辅制类别：");
        jComboBox3.setModel(new DefaultComboBoxModel(zfflag_array));
        jComboBox3.setSelectedItem(zfFlag);
        jComboBox3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
            	if(jComboBox3.getSelectedItem().toString().equals("F")) {
            		jLabel17.setVisible(true);
            		jTextField8.setVisible(true);
				} else {
					jLabel17.setVisible(false);
					jTextField8.setVisible(false);
				}

				String number = ID+"/"+XmlUtility.getAttributeValue(partElement, "partNumber")+jComboBox3.getSelectedItem().toString();
				String pplanidValue = jTextField9.getText();
				String techFileNoValue = jTextField8.getText();
				String tempnoValue = jTextField7.getText();
				String newValue = number+pplanidValue;

				if(jComboBox3.getSelectedItem().toString().equals("F")) {
					if(techFileNoValue!=null && !"".equals(techFileNoValue)) {
						newValue = newValue+"-"+techFileNoValue;
					}
				}

				if(jComboBox2.getSelectedItem().toString().equals("临时工艺文件")) {
					if(tempnoValue!=null && !"".equals(tempnoValue)) {
						newValue = newValue+"("+tempnoValue+")";
					}
				}

				jTextField10.setText(newValue);
            }
        });

        //获取工艺规程的所有子类型
      	try {
			typesMap = TechnicsIntf.getMPMPPlanSubTypes();
		} catch (RemoteException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		} catch (InvocationTargetException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
      	try {
			pplanIdMap = TechnicsIntf.getPPlanID();
		} catch (RemoteException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		} catch (InvocationTargetException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
        jLabel10.setText("工艺类型：");
        jComboBox4.setModel(new DefaultComboBoxModel(typesMap.values().toArray()));
        jComboBox4.setSelectedItem(technicsType);
        jComboBox4.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
				//设置工艺特征编码
            	jTextField9.setText(pplanIdMap.get(jComboBox4.getSelectedItem().toString()));

				//计算并设置工艺文件编号
				String number = ID+"/"+XmlUtility.getAttributeValue(partElement, "partNumber")
						+jComboBox3.getSelectedItem().toString()+pplanIdMap.get(jComboBox4.getSelectedItem().toString());
				String techFileNoValue = jTextField8.getText();
				String tempnoValue = jTextField7.getText();
				String newValue = number;
				if(techFileNoValue!=null && !"".equals(techFileNoValue)) {
					newValue = newValue+"-"+techFileNoValue;
				}
				if(tempnoValue!=null && !"".equals(tempnoValue)) {
					newValue = newValue+"("+tempnoValue+")";
				}
				jTextField10.setText(newValue);
				jTextField11.setText(jComboBox4.getSelectedItem().toString()+"规程");
            }
        });

        jLabel11.setText("工艺特征编码：");
        jTextField9.setText(pplanIdMap.get(jComboBox4.getSelectedItem().toString()));

        jLabel17.setText("工艺文件顺序号");
        jTextField8.setText("");
        if("F".equals(zfFlag)) {
        	jLabel17.setVisible(true);
        	jTextField8.setVisible(true);
        	if(techFileNo != null) {
        		jTextField8.setText(techFileNo);
        	}
        } else {
        	jLabel17.setVisible(false);
        	jTextField8.setVisible(false);
        }
        jTextField8.getDocument().addDocumentListener(new DocumentListener() {

			@Override
			public void removeUpdate(DocumentEvent e) {
				String number = ID+"/"+XmlUtility.getAttributeValue(partElement, "partNumber")+jComboBox3.getSelectedItem().toString();
				String tempnoValue = jTextField7.getText();
				String technicsFileNoValue = jTextField8.getText();
				String pplanidValue = jTextField9.getText();
				String newNumber = number+pplanidValue;
				if(technicsFileNoValue != null && !"".equals(technicsFileNoValue)) {
					newNumber = newNumber+"-"+technicsFileNoValue;
				}
				if(tempnoValue != null && !"".equals(tempnoValue)) {
					newNumber = newNumber + "(" + tempnoValue + ")";
				}
				jTextField10.setText(newNumber);
			}

			@Override
			public void insertUpdate(DocumentEvent e) {
				String number = ID+"/"+XmlUtility.getAttributeValue(partElement, "partNumber")+jComboBox3.getSelectedItem().toString();
				String tempnoValue = jTextField7.getText();
				String technicsFileNoValue = jTextField8.getText();
				String pplanidValue = jTextField9.getText();
				String newNumber = number+pplanidValue;
				if(technicsFileNoValue != null && !"".equals(technicsFileNoValue)) {
					newNumber = newNumber+"-"+technicsFileNoValue;
				}
				if(jComboBox2.getSelectedItem().toString().equals("临时工艺文件")) {
					if(tempnoValue != null && !"".equals(tempnoValue)) {
						newNumber = newNumber + "(" + tempnoValue + ")";
					}
				}

				jTextField10.setText(newNumber);
			}

			@Override
			public void changedUpdate(DocumentEvent e) {}

		});

        jLabel12.setText("工艺文件编号：");
        String numner = ID+"/"+XmlUtility.getAttributeValue(partElement, "partNumber")
        		+jComboBox3.getSelectedItem().toString()+pplanIdMap.get(jComboBox4.getSelectedItem().toString());
        String tempnoValue = jTextField7.getText();
        String technicsFileNoValue = jTextField8.getText();
        if(technicsFileNoValue != null && !"".equals(technicsFileNoValue)) {
        	numner = numner+"-"+technicsFileNoValue;
		}
		if(jComboBox2.getSelectedItem().toString().equals("临时工艺文件")) {
			if(tempnoValue != null && !"".equals(tempnoValue)) {
				numner = numner + "(" + tempnoValue + ")";
			}
		}
        jTextField10.setText(numner);

        jLabel13.setText("工艺文件名称：");
        jTextField11.setText(jComboBox4.getSelectedItem().toString()+"规程");

        jLabel14.setText("文件密级：");
        jComboBox5.setModel(new DefaultComboBoxModel(secret_array));
        if(secret != null) {
        	jComboBox5.setSelectedItem(secret);
        }

		//获取当前产品的批次号
        jLabel15.setText("批次号：");
		if(batchs == null) {
			long oid = Long.valueOf(XmlUtility.getAttributeValue(partElement, "containerId"));
			try {
				batchs = TechnicsIntf.getBatchsByProductOid(oid);
			} catch (RemoteException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			} catch (InvocationTargetException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			if(batchs == null) {
				batchs = new Vector<String>();
				batchs.add("");
			}
		}
        jComboBox6.setModel(new DefaultComboBoxModel(batchs));
        if(batch != null && batchs.contains(batch)) {
        	jComboBox6.setSelectedItem(batch);
        }

    }

    private void jButton1ActionPerformed(ActionEvent evt) {
    	String pplanNumber = jTextField10.getText();
    	if(pplanNumber==null||"".equals(pplanNumber.trim())){
			  JOptionPane.showMessageDialog(frame, "工艺文件编号不能为空！", "提示",JOptionPane.INFORMATION_MESSAGE);
			  return ;
		}
    	map.put("pplanNumber", pplanNumber);

    	String pplanName = jTextField11.getText();
    	if(pplanName==null||"".equals(pplanName.trim() )){
			JOptionPane.showMessageDialog(frame, "工艺文件名称不能为空！", "提示",JOptionPane.INFORMATION_MESSAGE);
			return ;
		}

    	if(checkNumber(pplanNumber)){
			JOptionPane.showMessageDialog(frame, "编号为【"+pplanNumber+"】的工艺文件已经存在！", "提示",JOptionPane.INFORMATION_MESSAGE);
			return ;
		}

    	if("Z".equals(String.valueOf(jComboBox3.getSelectedItem()))
				&& "正式工艺文件".equals(String.valueOf(jComboBox2.getSelectedItem()))) {
			if(checkZhuZhi()) {
				JOptionPane.showMessageDialog(frame, "正式主工艺文件已经存在,一个零部件下只能有一份正式主工艺！", "提示",JOptionPane.INFORMATION_MESSAGE);
				return ;
			}
		}


    	map.put("pplanName", pplanName);
    	map.put("technicsName", jComboBox4.getSelectedItem().toString()+"("+jTextField10.getText()+")");
    	map.put("DEPT", jComboBox1.getSelectedItem().toString());
    	map.put("PPLANTYPE", jComboBox2.getSelectedItem().toString());
    	map.put("ZFFLAG", jComboBox3.getSelectedItem().toString());
    	map.put("SECRET", jComboBox5.getSelectedItem().toString());
    	map.put("PCNO", jComboBox6.getSelectedItem().toString());
    	map.put("technicsType", jComboBox4.getSelectedItem().toString());
    	map.put("PPLANID", jTextField9.getText());

    	map.put("createTime", XmlUtility.getCurrentTime());
    	map.put("modifyTime", XmlUtility.getCurrentTime());

    	map.put("tempNo", jTextField7.getText());
    	map.put("MINDEX", jTextField1.getText());
    	map.put("PINDEX", jTextField2.getText());
    	map.put("KEYCOMPONENT", jTextField5.getText());
    	map.put("PHASE_CODE", jTextField6.getText());

    	dialog.setVisible(false);
    	try {
			frame.pastTechnicsAndModifyAttri(newTechNumber, map, partElement);
		} catch (Exception e) {
			e.printStackTrace();
		}
    }

    private void jButton2ActionPerformed(ActionEvent evt) {
    	dialog.setVisible(false);
    }

	private boolean checkNumber(String newNumber) {
		Enumeration childs = frame.xwPartTreePanel.getSelectedTreeNode().children();
		if(childs != null) {
			while(childs.hasMoreElements()) {
				Object obj = childs.nextElement();
				if(obj instanceof XWTreeNode) {
					XWTreeNode techObj = (XWTreeNode) obj;
					XWTreeObject treeObj = techObj.getObject();
					if(treeObj instanceof TechnicsMessageTreeObject) {
						TechnicsMessageTreeObject tmo = (TechnicsMessageTreeObject) treeObj;
						String number = tmo.getPplanNumber();
						if(newNumber.equals(number)) {
							return true;
						}
					}
				}
			}
		}
		return false;
	}

	private boolean checkZhuZhi() {
		Enumeration childs = frame.xwPartTreePanel.getSelectedTreeNode().children();
		if(childs != null) {
			while(childs.hasMoreElements()) {
				Object obj = childs.nextElement();
				if(obj instanceof XWTreeNode) {
					XWTreeNode techObj = (XWTreeNode) obj;
					XWTreeObject treeObj = techObj.getObject();
					if(treeObj instanceof TechnicsMessageTreeObject) {
						TechnicsMessageTreeObject tmo = (TechnicsMessageTreeObject) treeObj;
						String isZhuZhi = tmo.getisZhuZhi();
						String pplantype = tmo.getPplantype();
						Element techElement =tmo.getTreeCellData();
						String lifecycle = techElement.attributeValue("lifecycle");
						if("已作废".equals(lifecycle)){
							continue;
						}
						if("Z".equals(isZhuZhi)&&"正式工艺文件".equals(pplantype)) {
							return true;
						}
					}
				}
			}
		}
		return false;
	}

	/**
	 * 将dialog屏幕居中显示
	 * @author chenyunlong
	 * @date  2013-6-13
	 * @param dialog
	 *
	 */
	public static void setMiddleOnScreenWithDialog(JDialog dialog){
		int windowWidth = dialog.getWidth();                     //获得窗口宽
	    int windowHeight = dialog.getHeight();                   //获得窗口高
	    Toolkit kit = Toolkit.getDefaultToolkit();              //定义工具包
	    Dimension screenSize = kit.getScreenSize();             //获取屏幕的尺寸
	    int screenWidth = screenSize.width;                     //获取屏幕的宽
	    int screenHeight = screenSize.height;                   //获取屏幕的高
	    dialog.setLocation(screenWidth/2-windowWidth/2, screenHeight/2-windowHeight/2);//设置窗口居中显示
	}

	public void initIBAList(){
		ibaList.add("PHASE_CODE");
		ibaList.add("MINDEX");
		ibaList.add("PINDEX");
		ibaList.add("KEYCOMPONENT");
	}
}

