package com.glaway.mpm.view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.lang.reflect.InvocationTargetException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Vector;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

import org.dom4j.Element;

import com.glaway.mpm.util.XmlUtility;
import com.glaway.mpm.wcIntf.TechnicsIntf;


/**
 * 显示PBOM的批次信息
 *
 * @author LongXiuChuan
 */
public class ShowPbomBatchsDialog {

    private JButton jButton1;
    private JButton jButton2;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JScrollPane jScrollPane1;
    private JTable jTable1;
    private JDialog dialog;
    private NewTechnicsPart frame;
    private XWTreeNode node;
    private String currentBatch;

	/**
     * Creates new form ShowPbomBatchsDialog
     */
    public ShowPbomBatchsDialog(NewTechnicsPart frame, XWTreeNode node) {
        super();
        this.frame = frame;
        this.node = node;
        showDialog();
    }

    public void showDialog() {
    	newJDialog();
    	initComponents();
    	loadData();
    }

    /**
	 * 新增对话框jdialog
	 */
	public void newJDialog() {
		dialog = new JDialog();
		dialog.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
		dialog.setTitle("PBOM批次信息");
		dialog.setSize(665, 400);
		dialog.setVisible(true);
		dialog.setModal(true);
		setMiddleOnScreenWithDialog(dialog);
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new JPanel();
        jScrollPane1 = new JScrollPane();
        jTable1 = new JTable();
        jPanel2 = new JPanel();
        jButton1 = new JButton();
        jButton2 = new JButton();

        jTable1.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "序号", "批次", "版本", "状态", "OID"
            }
        ) {
			private static final long serialVersionUID = 1L;
			Class[] types = new Class [] {
                String.class, String.class, String.class, String.class, String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionBackground(new Color(51, 204, 255));
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(5);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setResizable(false);
        jTable1.getColumnModel().getColumn(4).setResizable(false);

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 313, GroupLayout.PREFERRED_SIZE)
        );

        jButton1.setText("确定");
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("取消");
        jButton2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(41, 41, 41)
                .addComponent(jButton2)
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
        );

        GroupLayout layout = new GroupLayout(dialog.getContentPane());
        dialog.getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SwingUtilities.invokeLater(new Runnable() {
			@Override
			public void run() {
				dialog.setModal(true);
				dialog.setVisible(true);
			}
		});
    }

    private void loadData() {
    	if (node != null) {
			XWTreeObject xo = node.getObject();
			if ((xo instanceof XWPartTreeObject)) {
				Element ele = xo.getTreeCellData();
				String partNumber = XmlUtility.getAttributeValue(ele, "partNumber");
				dialog.setTitle("批次信息("+partNumber+")");
				currentBatch = XmlUtility.getAttributeValue(ele, "BATCH");
				List<List<String>> list = new ArrayList<List<String>>();
				try {
					list = TechnicsIntf.getPbomBatchsByPartNumber(partNumber);
				} catch (RemoteException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (InvocationTargetException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				Collections.reverse(list);
				setTableValues(list);
			}
    	}
    }

    private void setTableValues(List<List<String>> list) {
    	DefaultTableModel tableModel = (DefaultTableModel)jTable1.getModel();
    	for (int n=0;n<list.size();n++) {
    		Vector vector = new Vector();
			for (int j = 0; j < jTable1.getColumnCount(); j++) {
				vector.add("");
			}
			List<String> blist = list.get(n);
			tableModel.addRow(vector);
			tableModel.setValueAt(n+1, n, 0);
			tableModel.setValueAt(blist.get(0), n, 1);
			tableModel.setValueAt(blist.get(1), n, 2);
			tableModel.setValueAt(blist.get(2), n, 3);
			tableModel.setValueAt(blist.get(3), n, 4);
		}
    }

    private void jButton2ActionPerformed(ActionEvent evt) {
    	dialog.setVisible(false);
    }

    private void jButton1ActionPerformed(ActionEvent evt) {
    	int row = jTable1.getSelectedRow();
    	String pbomOid = String.valueOf(jTable1.getValueAt(row, 4));
    	String batch = String.valueOf(jTable1.getValueAt(row, 1));
    	try {
    		if(batch == null || "".equals(batch)) {
    			JOptionPane.showMessageDialog(dialog, "批次为空，不能进行切换！");
    		} else if(batch.equals(currentBatch)) {
    			JOptionPane.showMessageDialog(dialog, "请选择与当前批次(" + currentBatch +")不同的批次！");
    		} else {
    			int option = JOptionPane.showConfirmDialog(dialog, "是否确认切换PBOM批次到："+batch +" ？", "提示", JOptionPane.OK_CANCEL_OPTION);
        		if(option == 0) {
        			if(pbomOid != null && !"".equals(pbomOid)) {
        				frame.resetPbomBatch(pbomOid);
        				JOptionPane.showMessageDialog(dialog, "PBOM已经切换到批次：" + batch);
        			} else {
        				JOptionPane.showMessageDialog(dialog, "PBOM切换到失败，请联系管理员！");
        			}
        		}
    		}
		} catch (Exception e) {
			JOptionPane.showMessageDialog(dialog, "PBOM切换到失败，请联系管理员！\r\n" + e.getLocalizedMessage());
			//e.printStackTrace();
		}
    	dialog.setVisible(false);
    }

	/**
	 * 将dialog屏幕居中显示
	 * @author chenyunlong
	 * @date  2013-6-13
	 * @param dialog
	 *
	 */
	public static void setMiddleOnScreenWithDialog(JDialog dialog){
		int windowWidth = dialog.getWidth();                     //获得窗口宽
	    int windowHeight = dialog.getHeight();                   //获得窗口高
	    Toolkit kit = Toolkit.getDefaultToolkit();              //定义工具包
	    Dimension screenSize = kit.getScreenSize();             //获取屏幕的尺寸
	    int screenWidth = screenSize.width;                     //获取屏幕的宽
	    int screenHeight = screenSize.height;                   //获取屏幕的高
	    dialog.setLocation(screenWidth/2-windowWidth/2, screenHeight/2-windowHeight/2);//设置窗口居中显示
	}
}
