package com.glaway.mpm.view;

import java.util.List;
import java.util.Map;
import java.util.Vector;

import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

import com.glaway.mpm.sop.util.SopPbomUtil;
import org.dom4j.Element;

import com.glaway.mpm.sjzyk.LoadDesignAttributes;

public class ShowMaterialsJPanel extends JPanel {

	private static final long serialVersionUID = 1L;
	private JScrollPane jScrollPane1;
    private JTable jTable1;
    private NewTechnicsPart frame;

	/**
     * Creates new form ShowMaterialsJPanel
     */
    public ShowMaterialsJPanel(NewTechnicsPart frame) {
    	this.frame = frame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        jScrollPane1 = new JScrollPane();
        jTable1 = new JTable();

        jScrollPane1.setBorder(BorderFactory.createTitledBorder("材料信息"));

        jTable1.setModel(new DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "c1", "c2", "c3", "c4", "c5", "c6"
            }
        ) {
			private static final long serialVersionUID = 1L;
			Class[] types = new Class [] {
                String.class, String.class, String.class, String.class, String.class, String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });

        jTable1.setColumnSelectionAllowed(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.getTableHeader().setVisible(false);
        jTable1.setEnabled(false);
        jTable1.setShowGrid(false);
        jTable1.setBackground(getBackground());//new Color(236,233,216)
        jTable1.setFont(this.getFont());//new Font(getFont().getName(), getFont().getStyle(), 14)
        jTable1.setRowHeight(30);
        jTable1.setRowMargin(15);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setResizable(false);
        jTable1.getColumnModel().getColumn(4).setResizable(false);
        jTable1.getColumnModel().getColumn(5).setResizable(false);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
        );
    }

    public void setValues(Element partElement, boolean flag, boolean isSop) {
    	DefaultTableModel tableModel = (DefaultTableModel)jTable1.getModel();
    	tableModel.setRowCount(0);
    	String mtype = partElement.attributeValue("MTYPE");
    	List<Map<String,String>> list = frame.getAttriMap().get(mtype);
		if(isSop){
			list.clear();
			setTitle("SOP体系BOM信息");
			list = SopPbomUtil.getPartInfo(partElement);
			loadData(list, partElement, tableModel);
		}else{
			if ("标准件".equals(mtype)) {
				setTitle("标准件材料信息");
				//map = LoadMaterialsConfig.getInstance().getAttributes("BZJ_");
			} else if ("元器件".equals(mtype)) {
				setTitle("元器件材料信息");
				//map = LoadMaterialsConfig.getInstance().getAttributes("YQJ_");
			} else if ("自制件".equals(mtype)) {
				setTitle("自制件材料信息");
				//map = LoadMaterialsConfig.getInstance().getAttributes("DEFAULT_");
			}

			if (list != null && flag) {
				loadData(list, partElement, tableModel);
			} else {
				setTitle("设计属性信息");
				list = LoadDesignAttributes.getInstance().getAllDesignAttr();
				loadData(list, partElement, tableModel);
			}

		}

    }

    private void loadData(List<Map<String,String>> list, Element partElement, DefaultTableModel tableModel) {
    	String name = "";
    	String displayName = "";

    	if(list != null && !list.isEmpty()) {
    		int index = 0;
    		for (Map<String, String> map : list) {
    			name = String.valueOf(map.keySet().toArray()[0]);
    			if(name == null || "".equals(name) || "null".equals(name)){
    				continue;
				}
        		displayName = map.get(name);

        		if((index == 6) || (jTable1.getRowCount() == 0)) {
        			//新增一行
            		Vector<String> vector = new Vector<String>();
            		for (int i = 0; i < tableModel.getColumnCount(); i++) {
            			vector.add("");
            		}
            		tableModel.addRow(vector);
            		index = 0;
        		}

        		tableModel.setValueAt(displayName+":", jTable1.getRowCount()-1, index++);
        		tableModel.setValueAt(partElement.attributeValue(name), jTable1.getRowCount()-1, index++);
			}
    	}

    	setDuiqi();
    }

    public void setTitle(String title) {
    	jScrollPane1.setBorder(BorderFactory.createTitledBorder(title));
    }

    //设置JTable表格单元格对齐的效果
  	public void setDuiqi() {
  		DefaultTableCellRenderer right = new DefaultTableCellRenderer();
  		right.setHorizontalAlignment(JLabel.RIGHT);
  		right.setBackground(getBackground());//new Color(236,233,216)

  		DefaultTableCellRenderer left = new DefaultTableCellRenderer();
  		left.setHorizontalAlignment(JLabel.LEFT);
  		left.setBackground(getBackground());//new Color(236,233,216)

		for(int i = 0; i< jTable1.getColumnCount();i++) {
			TableColumn col = jTable1.getColumn(jTable1.getColumnName(i));
			if(i%2==0){
				col.setCellRenderer(right);
			} else {
				col.setCellRenderer(left);
			}
			this.setSize(getWidth(), 50);
		}
  	}

}
