package com.glaway.mpm.view;

import com.glaway.mpm.pdf.HtmlGenerator;
import com.glaway.mpm.util.CommonUtil;
import com.glaway.mpm.util.SwitchUtil;
import com.glaway.mpm.util.WorkSpaceUtil;
import com.glaway.mpm.util.XmlUtility;
import com.glaway.speciaword.common.CommonHelper;
import org.dom4j.Document;
import org.dom4j.Element;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.*;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.io.File;

public class TechnicsDescribeJPanel extends JPanel {
	private String imageFolder;
	private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
   // private javax.swing.JTextArea jTextArea1;
	private NewTechnicsPart parentPanel;
	private SpecialWordPanel speCharPanel;
	 /**
     * Creates new form TechnicsDescribeJPanel
     */
    public TechnicsDescribeJPanel(NewTechnicsPart parentPanel) {
    	this.parentPanel = parentPanel;
        initComponents();
        setName("TechnicsDescribe");
        initUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        //jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        speCharPanel = new SpecialWordPanel(parentPanel, true, null);
        int width = Toolkit.getDefaultToolkit().getScreenSize().width;
		int height = Toolkit.getDefaultToolkit().getScreenSize().height;
//        speCharPanel.setMaximumSize(new Dimension(200, 38));
//		speCharPanel.setMinimumSize(new Dimension(200, 38));
		speCharPanel.setPreferredSize(new Dimension((int)(width*0.4), (int)(height*0.3)));
		speCharPanel.setBorder(BorderFactory.createEmptyBorder(1, 1, 1, 1));


        //jTextArea1.setColumns(20);
        //jTextArea1.setRows(5);
        //jScrollPane1.setViewportView(jTextArea1);
        jScrollPane1.setViewportView(speCharPanel);
        /*jButton1.setText("保 存");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });*/

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, (int)(width*0.4)+80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    /*.addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jButton1))*/
                        )
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, (int)(height*0.3)+50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                //.addComponent(jButton1)
                .addContainerGap(34, Short.MAX_VALUE))
        );


        speCharPanel.addFocusListener(new FocusListener()// 工具
		{
			public void focusGained(FocusEvent arg0) {
				if (parentPanel != null && parentPanel instanceof NewTechnicsPart) {
					NewTechnicsPart tp = (NewTechnicsPart) parentPanel;
					tp.getCSTreePanel().deleteObservers();
					tp.getCSTreePanel().addObserver(speCharPanel);
					tp.getLeftTab().setSelectedComponent(tp.getCSTreePanel());
				}
			}

			public void focusLost(FocusEvent arg0) {

			}
		});
        speCharPanel.getSpeciaWordComponent().getDocument()
		.addDocumentListener(new DocumentListener() {

			@Override
			public void removeUpdate(DocumentEvent e) {
				saveDescription();
			}

			@Override
			public void insertUpdate(DocumentEvent e) {
				saveDescription();
			}

			@Override
			public void changedUpdate(DocumentEvent e) {
				saveDescription();
			}
		});
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    	Document document = parentPanel.getCurrentTechnics();
    	Element techElement = XmlUtility.getTechnicsElement(document);
    	String techPath = WorkSpaceUtil.getTechnicsDirectory(techElement.attributeValue("technicsNumber"));
		String xmlFilePath = techPath + File.separator + techElement.attributeValue("technicsNumber")+".xml";
		System.out.println("---------xmlFilePath-----"+xmlFilePath);
	    System.out.println("============================>>>>"+speCharPanel.getTechnicsPath());
		// 特殊符号
		if (document == null)
			return;
		Element techEle = XmlUtility.getTechnicsElement(document);
		imageFolder = WorkSpaceUtil.getTechnicsPath(techEle);

		String comment1 =   speCharPanel.getText().replaceAll(CommonUtil.SPECIAL_SPACE, " ");
		comment1 = SwitchUtil.filterSpecialChar(comment1);
		comment1 = HtmlGenerator.removeImageTags(comment1);
		comment1 = CommonHelper.replaceSaveSeperator(comment1,imageFolder);
		XmlUtility.setTechnicsDescribe(techElement, comment1);

		try {
			XmlUtility.saveDocument(techElement.getDocument(), xmlFilePath);
			JOptionPane.showMessageDialog(this.parentPanel, "工艺说明保存成功！");
		} catch (Exception e1) {
			JOptionPane.showMessageDialog(this.parentPanel, "工艺说明保存失败！");
			e1.printStackTrace();
		}
    }
    private void saveDescription() {
    	Document document = parentPanel.getCurrentTechnics();
    	Element techElement = XmlUtility.getTechnicsElement(document);
    	String techPath = WorkSpaceUtil.getTechnicsDirectory(techElement.attributeValue("technicsNumber"));
		String xmlFilePath = techPath + File.separator + techElement.attributeValue("technicsNumber")+".xml";
		System.out.println("---------xmlFilePath-----"+xmlFilePath);
	    System.out.println("============================>>>>"+speCharPanel.getTechnicsPath());
		// 特殊符号
		if (document == null)
			return;
		Element techEle = XmlUtility.getTechnicsElement(document);
		imageFolder = WorkSpaceUtil.getTechnicsPath(techEle);

		String comment1 =   speCharPanel.getText().replaceAll(CommonUtil.SPECIAL_SPACE, " ");
		comment1 = SwitchUtil.filterSpecialChar(comment1);
		comment1 = HtmlGenerator.removeImageTags(comment1);
		comment1 = CommonHelper.replaceSaveSeperator(comment1,imageFolder);
		XmlUtility.setTechnicsDescribe(techElement, comment1);

		try {
			XmlUtility.saveDocument(techElement.getDocument(), xmlFilePath);
		} catch (Exception e1) {
			JOptionPane.showMessageDialog(this.parentPanel, "工艺说明保存失败！");
			e1.printStackTrace();
		}
    }
    private void initUI() {
    }
    public void setContent(String content) {
    	// 特殊符号
    			Document document = this.parentPanel.getCurrentTechnics();
    			if (document == null)
    				return;
    			Element techEle = XmlUtility.getTechnicsElement(document);

    			imageFolder = WorkSpaceUtil.getTechnicsPath(techEle);
    			speCharPanel.setTechnicsPath(imageFolder);
//    			content = content.replace("@#$", "\n");
    			speCharPanel.setText(CommonHelper.replaceReadSeperator(content,imageFolder));
    }

    public void setUIEnabled(boolean flag) {
    	jButton1.setEnabled(flag);
    	speCharPanel.setEnabled(flag);
    }
}
