package com.glaway.mpm.view;

import com.glaway.mpm.model.TechnicsStateTableBean;
import com.glaway.mpm.util.FileChooserTool;
import com.glaway.mpm.util.WorkSpaceUtil;
import com.glaway.mpm.wcIntf.ResourceIntf;
import com.glaway.speciaword.common.CommonHelper;
import org.dom4j.Element;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.*;
import java.util.List;

/**
 *
 * @author glaway
 */
public class UpdateTechnicsStateItemJDialog {

	private JButton chooseButton;
	private JButton sureButton;
	private JButton cancelButton;
	private JComboBox makeDeptComboBox;
	private JComboBox useDeptComboBox;
	private JLabel makeDeptLabel;
	private JLabel useDeptLabel;
	private JLabel technicsStateLabel;
	private JLabel insertImgLabel;
	private JLabel jLabel5;
	private JPanel mainPanel;
	private JPanel jPanel2;
	private JPanel jPanel3;
	private JPanel previewPanel;
	private JTextField insertImgTextField;
	private JPanel p;

	private JDialog dialog;
    private Container frame;
    private TechnicsStateTableJPanel parentPanel;
    private int flag;//0表示新建，1表示编辑
    private String oldPath;
    private SpecialWordPanel speCharPanel = null;
    private String path;
    private Element currentTech;

	/**
	 * Creates new form AddTechnicsStateItemJDialog
	 */
	public UpdateTechnicsStateItemJDialog(Container frame, TechnicsStateTableJPanel parentPanel,int flag,Element currentTech) {
		super();
		this.frame = frame;
		this.parentPanel = parentPanel;
		this.flag = flag;
		this.currentTech = currentTech;
		speCharPanel = new SpecialWordPanel((JFrame)frame, true, WorkSpaceUtil.getTechnicsPath(currentTech));
		showDialog();
	}

    public void showDialog() {
		speCharPanel.setTechnicsPath(WorkSpaceUtil.getTechnicsPath(currentTech));
    	newJDialog();
    	initComponents();
    	if(this.flag == 1) {
    		loadDatas();
    	}
    }

    /**
	 * 新增对话框jdialog
	 */
	public void newJDialog() {
		dialog = new JDialog();
		dialog.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
		dialog.setTitle("修改工艺状态表");
//		dialog.setSize(534, 568);
		dialog.setSize(534, 600);
		dialog.setResizable(true);
		dialog.setVisible(true);
		dialog.setModal(true);
		setMiddleOnScreenWithDialog(dialog);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	private void initComponents() {

		mainPanel = new JPanel();
		jPanel2 = new JPanel();
		makeDeptLabel = new JLabel();
		makeDeptComboBox = new JComboBox();
		useDeptLabel = new JLabel();
		useDeptComboBox = new JComboBox();
		technicsStateLabel = new JLabel();
		insertImgLabel = new JLabel();
		insertImgTextField = new JTextField();
		chooseButton = new JButton();
		previewPanel = new JPanel();
		jLabel5 = new JLabel();
		jPanel3 = new JPanel();
		sureButton = new JButton();
		cancelButton = new JButton();
		p = new JPanel();

		//获取到所有的车间组，然后自动定位到当前用户所在的组
		List<String> allList = new ArrayList<String>();
		Map<String,String> workShop = ResourceIntf.getWorkShops();
		if (workShop != null && workShop.size() > 0) {
			Collection<String> coll = workShop.values();
			Iterator<String> it = coll.iterator();
			while (it.hasNext()) {
				String temp = (String) it.next();
				if (temp != null && temp.trim().length() > 0) {
					allList.add(temp);

				}
			}

			Collections.sort(allList);
		}

		makeDeptLabel.setText("制造部门：");
		makeDeptComboBox.setModel(new DefaultComboBoxModel(allList.toArray()));

		useDeptLabel.setText("使用部门：");
		useDeptComboBox.setModel(new DefaultComboBoxModel(allList.toArray()));

		technicsStateLabel.setText("工艺状态：");

		insertImgLabel.setText("插入图片：");
		insertImgTextField.setText("");
		insertImgTextField.setEditable(false);
		chooseButton.setText("选择");
		chooseButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				chooseButtonActionPerformed(evt);
			}
		});

		previewPanel.setBorder(BorderFactory.createTitledBorder("预览"));

		previewPanel.add(jLabel5);
		previewPanel.setSize(467, 266);

        sureButton.setText("确定");
        sureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sureButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("取消");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

		mainPanel.setLayout(new GridBagLayout());

		GridBagConstraints g = new GridBagConstraints();
		g.gridy = 0;
		g.gridx = 0;
		g.gridwidth=1;
		g.anchor = GridBagConstraints.EAST;
		g.insets = new Insets(10, 25, 10, 5);
		mainPanel.add(makeDeptLabel, g);
		g.gridx = 1;
		g.gridwidth=2;
		g.weightx = 0;
		g.weighty=0;
		g.anchor = GridBagConstraints.WEST;
		g.insets = new Insets(10, 5, 10, 25);
		mainPanel.add(makeDeptComboBox, g);

		g = new GridBagConstraints();
		g.gridy = 1;
		g.gridx = 0;
		g.gridwidth=1;
		g.anchor = GridBagConstraints.EAST;
		g.insets = new Insets(10, 25, 10, 5);
		mainPanel.add(useDeptLabel, g);
		g.gridx = 1;
		g.gridwidth=2;
		g.weightx = 0;
		g.weighty=0;
		g.anchor = GridBagConstraints.WEST;
		g.insets = new Insets(10, 5, 10, 25);
		mainPanel.add(useDeptComboBox, g);

		g = new GridBagConstraints();
		g.fill=GridBagConstraints.BOTH;
		g.gridy = 2;
		g.gridx = 0;
		g.gridwidth=1;
		g.anchor = GridBagConstraints.EAST;
		g.weightx = 0;
		g.weighty=0;
		g.insets = new Insets(10, 25, 10, 5);
		mainPanel.add(technicsStateLabel, g);
		g.gridx = 1;
		g.gridwidth=2;
		g.weightx = 1;
		g.weighty=1;
		g.anchor = GridBagConstraints.WEST;
		g.insets = new Insets(10, 5, 10, 25);
		mainPanel.add(speCharPanel, g);

		g = new GridBagConstraints();
		g.fill=GridBagConstraints.BOTH;
		g.gridy = 3;
		g.gridx = 0;
		g.gridwidth=1;
		g.weightx = 0;
		g.weighty=0;
		g.anchor = GridBagConstraints.EAST;
		g.insets = new Insets(10, 25, 10, 5);
		mainPanel.add(insertImgLabel, g);
		g.gridx = 1;
		g.gridwidth=1;
		g.weightx = 1;
		g.anchor = GridBagConstraints.CENTER;
		g.insets = new Insets(10, 5, 10, 5);
		mainPanel.add(insertImgTextField, g);
		g.gridx = 2;
		g.gridwidth=1;
		g.weightx = 0;
		g.anchor = GridBagConstraints.WEST;
		g.insets = new Insets(10, 5, 10, 25);
		mainPanel.add(chooseButton, g);

		g = new GridBagConstraints();
		g.fill=GridBagConstraints.BOTH;
		g.gridy = 4;
		g.gridx = 0;
		g.gridwidth = 3;
		g.weightx=1;
		g.weighty=1;
		g.anchor = GridBagConstraints.CENTER;
		g.insets = new Insets(10, 25, 10, 25);
		mainPanel.add(previewPanel, g);

		g = new GridBagConstraints();
		g.gridy = 5;
		g.gridx = 1;
		g.gridwidth=1;
		g.weighty=0;
		g.weightx=0;
		g.anchor = GridBagConstraints.EAST;
		g.insets = new Insets(10, 25, 10, 5);
		mainPanel.add(sureButton, g);
		g.gridx = 2;
		g.gridwidth=1;
		g.weighty=0;
		g.weightx=0;
		g.anchor = GridBagConstraints.WEST;
		g.insets = new Insets(10, 5, 10, 25);
		mainPanel.add(cancelButton, g);

		dialog.add(mainPanel);


		SwingUtilities.invokeLater(new Runnable() {
			@Override
			public void run() {
				dialog.setModal(true);
				dialog.setVisible(true);
			}
		});
	}

	private void loadDatas() {
		int row = this.parentPanel.table.getSelectedRow();
		makeDeptComboBox.setSelectedItem((String) this.parentPanel.table.getValueAt(row, 1));
		useDeptComboBox.setSelectedItem((String) this.parentPanel.table.getValueAt(row, 2));
		String text = (String) this.parentPanel.table.getValueAt(row, 3);
		if(text != null) {
			text = CommonHelper.replaceReadSeperator(text, WorkSpaceUtil.getTechnicsPath(currentTech));
		}
		speCharPanel.setText(text);
		insertImgTextField.setText((String) this.parentPanel.table.getValueAt(row, 4));
		oldPath = (String) this.parentPanel.table.getValueAt(row, 4);

		String techNumber = currentTech.attributeValue("technicsNumber");

		String techDir = WorkSpaceUtil.getTechnicsDirectory(techNumber);
		String imageP = String.valueOf(this.parentPanel.table.getValueAt(row, 5));

		String filePath = techDir + File.separator + imageP;
		showImage(filePath);
	}

	private void chooseButtonActionPerformed(ActionEvent evt) {
		// 选择图片
		String filepath = FileChooserTool.getFilePath("jpg", this.dialog);
		//File file = getAttachFile();
		if(filepath == null || "".equals(filepath)) {

		} else {
			insertImgTextField.setText(filepath);
			showImage(filepath);
		}
	}

	private void showImage(String filepath) {
		if(filepath == null || "".equals(filepath) || filepath.endsWith(".dwg")) {
			jLabel5.setIcon(null);

			dialog.pack();
		} else {
			ImageIcon imageIcon = new ImageIcon(filepath);
	        imageIcon.setImage(imageIcon.getImage().getScaledInstance(403, 236, Image.SCALE_DEFAULT));
	        jLabel5.setIcon(imageIcon);

//	        p.removeAll();
//	        p.add(jLabel5);
//	        p.setVisible(true);
//	        p.setBounds(5, 15, 403, 236);
	//
//	        previewPanel.removeAll();
//	        previewPanel.add(p);
	        dialog.pack();
		}
	}

	private void sureButtonActionPerformed(ActionEvent evt) {
		//点击确定按钮
		TechnicsStateTableBean bean = new TechnicsStateTableBean();
		bean.setZzdw(makeDeptComboBox.getSelectedItem().toString());
		bean.setSydw(useDeptComboBox.getSelectedItem().toString());
		bean.setGyzt(speCharPanel.getText());
		if(oldPath == null || !oldPath.equals(insertImgTextField.getText())) {
			bean.setImagePath(insertImgTextField.getText());
			bean.setChangeFile(true);
		}
		if(this.flag == 0) {
			parentPanel.addToTable(bean);
		} else {
			parentPanel.update(bean, this.parentPanel.table.getSelectedRow());
		}

		dialog.setVisible(false);
	}

	private void cancelButtonActionPerformed(ActionEvent evt) {
		//点击取消按钮
		dialog.setVisible(false);
	}

	/**
	 * 将dialog屏幕居中显示
	 *
	 */
	public static void setMiddleOnScreenWithDialog(JDialog dialog){
		int windowWidth = dialog.getWidth();                     //获得窗口宽
	    int windowHeight = dialog.getHeight();                   //获得窗口高
	    Toolkit kit = Toolkit.getDefaultToolkit();              //定义工具包
	    Dimension screenSize = kit.getScreenSize();             //获取屏幕的尺寸
	    int screenWidth = screenSize.width;                     //获取屏幕的宽
	    int screenHeight = screenSize.height;                   //获取屏幕的高
	    dialog.setLocation(screenWidth/2-windowWidth/2, screenHeight/2-windowHeight/2);//设置窗口居中显示
	}

}
