package com.glaway.mpm.view;

import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.Iterator;
import java.util.Map;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.JTextComponent;

import org.dom4j.Document;
import org.dom4j.Element;

import com.glaway.mpm.qmIntf.frock.FrockSearchDialog;
import com.glaway.mpm.qmIntf.tecparam.TechnicsParamSearchDialog;
import com.glaway.mpm.util.WorkSpaceUtil;
import com.glaway.mpm.util.XmlUtility;

/**
*
* @author LongXiuChuan 2014/5/22
*/
public class WaiXieTecDescirbeJPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = 1L;
	private NewTechnicsPart parentPanel;
	protected DefaultTableModel tableModel = null;
	private JTextComponent currentText = null;

   /**
    * Creates new form WaiXieTecDescirbe
    */
   public WaiXieTecDescirbeJPanel(NewTechnicsPart parentPanel) {
	   this.parentPanel = parentPanel;
       initComponents();
       setName("WaiXieTecDescirbe");
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">
   private void initComponents() {

       jPanel1 = new javax.swing.JPanel();
       jScrollPane2 = new javax.swing.JScrollPane();
       jTable1 = new javax.swing.JTable();
       jButton2 = new javax.swing.JButton();
       jButton3 = new javax.swing.JButton();
       jPanel2 = new javax.swing.JPanel();
       jLabel1 = new javax.swing.JLabel();
       jTextField1 = new javax.swing.JTextField();
       jLabel2 = new javax.swing.JLabel();
       jTextField2 = new javax.swing.JTextField();
       jLabel3 = new javax.swing.JLabel();
       jScrollPane1 = new javax.swing.JScrollPane();
       jTextArea1 = new javax.swing.JTextArea();
       jButton1 = new javax.swing.JButton();

       gycsButton = new javax.swing.JButton();

       jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("工艺装备"));

       jTable1.setModel(new javax.swing.table.DefaultTableModel(
           new Object [][] {

           },
           new String [] {
               "编号", "名称", "类别", "型号", "规格", "oid", "frockCardNum"
           }
       ) {
           Class[] types = new Class [] {
               java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
           };
           boolean[] canEdit = new boolean [] {
               false, false, false, false, false, false, false
           };

           public Class getColumnClass(int columnIndex) {
               return types [columnIndex];
           }

           public boolean isCellEditable(int rowIndex, int columnIndex) {
               return canEdit [columnIndex];
           }
       });
       int width = Toolkit.getDefaultToolkit().getScreenSize().width;
       int height = Toolkit.getDefaultToolkit().getScreenSize().height;
       jScrollPane2.setViewportView(jTable1);
       tableModel = (DefaultTableModel)jTable1.getModel();
       jTable1.getTableHeader().setReorderingAllowed(false);
       setHiddenColumn(5);
       setHiddenColumn(6);

       jButton2.setText("添  加");
       jButton2.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton2ActionPerformed(evt);
               saveDescription();
           }
       });

       jButton3.setText("删  除");
       jButton3.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton3ActionPerformed(evt);
               saveDescription();
           }
       });
       jTextField2.getDocument().addDocumentListener(new DocumentListener() {
			@Override
			public void removeUpdate(DocumentEvent e) {
				saveDescription();
			}

			@Override
			public void insertUpdate(DocumentEvent e) {
				saveDescription();
			}

			@Override
			public void changedUpdate(DocumentEvent e) {
				saveDescription();
			}
		});
	   jTextField2.addMouseListener(new MouseAdapter() {
		   public void mouseClicked(MouseEvent e) {
			   currentText = jTextField2;
		   }
	   });
       jTextField1.getDocument().addDocumentListener(new DocumentListener() {
			@Override
			public void removeUpdate(DocumentEvent e) {
				saveDescription();
			}

			@Override
			public void insertUpdate(DocumentEvent e) {
				saveDescription();
			}

			@Override
			public void changedUpdate(DocumentEvent e) {
				saveDescription();
			}
		});
	   jTextField1.addMouseListener(new MouseAdapter() {
		   public void mouseClicked(MouseEvent e) {
			   currentText = jTextField1;
		   }
	   });
       jTextArea1.getDocument().addDocumentListener(new DocumentListener() {
			@Override
			public void removeUpdate(DocumentEvent e) {
				saveDescription();
			}

			@Override
			public void insertUpdate(DocumentEvent e) {
				saveDescription();
			}

			@Override
			public void changedUpdate(DocumentEvent e) {
				saveDescription();
			}
		});
	   jTextArea1.addMouseListener(new MouseAdapter() {
		   public void mouseClicked(MouseEvent e) {
			   currentText = jTextArea1;
		   }
	   });
       javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
       jPanel1.setLayout(jPanel1Layout);
       jPanel1Layout.setHorizontalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, (int)(width*0.4)+80, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jButton2)
                   .addComponent(jButton3))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );
       jPanel1Layout.setVerticalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addGap(18, 18, 18)
               .addComponent(jButton2)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(jButton3)
               .addContainerGap(162, Short.MAX_VALUE))
       );

       jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("属性"));

       jLabel1.setText("技术协议(或合同)编号：");

       jLabel2.setText("承制单位：");

       jLabel3.setText("备   注：");

       jTextArea1.setColumns(20);
       jTextArea1.setRows(5);
       jScrollPane1.setViewportView(jTextArea1);

       jButton1.setText("保  存");
       jButton1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton1ActionPerformed(evt);
           }
       });

       gycsButton.setText("插入工艺参数");
       gycsButton.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
        	   try {

					String param = null;
					TechnicsParamSearchDialog dia = new TechnicsParamSearchDialog(parentPanel);

					param = dia.showDialog();
					if(param == null) {
						param = "";
					}
					if(currentText ==null){
						currentText = jTextField1;
					}
					String oldText = currentText.getText();
					if(oldText!=null&&!"".equals(oldText)&&!"null".equals(oldText)){
						param = oldText + param;
					}
				    currentText.setText(param);
				} catch(Exception ee) {
					ee.printStackTrace();
				}
           }
       });



       javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
       jPanel2.setLayout(jPanel2Layout);
       jPanel2Layout.setHorizontalGroup(
           jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel2Layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                   .addGroup(jPanel2Layout.createSequentialGroup()
                       .addComponent(jLabel1)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, (int)(width*0.3), javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(gycsButton)
                       )

                   .addGroup(jPanel2Layout.createSequentialGroup()

                       .addComponent(jLabel2)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(jTextField2,javax.swing.GroupLayout.PREFERRED_SIZE, (int)(width*0.3), javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(98, 98, 98)
                       )
                   .addGroup(jPanel2Layout.createSequentialGroup()
                       .addComponent(jLabel3)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, (int)(width*0.3), javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(98, 98, 98)
                       //.addComponent(jButton1)
                       ))
               .addGap(0, 0, Short.MAX_VALUE))
       );
       jPanel2Layout.setVerticalGroup(
           jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel2Layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jLabel1)
                   .addComponent(gycsButton))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                   .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jLabel2))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jLabel3)
                   .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                       //.addComponent(jButton1)
                       .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, (int)(height*0.15)+30, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addContainerGap(22, Short.MAX_VALUE))
       );

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
       this.setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                   .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addContainerGap(15, Short.MAX_VALUE))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, (int)(height*0.2)+50, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, (int)(height*0.4)+50, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );
   }// </editor-fold>

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
	   Document document = this.parentPanel.getCurrentTechnics();
       Element techEle = XmlUtility.getTechnicsElement(document);

       XmlUtility.setAttributeValue(techEle, "jsxy", jTextField1.getText());
       XmlUtility.setAttributeValue(techEle, "zzdw", jTextField2.getText());
       XmlUtility.setAttributeValue(techEle, "bz", jTextArea1.getText());

       String content = jTextArea1.getText();
   	   content = content.replace("\n", "@#$");
       XmlUtility.setWXTechnicsDescribe(techEle, content);

       setLinkAtrributes(techEle);

       String techPath = WorkSpaceUtil.getTechnicsDirectory(techEle.attributeValue("technicsNumber"));
       String xmlFilePath = techPath + File.separator + techEle.attributeValue("technicsNumber")+".xml";
       System.out.println("---------xmlFilePath-----"+xmlFilePath);
       try {
    	   XmlUtility.saveDocument(techEle.getDocument(), xmlFilePath);
    	   JOptionPane.showMessageDialog(this.parentPanel, "外协工艺说明保存成功！");
       } catch (Exception e1) {
    	   JOptionPane.showMessageDialog(this.parentPanel, "外协工艺说明保存失败！");
    	   e1.printStackTrace();
       }
   }
   private void saveDescription() {
	   Document document = this.parentPanel.getCurrentTechnics();
       Element techEle = XmlUtility.getTechnicsElement(document);

       XmlUtility.setAttributeValue(techEle, "jsxy", jTextField1.getText());
       XmlUtility.setAttributeValue(techEle, "zzdw", jTextField2.getText());
       XmlUtility.setAttributeValue(techEle, "bz", jTextArea1.getText());

       String content = jTextArea1.getText();
   	   content = content.replace("\n", "@#$");
       XmlUtility.setWXTechnicsDescribe(techEle, content);

       setLinkAtrributes(techEle);

       String techPath = WorkSpaceUtil.getTechnicsDirectory(techEle.attributeValue("technicsNumber"));
       String xmlFilePath = techPath + File.separator + techEle.attributeValue("technicsNumber")+".xml";
       System.out.println("---------xmlFilePath-----"+xmlFilePath);
       try {
    	   XmlUtility.saveDocument(techEle.getDocument(), xmlFilePath);
       } catch (Exception e1) {
    	   JOptionPane.showMessageDialog(this.parentPanel, "外协工艺说明保存失败！");
    	   e1.printStackTrace();
       }
   }

   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		FrockSearchDialog dia = new FrockSearchDialog(parentPanel, WaiXieTecDescirbeJPanel.this);
		Vector vec = dia.showDialog();
		addData(vec);
   }

   private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
	   int[] rows = jTable1.getSelectedRows();
		for (int i = 0; i < rows.length; i++) {
			tableModel.removeRow(rows[i]);
			for (int j = i + 1; j < rows.length; j++) {
				rows[j] = rows[j] - 1;
			}
		}
		jTable1.updateUI();
   }

	public void addData(Vector vec) {
		if (vec != null && vec.size() > 0) {
			for (int i = 0; i < vec.size(); i++) {
				Map map = (Map) vec.get(i);
				setOneRowTableValue(map);
			}
		}
	}

	// 取表格里的值
	private void setLinkAtrributes(Element techEle) {
		Element toolElement = techEle.element(XmlUtility.TOOL_GROUP);
		if (toolElement == null)
			toolElement = techEle.addElement(XmlUtility.TOOL_GROUP);
		toolElement.elements().clear();
		Vector<Element> tool = getElements();
		for (Iterator<Element> it = tool.iterator(); it.hasNext();) {
			toolElement.add(it.next());
		}

	}

	public Vector<Element> getElements() {
		Vector<Element> elements = new Vector<Element>();
		for (int i = 0; i < tableModel.getRowCount(); i++) {
			if (isRowNull(i))
				continue;
			Element element = XmlUtility.createTool();
			XmlUtility.setAttributeValue(element, "bsoID", "");
			XmlUtility.setAttributeValue(element, "toolNum", (String) tableModel.getValueAt(i, 0));
			XmlUtility.setAttributeValue(element, "toolName", (String) tableModel.getValueAt(i, 1));
			XmlUtility.setAttributeValue(element, "frockType", (String) tableModel.getValueAt(i, 2));
			XmlUtility.setAttributeValue(element, "csize", (String) tableModel.getValueAt(i, 3));
			XmlUtility.setAttributeValue(element, "mindex", (String) tableModel.getValueAt(i, 4));
			XmlUtility.setAttributeValue(element, "oid", (String) tableModel.getValueAt(i, 5));
			XmlUtility.setAttributeValue(element, "frockCardNum", (String) tableModel.getValueAt(i, 6));
			elements.add(element);
		}
		return elements;
	}

	protected boolean isRowNull(int row) {
		for (int i = 0; i < tableModel.getColumnCount(); i++) {
			if (tableModel.getValueAt(row, i) != null
					&& !tableModel.getValueAt(row, i).equals(""))
				return false;
		}
		return true;
	}

	public void setHiddenColumn(int columnIndex) {
		if (columnIndex >= 0 && columnIndex < jTable1.getColumnCount()) {
			// 隐藏ID列
			jTable1.getTableHeader().getColumnModel().getColumn(columnIndex).setMaxWidth(0);
			jTable1.getTableHeader().getColumnModel().getColumn(columnIndex).setMinWidth(0);
			jTable1.getColumnModel().getColumn(columnIndex).setMaxWidth(0);
			jTable1.getColumnModel().getColumn(columnIndex).setPreferredWidth(0);
			jTable1.getColumnModel().getColumn(columnIndex).setWidth(0);
			jTable1.getColumnModel().getColumn(columnIndex).setMinWidth(0);
		}
	}

	public void setOneRowTableValue(Map map) {
		String number = (String) map.get("toolNum");
		if (number.startsWith("A%")) {
			number = number.replace("A%", "");
		}
		if (number.startsWith("B%")) {
			number = number.replace("B%", "");
		}
		if (isHasExistData(tableModel, 0, number))
			return;
		addProcess();
		int i = tableModel.getRowCount();
		i--;
		tableModel.setValueAt(number, i, 0);
		tableModel.setValueAt(map.get("toolName"), i, 1);
		tableModel.setValueAt(map.get("frockType"), i, 2);
		tableModel.setValueAt(map.get("csize"), i, 3);
		tableModel.setValueAt(map.get("mindex"), i, 4);
		tableModel.setValueAt(map.get("oid"), i, 5);
		tableModel.setValueAt(map.get("frockCardNum"), i, 6);
	}

	public void addProcess() {
		// stopTableCellEditing();
		Vector<String> vector = new Vector<String>();
		for (int i = 0; i < tableModel.getColumnCount(); i++) {
			vector.add("");
		}
		tableModel.addRow(vector);
	}

	protected boolean isHasExistData(DefaultTableModel model, int colIndex,
			String data) {
		if (null == model || model.getRowCount() == 0)
			return false;

		for (int i = 0; i < model.getRowCount(); i++) {
			String str = "";
			if (model.getValueAt(i, colIndex) == null
					|| (str = (((String) (model.getValueAt(i, colIndex)))
							.trim())).equals(""))
				continue;
			if (str.equals(data))
				return true;
		}
		return false;
	}

	public void loadData(Element techEle) {
		jTextField1.setText(techEle.attributeValue("jsxy"));
		jTextField2.setText(techEle.attributeValue("zzdw"));

		String content = XmlUtility.getWXTechnicsDescribe(techEle);
		content = content.replace("@#$", "\n");
		jTextArea1.setText(content);

		Element toolElement = techEle.element(XmlUtility.TOOL_GROUP);
		Vector<Element> toolVec = new Vector<Element>();
		if(toolElement != null) {
			for (Iterator<Element> it = toolElement.elementIterator(XmlUtility.TOOL_TAG); it.hasNext();) {
				toolVec.add(it.next());
			}
		}
		setTableValues(toolVec);
	}

	public void setTableValues(Vector<Element> vec) {
		clearTable();
		for (int i = 0; i < vec.size(); i++) {
			Element element = vec.get(i);
			setOneRowTableValue(element);
		}
	}

	public void clearTable() {
		tableModel.setRowCount(0);
	}

	public void setOneRowTableValue(Element element) {
		if (element != null && element.getName().equals(XmlUtility.TOOL_TAG)) {
			addProcess();
			int i = tableModel.getRowCount();
			i--;
			tableModel.setValueAt(element.attributeValue("toolNum"), i, 0);
			tableModel.setValueAt(element.attributeValue("toolName"), i, 1);
			tableModel.setValueAt(element.attributeValue("frockType"), i, 2);
			tableModel.setValueAt(element.attributeValue("csize"), i, 3);
			tableModel.setValueAt(element.attributeValue("mindex"), i, 4);
			tableModel.setValueAt(element.attributeValue("oid"), i, 5);
			tableModel.setValueAt(element.attributeValue("frockCardNum"), i, 6);
		}
	}

  public void setUIEnabled(boolean b){
	   jButton1.setEnabled(b);
	   gycsButton.setEnabled(b);

	   jButton2.setEnabled(b);
	   jButton3.setEnabled(b);
	   jTable1.setEnabled(b);
	   jTextArea1.setEnabled(b);
	   jTextField1.setEnabled(b);
	   jTextField2.setEnabled(b);
   }

  public void clear() {
	  jTextField1.setText("");
	  jTextField2.setText("");
	  jTextArea1.setText("");
	  clearTable();
  }

   // Variables declaration - do not modify
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JButton jButton3;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JTable jTable1;
   private javax.swing.JTextArea jTextArea1;
   private javax.swing.JTextField jTextField1;
   private javax.swing.JTextField jTextField2;
   private javax.swing.JButton gycsButton;

}
