  CREATE TABLE "PDM10"."GLMATERIALQUOTARECORD"
   (	"CMKEYID" VARCHAR2(30 BYTE) NOT NULL ENABLE,
	"DOCNUMBER" VARCHAR2(64 BYTE),
	"VERSION" VARCHAR2(20 BYTE),
	 CONSTRAINT "GLMATERIALQUOTARECORD_PK" PRIMARY KEY ("CMKEYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;