
  CREATE TABLE "PDM10"."GLNCPARTMAPPING"
   (	"CMKEYID" VARCHAR2(64 BYTE) NOT NULL ENABLE,
	"OLDPARTNUMBER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"NEWPARTNUMBER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"STATE" VARCHAR2(10 BYTE),
	"SYNCHTIME" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE INDEX "PDM10"."OLDPARTNUMBER_IDX" ON "PDM10"."GLNCPARTMAPPING" ("OLDPARTNUMBER")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE INDEX "PDM10"."NEWPARTNUMBER_IDX" ON "PDM10"."GLNCPARTMAPPING" ("NEWPARTNUMBER")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

