
  CREATE TABLE "PDM10"."SYNCHPARTRECORD"
   (
    "CMKEYID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"INSTANCEID" VARCHAR2(100 BYTE),
	"OBJECTNUMBER" VARCHAR2(200 BYTE),
	"OBJECTVERSION" VARCHAR2(100 BYTE),
	"VIEWNAME" VARCHAR2(100 BYTE),
	"SYNCHSTATE" VARCHAR2(100 BYTE),
	"IMPORTER" VARCHAR2(100 BYTE),
    "NOTE" VARCHAR2(200 BYTE),
	"SYNCHTIME" VARCHAR2(32 BYTE),
	 CONSTRAINT "SYNCHPARTRECORD_PK" PRIMARY KEY ("CMKEYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


  CREATE INDEX "PDM10"."SYNCHPARTRECORD_INDEX1" ON "PDM10"."SYNCHPARTRECORD" ("INSTANCEID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

  CREATE INDEX "PDM10"."SYNCHPARTRECORD_INDEX2" ON "PDM10"."SYNCHPARTRECORD" ("OBJECTNUMBER")
      PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;