-- ɾ����
DROP TABLE "PDM10"."GLPROCESSPARAMDEFINITION" CASCADE CONSTRAINTS;

CREATE TABLE "PDM10"."GLPROCESSPARAMDEFINITION"
(
    "CMKEYID"       VARCHAR2(64 BYTE) NOT NULL ENABLE,
    "TEMPLATEID"    VARCHAR2(60 BYTE),
    "GYPARAMNUMBER" VARCHAR2(20 BYTE),
    "GYPARAMNAME"   VARCHAR2(100 BYTE),
    "GYPARAMTYPE"   VARCHAR2(100 BYTE),
    "ENUMVALUES"   VARCHAR2(4000 BYTE),
    "SJPARAMNAME"   VARCHAR2(100 BYTE),
    CONSTRAINT "GLPROCESSPARAMDEFINITION_PK" PRIMARY KEY ("CMKEYID")
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
            TABLESPACE "USERS" ENABLE
) SEGMENT CREATION DEFERRED
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    TABLESPACE "USERS";

