CREATE TABLE PDM10.GLProcessKnowledge
(
    CMKEYID   VARCHAR2(100 CHAR) NOT NULL,
    XUHAO     VARCHAR2(100 CHAR),
    SHEETNAME VARCHAR2(100 CHAR) NOT NULL,
    SMALLTYPE VARCHAR2(100 CHAR),
    STATE     VARCHAR2(30 CHAR) ,
    ZHUANYE    VARCHAR2(100 CHAR) ,
    COLUMN1   VARCHAR2(200 CHAR),
    COLUMN2   VARCHAR2(200 CHAR),
    COLUMN3   VARCHAR2(200 CHAR),
    COLUMN4   VARCHAR2(200 CHAR),
    COLUMN5   VARCHAR2(200 CHAR),
    COLUMN6   VARCHAR2(200 CHAR),
    COLUMN7   VARCHAR2(200 CHAR),
    COLUMN8   VARCHAR2(200 CHAR),
    COLUMN9   VARCHAR2(200 CHAR),
    COLUMN10   VARCHAR2(200 CHAR),
    COLUMN11   VARCHAR2(200 CHAR),
    COLUMN12   VARCHAR2(200 CHAR),
    CONSTRAINT GLProcessKnowledge_PK PRIMARY KEY (CMKEYID)
) TABLESPACE USERS;
CREATE INDEX GLProcessKnowledge_Index ON PDM10.GLProcessKnowledge (SHEETNAME, SMALLTYPE);

CREATE INDEX COLUMN1_IDX ON PDM10.GLPROCESSKNOWLEDGE (COLUMN1);
CREATE INDEX COLUMN2_IDX ON PDM10.GLPROCESSKNOWLEDGE (COLUMN2);
CREATE INDEX COLUMN3_IDX ON PDM10.GLPROCESSKNOWLEDGE (COLUMN3);
CREATE INDEX COLUMN4_IDX ON PDM10.GLPROCESSKNOWLEDGE (COLUMN4);
CREATE INDEX COLUMN5_IDX ON PDM10.GLPROCESSKNOWLEDGE (COLUMN5);
CREATE INDEX COLUMN6_IDX ON PDM10.GLPROCESSKNOWLEDGE (COLUMN6);


/* 2024/8/20扩展
ALTER TABLE PDM10.GLPROCESSKNOWLEDGE ADD COLUMN9 VARCHAR2(200);
ALTER TABLE PDM10.GLPROCESSKNOWLEDGE ADD COLUMN10 VARCHAR2(200);
ALTER TABLE PDM10.GLPROCESSKNOWLEDGE ADD COLUMN11 VARCHAR2(200);
ALTER TABLE PDM10.GLPROCESSKNOWLEDGE ADD COLUMN12 VARCHAR2(200);
ALTER TABLE PDM10.GLPROCESSKNOWLEDGE ADD ZHUANYE VARCHAR2(200);
ALTER TABLE PDM10.GLPROCESSKNOWLEDGE MODIFY XUHAO VARCHAR2(100) NULL;

 */



