
CREATE TABLE "PDM10"."GLPROCESSPARAMS"
(	"CMKEYID" VARCHAR2(100 CHAR) NOT NULL ENABLE,
     "GYNUMBER" VARCHAR2(30 CHAR) NOT NULL ENABLE,
     "GYNAME" VARCHAR2(100 CHAR) NOT NULL ENABLE,
     "PARAMETERCATEGORY" VARCHAR2(30 CHAR) NOT NULL ENABLE,
     "PROCESSCATEGORY" VARCHAR2(30 CHAR) NOT NULL ENABLE,
     "ENUMVALUES" VARCHAR2(30 CHAR),
     "UNIT" VARCHAR2(20 CHAR),
     "KNOWLEDGEINFERENCEPARA" VARCHAR2(200 CHAR),
     "KNOWLEDGEOUTPUTPARA" VARCHAR2(200 CHAR),
     "OUTPUTRULES" VARCHAR2(4000 CHAR),
     "KNOWLEDGETYPE" VARCHAR2(30),
     "ISCANZHUANG" VARCHAR2(30),
     "ISONLYVALUE" VARCHAR2(30),
     "SOURCE" VARCHAR2(30 CHAR),
     CONSTRAINT "GLPROCESSPARAMS_PK" PRIMARY KEY ("CMKEYID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
         BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "USERS"  ENABLE,
     CONSTRAINT "GLPROCESSPARAMS_UN" UNIQUE ("GYNUMBER")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
         BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "USERS"  ENABLE,
     CONSTRAINT "GLPROCESSPARAMS_UNNAME" UNIQUE ("GYNAME")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
         BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "USERS"  ENABLE
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 