CREATE TABLE "PDM10"."GLPROCESSPARAMVALUES"
(
    "CMKEYID"       VARCHAR2(64 BYTE) NOT NULL ENABLE,
    "TEMPLATEID"    VARCHAR2(60 BYTE),
    "TEMPLATENAME"  VARCHAR2(80 BYTE),
    "CADNAME"       VARCHAR2(200 BYTE),
    "CADVERSION"    VARCHAR2(20 BYTE),
    "PARTNUMBER"    VARCHAR2(100 BYTE),
    "PARTVERSION"   VARCHAR2(60 BYTE),
    "GYPARAMNAME"   VARCHAR2(100 BYTE),
    "GYPARAMNUMBER" VARCHAR2(80 BYTE),
    "SJPARAMNAME"   VARCHAR2(100 BYTE),
    "PARAMVALUE"    VARCHAR2(600 BYTE),
    "PARAMUNIT"     VARCHAR2(100 BYTE),
    "GONGCHENGZHI"  VARCHAR2(100 BYTE),
    "SHANGPIANCHA"  VARCHAR2(100 BYTE),
    "XIAPIANCHA"    VARCHAR2(100 BYTE),
    "FUHAO"         VARCHAR2(100 BYTE),
    "JIZHUN1"       VARCHAR2(600 BYTE),
    "JIZHUN2"       VARCHAR2(600 BYTE),
    "JIZHUN3"       VARCHAR2(600 BYTE),
    "DATAFROM"      VARCHAR2(20 BYTE),
    CONSTRAINT "GLPROCESSPARAMVALUES_PK" PRIMARY KEY ("CMKEYID")
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
            TABLESPACE "USERS" ENABLE
) SEGMENT CREATION DEFERRED
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    TABLESPACE "USERS";


CREATE UNIQUE INDEX "PDM10"."GLPROCESSPARAMVALUES_PK" ON "PDM10"."GLPROCESSPARAMVALUES" ("CMKEYID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
    TABLESPACE "USERS" ;

CREATE INDEX "PDM10"."CADNAME_VERSION" ON "PDM10"."GLPROCESSPARAMVALUES" ("CADNAME", "CADVERSION")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
    TABLESPACE "USERS" ;

CREATE INDEX "PDM10"."PARTNUMBER_VERSION" ON "PDM10"."GLPROCESSPARAMVALUES" ("PARTNUMBER", "PARTVERSION")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
    TABLESPACE "USERS" ;

CREATE INDEX PARTNUMBER_IDX ON PDM10.GLPROCESSPARAMVALUES (PARTNUMBER);
