-- 工艺模板映射
CREATE TABLE PDM10.GLProcessTemplateLink
(
    CMKEYID         VARCHAR2(100 CHAR) NOT NULL,
    XUHAO           VARCHAR2(5 CHAR),
    CAILIAOFENLEI   VARCHAR2(200 CHAR),
    YAXIAXIAN       VARCHAR2(200 CHAR),
    RECHULI         VARCHAR2(200 CHAR),
    BIAOMIANCHULI   VARCHAR2(200 CHAR),
    PROCESSTEMPLATE VARCHAR2(200 CHAR),
    TEMPLATENUMBER  VARCHAR2(200 CHAR),
    CONSTRAINT GLProcessTemplateLink_PK PRIMARY KEY (CMKEYID)
) TABLESPACE USERS;
CREATE INDEX GLProcessTemplateLink_n_h ON PDM10.GLProcessTemplateLink (CAILIAOFENLEI, PROCESSTEMPLATE);



