CREATE TABLE PDM10.GLProcessLink
(
    CMKEYID  VARCHAR2(100 CHAR) NOT NULL,
    paraName VARCHAR2(100 CHAR) NOT NULL,
    heads    VARCHAR2(300 CHAR) NOT NULL,
    CONSTRAINT GLProcessLink_PK PRIMARY KEY (CMKEYID)
) TABLESPACE USERS;
CREATE INDEX GLProcessLink_name_heads ON PDM10.GLProcessLink (paraName, heads);


