CREATE TABLE PDM10.GLProcessOtherKnowledge
(
    CMKEYID   VARCHAR2(100 CHAR) NOT NULL,
    ZHUANYE     VARCHAR2(100 CHAR) ,
    COLUMN1   VARCHAR2(200 CHAR),
    COLUMN2   VARCHAR2(200 CHAR),
    COLUMN3   VARCHAR2(200 CHAR),
    COLUMN4   VARCHAR2(200 CHAR),
    COLUMN5   VARCHAR2(200 CHAR),
    COLUMN6   VARCHAR2(200 CHAR),
    COLUMN7   VARCHAR2(200 CHAR),
    COLUMN8   VARCHAR2(200 CHAR),
    COLUMN9   VARCHAR2(200 CHAR),
    COLUMN10   VARCHAR2(200 CHAR),
    CONSTRAINT GLProcessOtherKnowledge_PK PRIMARY KEY (CMKEYID)
) TABLESPACE USERS;
CREATE INDEX GLProcessOtherKnowledge_Index ON PDM10.GLProcessOtherKnowledge (ZHUANYE,COLUMN1,COLUMN2,COLUMN3);


