-- 工序模板映射

CREATE TABLE PDM10.GLProcessStepTemplateLink
(
    CMKEYID             VARCHAR2(100 CHAR) NOT NULL,
    STEPNAME            VARCHAR2(50 CHAR),
    XUHAO               VARCHAR2(5 CHAR),
    CAILIAOFENLEI       VARCHAR2(200 CHAR),
    GUIGE               VARCHAR2(200 CHAR),
    BIAOMIANCHULI       VARCHAR2(200 CHAR),
    PROCESSSTEPTEMPLATE VARCHAR2(200 CHAR),
    TEMPLATENUMBER      VARCHAR2(200 CHAR),
    CONSTRAINT GLProcessStepTemplateLink_PK PRIMARY KEY (CMKEYID)
) TABLESPACE USERS;
CREATE INDEX GLProcessStepTemplateLink_n_h ON PDM10.GLProcessStepTemplateLink (STEPNAME, PROCESSSTEPTEMPLATE);


