CREATE INDEX EnvelopeMemberLink$COMPOSITE0 ON EnvelopeMemberLink(branchIdA3B5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX EnvelopeMemberLink$COMPOSITE1 ON EnvelopeMemberLink(idA3A5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
