CREATE INDEX EnvelopeTopObjLink$COMPOSITE0 ON EnvelopeTopObjLink(idA3A5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX EnvelopeTopObjLink$COMPOSITE1 ON EnvelopeTopObjLink(idA3B5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
