CREATE INDEX ProcessEnvelope$COMPOSITE1 ON ProcessEnvelope(idA3A2folderingInfo)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX ProcessEnvelope$COMPOSITE2 ON ProcessEnvelope(idA3teamId)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX ProcessEnvelope$COMPOSITE6 ON ProcessEnvelope(idA3containerReference)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX ProcessEnvelope$COMPOSITE20 ON ProcessEnvelope(ProcessEnvelopeNumber)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
