
  CREATE TABLE "PDM10"."GWPRINTDISTRIBUTERECORD" 
   (	"GWKEYID" VARCHAR2(500 BYTE), 
	"DOCVR" VARCHAR2(500 BYTE), 
	"APPLYRECORDID" VARCHAR2(500 BYTE), 
	"DISTRIBUTEDEPT" VARCHAR2(500 BYTE), 
	"DISTRIBUTEQUANTITY" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


Insert into GWPRINTDISTRIBUTERECORD (GWKEYID,DOCVR,APPLYRECORDID,DISTRIBUTEDEPT,DISTRIBUTEQUANTITY) values ('GWREC001',null,'GW001','一分厂','1');
Insert into GWPRINTDISTRIBUTERECORD (GWKEYID,DOCVR,APPLYRECORDID,DISTRIBUTEDEPT,DISTRIBUTEQUANTITY) values ('GWREC002',null,'GW001','二分厂','3');
Insert into GWPRINTDISTRIBUTERECORD (GWKEYID,DOCVR,APPLYRECORDID,DISTRIBUTEDEPT,DISTRIBUTEQUANTITY) values ('GWREC002',null,'GW001','八分厂','4');
