CREATE INDEX TechNoticeBeforeLink$COMPOSITE ON TechNoticeBeforeLink(branchIdA3A5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX TechNoticeBeforeLink$COMPOSIT1 ON TechNoticeBeforeLink(branchIdA3B5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
