CREATE INDEX TechNoticeAfterLink$COMPOSITE ON TechNoticeAfterLink(branchIdA3A5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX TechNoticeAfterLink$COMPOSITE1 ON TechNoticeAfterLink(branchIdA3B5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
