#零部件设计属性
design_SHORTNAME=物资简称
design_STANDARDNUMBER=标准号
design_STANDARD=规格
design_CMAT=材料
design_MECHANICALPROPERTYORHARDNESS=机械性能等级或硬度
design_SURFACETREATMENT=表面处理
design_HEATTREATMENT=热处理
design_PRODUCTFORM=产品型式
design_PRODUCTLEVEL=产品等级
design_PLATECSCREWFORM=板拧形式
design_ISIMPORT=是否进口
design_SPECIALINSTRUCTION=特殊说明
design_MEASUREUNIT=计量单位