CREATE INDEX ChangeRequestAffectLink$COMP0 ON ChangeRequestAffectLink(branchIdA3B5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX ChangeRequestAffectLink$COMP1 ON ChangeRequestAffectLink(idA3A5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
