CREATE INDEX ChangeRequest$COMPOSITE1 ON ChangeRequest(idA3A2folderingInfo)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX ChangeRequest$COMPOSITE2 ON ChangeRequest(idA3teamId)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX ChangeRequest$COMPOSITE6 ON ChangeRequest(idA3containerReference)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX ChangeRequest$COMPOSITE20 ON ChangeRequest(ChangeRequest)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
