package com.glaway.mpm.task;

import com.glaway.mpm.util.DateChooser;
import com.glaway.mpm.util.DateUtil;
import com.glaway.mpm.util.IntfUtil;
import com.glaway.mpm.view.NewTechnicsPart;
import com.glaway.mpm.wcIntf.ResourceIntf;
import com.glaway.mpm.wcIntf.TechnicsIntf;
import org.dom4j.Element;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.lang.reflect.InvocationTargetException;
import java.rmi.RemoteException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CreateTaskItemDialog {

    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField userField;
    private javax.swing.JButton searchUserButton;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JTextField jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private JLabel cldePlanTimeLabel;
    private JTextField cldePlanTimeTextField;
//    private JButton clearButton;

	private String[] taskType = new String[]{"工艺设计任务","工艺更改任务","临时工艺任务"};
	private Map<String, String> workShop = null;
	private Element techElement;
	private NewTechnicsPart frame;
	private JDialog dialog;

	/**
     * Creates new form CreateTaskItemDialog
     */
    public CreateTaskItemDialog(NewTechnicsPart frame, Element techElement) {
        super();
        this.frame = frame;
        this.techElement = techElement;

        newJDialog();
        initComponents();
        initData();

        setMiddleOnScreenWithDialog(dialog);
        dialog.setModal(true);
        dialog.setVisible(true);
    }

	/**
	 * 新增对话框jdialog
	 */
	public void newJDialog() {
		dialog = new JDialog();
		dialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		dialog.setTitle("提交辅制工艺编制任务");
		dialog.setIconImage(frame.getIconImage());
		dialog.setResizable(false);
		dialog.setSize(500,500);
	}

    private void initData() {
		// 20250122 车间从config_149.xml加载
//		List<String> allList = ResourceIntf.getAllDepts();
//		for (String string : allList) {
//			userField.addItem(string);
//		}

		jLabel2.setText(techElement.attributeValue("partNumber"));
		jLabel4.setText(techElement.attributeValue("partName"));
		jLabel6.setText(techElement.attributeValue("pplanNumber"));
		jLabel8.setText(techElement.attributeValue("pplanName"));

		jTextField1.setText(DateUtil.getTodayDate());
		DateChooser dateChooser = DateChooser.getInstance("yyyy/MM/dd");
		dateChooser.register(jTextField1);

//		cldePlanTimeTextField.setText(DateUtil.getTodayDate());
		DateChooser dateChooser2 = DateChooser.getInstance("yyyy/MM/dd");
		dateChooser2.register(cldePlanTimeTextField);
		cldePlanTimeTextField.addMouseListener(new MouseListener() {
			@Override
			public void mouseClicked(MouseEvent e) {
				if (e.getClickCount() == 2) {
					cldePlanTimeTextField.setText("");
				}
			}

			@Override
			public void mousePressed(MouseEvent e) {

			}

			@Override
			public void mouseReleased(MouseEvent e) {

			}

			@Override
			public void mouseEntered(MouseEvent e) {

			}

			@Override
			public void mouseExited(MouseEvent e) {

			}
		});
    }

	/**
	 * 将dialog屏幕居中显示
	 * @author chenyunlong
	 * @date  2013-6-13
	 * @param dialog
	 *
	 */
	public static void setMiddleOnScreenWithDialog(JDialog dialog){
		int windowWidth = dialog.getWidth();                     //获得窗口宽
	    int windowHeight = dialog.getHeight();                   //获得窗口高
	    Toolkit kit = Toolkit.getDefaultToolkit();              //定义工具包
	    Dimension screenSize = kit.getScreenSize();             //获取屏幕的尺寸
	    int screenWidth = screenSize.width;                     //获取屏幕的宽
	    int screenHeight = screenSize.height;                   //获取屏幕的高
	    dialog.setLocation(screenWidth/2-windowWidth/2, screenHeight/2-windowHeight/2);//设置窗口居中显示
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
		userField = new javax.swing.JTextField();
		userField.setEditable(false);
		searchUserButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jTextField1 = new javax.swing.JTextField();
        cldePlanTimeLabel = new javax.swing.JLabel();
        cldePlanTimeTextField = new JTextField();
//        clearButton = new JButton();

        jTextPane1.setPreferredSize(new Dimension(15,25));

        jLabel1.setText("零部件编号：");
        jLabel2.setEditable(false);

        jLabel3.setText("零部件名称：");
        jLabel4.setEditable(false);

        jLabel5.setText("主工艺编号：");
        jLabel6.setEditable(false);

        jLabel7.setText("主工艺名称：");
        jLabel8.setEditable(false);

        jLabel9.setText("工艺员：");
        searchUserButton.setText("查询");
		searchUserButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				new SearchTaskUserDialog(frame,userField);
			}
		});

        jLabel10.setText("任务类型：");
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(taskType));

        jLabel11.setText("计划完成时间：");

        cldePlanTimeLabel.setText("材料定额计划完成时间：");

        jLabel12.setText("任务说明：");

        jButton1.setText("确定");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

//        clearButton.setText("clear");
//		clearButton.addActionListener(new ActionListener() {
//			public void actionPerformed(ActionEvent evt) {
//				clear(evt);
//			}
//		});
        jButton2.setText("取消");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jTextPane1);

        jTextField1.setEditable(false);
        jTextField1.setText("");

		cldePlanTimeTextField.setEditable(false);
		cldePlanTimeTextField.setText("");

        JPanel mainPanel = new JPanel();
        dialog.add(mainPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(layout);
		// 水平布局部分的修改
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGap(0, 0, Short.MAX_VALUE) // 移除固定间隙，只保留弹性间隙
								.addComponent(jButton1)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jButton2)
								.addGap(0, 0, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup()
								.addGap(38, 38, 38)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel5)
														.addComponent(jLabel3)
														.addComponent(jLabel1)
														.addComponent(jLabel7)
														.addComponent(jLabel9)
														.addComponent(jLabel10)
														.addComponent(jLabel11)
														.addComponent(cldePlanTimeLabel)
														.addComponent(jLabel12))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addGroup(layout.createSequentialGroup()
																.addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(searchUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(cldePlanTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								))
		);

		// 垂直布局部分的修改
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGap(25, 25, 25)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel1)
										.addComponent(jLabel2))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel3)
										.addComponent(jLabel4))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel5)
										.addComponent(jLabel6))
								.addGap(14, 14, 14)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel7)
										.addComponent(jLabel8))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel9)
										.addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(searchUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel10)
										.addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel11)
										.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(cldePlanTimeLabel)
										.addComponent(cldePlanTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addComponent(jLabel12)
												.addGap(0, 0, Short.MAX_VALUE))
										.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
								.addGap(34, 34, 34)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jButton1)
										.addComponent(jButton2))
								.addGap(22, 22, 22))
		);

		Container contentPane = dialog.getContentPane();
		contentPane.add(mainPanel);
    }

    private void clear(ActionEvent evt){
    	cldePlanTimeTextField.setText("");
	}

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    	String dateStr = jTextField1.getText();
    	String cldePlanTime = cldePlanTimeTextField.getText();
    	String fzcj = String.valueOf(userField.getText());
    	String taskTypeValue = String.valueOf(jComboBox2.getSelectedItem());
    	String currentCj = techElement.attributeValue("DEPT");
    	if(dateStr == null || "".equals(dateStr)) {
    		JOptionPane.showMessageDialog(dialog,"计划完成时间不能为空！");
    	} else if (fzcj == null || "".equals(fzcj)) {
    		JOptionPane.showMessageDialog(dialog,"辅制工艺员不能为空！");
    	}
//    	else if (fzcj.equals(currentCj)) {
//    		JOptionPane.showMessageDialog(dialog,"辅制任务不能分配给本车间！");
//    	}
    	else if (taskTypeValue == null || "".equals(taskTypeValue)) {
    		JOptionPane.showMessageDialog(dialog,"任务类型不能为空！");
    	} else {
        	String taskDescribe = jTextPane1.getText();
        	dateStr = dateStr.replaceAll("/", "-")+" "+"00:00:00";
        	if(cldePlanTime != null && !cldePlanTime.isEmpty()){
				cldePlanTime = cldePlanTime.replaceAll("/", "-")+" "+"00:00:00";
			}
        	String technicsNumber = this.techElement.attributeValue("technicsNumber");
        	String pplanNumber = this.techElement.attributeValue("pplanNumber");
        	String technicsName = this.techElement.attributeValue("technicsName");

        	String partNumber = this.techElement.attributeValue("partNumber");
        	String partVersion = this.techElement.attributeValue("partVersion");
        	String oid = null;

        	oid=(String) IntfUtil.getPeRemoteMethodInvoke("getProcessTaskItemOidByPartNumber",
       			   new Class[] { String.class,String.class,String.class }, new Object[] { partNumber,"工艺编制",partVersion});
        	if(oid==null){
        		oid=(String) IntfUtil.getPeRemoteMethodInvoke("getProcessTaskItemOidByPartNumber",
            			   new Class[] { String.class,String.class,String.class }, new Object[] { partNumber,"临时工艺任务",partVersion});
        	}
        	if(NewTechnicsPart.workItemOid!=null&&oid==null){
        		String taskItemName=(String) IntfUtil.getPeRemoteMethodInvoke("getTaskItemName",
    					new Class[] { String.class }, new Object[] { NewTechnicsPart.workItemOid});
                if (taskItemName!=null&&("工艺编制".equals(taskItemName)||"临时工艺任务".equals(taskItemName))) {
            	    oid=(String) IntfUtil.getPeRemoteMethodInvoke("getProcessTaskItemOidByPartNumber",
            			   new Class[] { String.class,String.class ,String.class}, new Object[] { partNumber,taskItemName,partVersion});
    		    }
        	}


        	if (oid==null) {
        		//JOptionPane.showMessageDialog(dialog,"找不到相应的工艺任务！请到对应的工艺任务启动工艺编辑器后再提交。");
        		//return;
			}
        	Map<String,String> map = new  HashMap<String,String>();

        	map.put("technicsNumber", technicsNumber);
        	map.put("pplanNumber", pplanNumber);
        	map.put("technicsName", technicsName);

        	map.put("FZCJ", fzcj);
        	map.put("taskType", taskTypeValue);
        	map.put("JHWCSJ", dateStr);
        	map.put("cldePlanTime", cldePlanTime);
        	map.put("taskDescribe", taskDescribe);
        	map.put("partVersion", partVersion);



        	map.put("ZGYOID", oid);
        	System.out.println("------map----"+map);
        	boolean b = true;
			/*try {
				b = TechnicsIntf.checkProcessTask(map);
			} catch (RemoteException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (InvocationTargetException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}*/

        	/*if((taskTypeValue.equals("工艺设计任务")||taskTypeValue.equals("工艺更改任务"))&&!b) {
        		JOptionPane.showMessageDialog(dialog,"设计或更改主工艺任务的辅制工艺任务，每个车间只能有一份辅制工艺任务！");
        	} else {*/
        		boolean flag = true;
				try {
					flag = TechnicsIntf.createTaskItem(map);
				} catch (RemoteException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (InvocationTargetException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            	if(flag) {
            		JOptionPane.showMessageDialog(dialog,"辅制工艺编制任务提交成功！");
            	} else {
            		JOptionPane.showMessageDialog(dialog,"辅制工艺编制任务提交失败，请联系管理员！");
            	}
            	this.dialog.setVisible(false);
        	//}
    	}
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
    	dialog.setVisible(false);
    }
}
