CREATE INDEX TechnicsMaterial$COMPOSITE1 ON TechnicsMaterial(idA3A2folderingInfo)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX TechnicsMaterial$COMPOSITE2 ON TechnicsMaterial(idA3teamId)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX TechnicsMaterial$COMPOSITE6 ON TechnicsMaterial(idA3containerReference)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX TechnicsMaterial$COMPOSITE13 ON TechnicsMaterial(idA3B2folderingInfo)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX TechnicsMaterial$COMPOSITE20 ON TechnicsMaterial(TechnicsMaterialName)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
