/*复合材料*/
DROP TABLE "TMECOMPOUNDMATERIALPARTLINK";
CREATE TABLE "TMECOMPOUNDMATERIALPARTLINK" (
"GWKEYID" VARCHAR2(255 BYTE) NOT NULL ,
"TECHNICSMATERIALENTRIESID" VARCHAR2(255 BYTE) NULL ,
"WZBM" VARCHAR2(255 BYTE) NULL ,
"PH" VARCHAR2(255 BYTE) NULL ,
"GG" VARCHAR2(255 BYTE) NULL ,
"CYBZ" VARCHAR2(255 BYTE) NULL ,
"JLDW" VARCHAR2(255 BYTE) NULL,
"SCCJ" VARCHAR2(255 BYTE) NULL ,
"TSSM" VARCHAR2(255 BYTE) NULL ,
"SFJK" VARCHAR2(255 BYTE) NULL ,
"WZJC" VARCHAR2(255 BYTE) NULL ,
"HSL" VARCHAR2(255 BYTE) NULL ,
"XS" VARCHAR2(255 BYTE) NULL ,
"SJBM" VARCHAR2(255 BYTE) NULL ,
"WZMC" VARCHAR2(255 BYTE) NULL ,
"BMYXJB" VARCHAR2(255 BYTE) NULL ,
"BMZT" VARCHAR2(255 BYTE) NULL ,
"BMLX" VARCHAR2(255 BYTE) NULL ,
"BMDJ" VARCHAR2(255 BYTE) NULL,
"WZFL" VARCHAR2(255 BYTE) NULL
);

/*电子元器件*/
DROP TABLE "TMEELECOMPONENTSPARTLINK";
CREATE TABLE "TMEELECOMPONENTSPARTLINK" (
"GWKEYID" VARCHAR2(255 BYTE) NOT NULL ,
"TECHNICSMATERIALENTRIESID" VARCHAR2(255 BYTE) NULL ,
"WZMC" VARCHAR2(255 BYTE) NULL ,
"XHGG" VARCHAR2(255 BYTE) NULL ,
"ZLDJ" VARCHAR2(255 BYTE) NULL ,
"SCCJ" VARCHAR2(255 BYTE) NULL ,
"JLDW" VARCHAR2(255 BYTE) NULL ,
"ZGF" VARCHAR2(255 BYTE) NULL ,
"XXGF" VARCHAR2(255 BYTE) NULL ,
"XH" VARCHAR2(255 BYTE) NULL ,
"FZXS" VARCHAR2(255 BYTE) NULL ,
"WXCC" VARCHAR2(255 BYTE) NULL ,
"ZYTJ" VARCHAR2(255 BYTE) NULL ,
"FJXY" VARCHAR2(255 BYTE) NULL ,
"TSSM" VARCHAR2(255 BYTE) NULL ,
"SFJK" VARCHAR2(255 BYTE) NULL ,
"KFSZBTID" VARCHAR2(255 BYTE) NULL ,
"KFSZBSEE" VARCHAR2(255 BYTE) NULL ,
"XNCS" VARCHAR2(255 BYTE) NULL ,
"SFJDMG" VARCHAR2(255 BYTE) NULL ,
"JDMGDJ" VARCHAR2(255 BYTE) NULL ,
"SMDJ" VARCHAR2(255 BYTE) NULL ,
"SJBM" VARCHAR2(255 BYTE) NULL ,
"WZBM" VARCHAR2(255 BYTE) NULL ,
"WZJC" VARCHAR2(255 BYTE) NULL ,
"BMYXJB" VARCHAR2(255 BYTE) NULL ,
"BMZT" VARCHAR2(255 BYTE) NULL ,
"BMLX" VARCHAR2(255 BYTE) NULL ,
"BMDJ" VARCHAR2(255 BYTE) NULL,
"WZFL" VARCHAR2(255 BYTE) NULL
);



/*金属材料*/
-- ----------------------------
-- Table structure for TMEMETALLICPARTLINK
-- ----------------------------
DROP TABLE "TMEMETALLICPARTLINK";
CREATE TABLE "TMEMETALLICPARTLINK" (
"GWKEYID" VARCHAR2(255 BYTE) NOT NULL ,
"TECHNICSMATERIALENTRIESID" VARCHAR2(255 BYTE) NULL ,
"WZMC" VARCHAR2(255 BYTE) NULL ,
"PH" VARCHAR2(255 BYTE) NULL ,
"GG" VARCHAR2(255 BYTE) NULL ,
"GYZT" VARCHAR2(255 BYTE) NULL ,
"CYBZ" VARCHAR2(255 BYTE) NULL ,
"JLDW" VARCHAR2(255 BYTE) NULL,
"GYDW" VARCHAR2(255 BYTE) NULL,
"PZGGBZ" VARCHAR2(255 BYTE) NULL ,
"JD" VARCHAR2(255 BYTE) NULL ,
"ZLTZ" VARCHAR2(255 BYTE) NULL ,
"SCCJ" VARCHAR2(255 BYTE) NULL ,
"WZJC" VARCHAR2(255 BYTE) NULL ,
"TSSM" VARCHAR2(255 BYTE) NULL ,
"SFJK" VARCHAR2(255 BYTE) NULL ,
"HSL" VARCHAR2(255 BYTE) NULL ,
"XS" VARCHAR2(255 BYTE) NULL ,
"SJBM" VARCHAR2(255 BYTE) NULL ,
"WZBM" VARCHAR2(255 BYTE) NULL ,
"BMYXJB" VARCHAR2(255 BYTE) NULL ,
"BMZT" VARCHAR2(255 BYTE) NULL ,
"BMLX" VARCHAR2(255 BYTE) NULL ,
"BMDJ" VARCHAR2(255 BYTE) NULL,
"WZFL" VARCHAR2(255 BYTE) NULL
);

/*非金属材料*/
-- ----------------------------
-- Table structure for TMENONMETALLICPARTLINK
-- ----------------------------
DROP TABLE "TMENONMETALLICPARTLINK";
CREATE TABLE "TMENONMETALLICPARTLINK" (
"GWKEYID" VARCHAR2(255 BYTE) NOT NULL ,
"TECHNICSMATERIALENTRIESID" VARCHAR2(255 BYTE) NULL ,
"WZMC" VARCHAR2(255 BYTE) NULL ,
"PH" VARCHAR2(255 BYTE) NULL ,
"GG" VARCHAR2(255 BYTE) NULL ,
"CYBZ" VARCHAR2(255 BYTE) NULL ,
"JLDW" VARCHAR2(255 BYTE) NULL ,
"GYDW" VARCHAR2(255 BYTE) NULL ,
"SCCJ" VARCHAR2(255 BYTE) NULL ,
"TSSM" VARCHAR2(255 BYTE) NULL ,
"SFJK" VARCHAR2(255 BYTE) NULL ,
"WZJC" VARCHAR2(255 BYTE) NULL ,
"HSL" VARCHAR2(255 BYTE) NULL ,
"XS" VARCHAR2(255 BYTE) NULL ,
"SJBM" VARCHAR2(255 BYTE) NULL ,
"WZBM" VARCHAR2(255 BYTE) NULL ,
"BMYXJB" VARCHAR2(255 BYTE) NULL ,
"BMZT" VARCHAR2(255 BYTE) NULL ,
"BMLX" VARCHAR2(255 BYTE) NULL ,
"BMDJ" VARCHAR2(255 BYTE) NULL,
"WZFL" VARCHAR2(255 BYTE) NULL
);

/*标准件*/
-- ----------------------------
-- Table structure for TMESTANDPARTLINK
-- ----------------------------
DROP TABLE "TMESTANDPARTLINK";
CREATE TABLE "TMESTANDPARTLINK" (
"GWKEYID" VARCHAR2(255 BYTE) NOT NULL ,
"TECHNICSMATERIALENTRIESID" VARCHAR2(255 BYTE) NULL ,
"WZMC" VARCHAR2(255 BYTE) NULL ,
"GG" VARCHAR2(255 BYTE) NULL ,
"BZH" VARCHAR2(255 BYTE) NULL ,
"JXXNDJ" VARCHAR2(255 BYTE) NULL ,
"JLDW" VARCHAR2(255 BYTE) NULL ,
"CL" VARCHAR2(255 BYTE) NULL ,
"BMCL" VARCHAR2(255 BYTE) NULL ,
"RCL" VARCHAR2(255 BYTE) NULL ,
"SCCJ" VARCHAR2(255 BYTE) NULL ,
"CPXS" VARCHAR2(255 BYTE) NULL ,
"CPDJ" VARCHAR2(255 BYTE) NULL ,
"NBXS" VARCHAR2(255 BYTE) NULL ,
"TSSM" VARCHAR2(255 BYTE) NULL ,
"SFJK" VARCHAR2(255 BYTE) NULL ,
"SJBM" VARCHAR2(255 BYTE) NULL ,
"WZBM" VARCHAR2(255 BYTE) NULL ,
"WZJC" VARCHAR2(255 BYTE) NULL ,
"BMYXJB" VARCHAR2(255 BYTE) NULL ,
"BMZT" VARCHAR2(255 BYTE) NULL ,
"BMLX" VARCHAR2(255 BYTE) NULL ,
"BMDJ" VARCHAR2(255 BYTE) NULL,
"WZFL" VARCHAR2(255 BYTE) NULL
);

/*工艺物资名称link*/
-- ----------------------------
-- Table structure for TECHNICSMATERIALLINK
-- ----------------------------
DROP TABLE "TECHNICSMATERIALLINK";
CREATE TABLE "TECHNICSMATERIALLINK" (
"GWKEYID" VARCHAR2(255 BYTE) NOT NULL ,
"TECHNICSMATERIALID" VARCHAR2(255 BYTE) NULL ,
"DICTIONARYID" VARCHAR2(255 BYTE) NULL ,
"DESCRIPTION" VARCHAR2(2000 BYTE) NULL ,
"TMCREATETIME" VARCHAR2(255 BYTE) NULL ,
"TMCREATOR" VARCHAR2(255 BYTE) NULL 
);

/*未申请编码的物资*/
DROP TABLE "TECHNICAQUOTANUMBER";
CREATE TABLE "TECHNICAQUOTANUMBER" (
  "GWKEYID" VARCHAR2(255 BYTE) NOT NULL ,
  "TECHNICSOID" VARCHAR2(255 BYTE) ,
  "QUOTANUMBER" VARCHAR2(255 BYTE) ,
  "TECHMATERIALTYPE" VARCHAR2(255 BYTE) ,
  "TMCREATETIME" VARCHAR2(255 BYTE) ,
  "TMCREATOR" VARCHAR2(255 BYTE)
);
-- ----------------------------
-- Indexes structure for table TMECOMPOUNDMATERIALPARTLINK
-- ----------------------------

-- ----------------------------
-- Checks structure for table TMECOMPOUNDMATERIALPARTLINK
-- ----------------------------
ALTER TABLE "TMECOMPOUNDMATERIALPARTLINK" ADD CHECK ("GWKEYID" IS NOT NULL);
ALTER TABLE "TMECOMPOUNDMATERIALPARTLINK" ADD CHECK ("GWKEYID" IS NOT NULL);
ALTER TABLE "TMECOMPOUNDMATERIALPARTLINK" ADD CHECK ("GWKEYID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table TMECOMPOUNDMATERIALPARTLINK
-- ----------------------------
ALTER TABLE "TMECOMPOUNDMATERIALPARTLINK" ADD PRIMARY KEY ("GWKEYID");

-- ----------------------------
-- Indexes structure for table TMEELECOMPONENTSPARTLINK
-- ----------------------------

-- ----------------------------
-- Checks structure for table TMEELECOMPONENTSPARTLINK
-- ----------------------------
ALTER TABLE "TMEELECOMPONENTSPARTLINK" ADD CHECK ("GWKEYID" IS NOT NULL);
ALTER TABLE "TMEELECOMPONENTSPARTLINK" ADD CHECK ("GWKEYID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table TMEELECOMPONENTSPARTLINK
-- ----------------------------
ALTER TABLE "TMEELECOMPONENTSPARTLINK" ADD PRIMARY KEY ("GWKEYID");

-- ----------------------------
-- Indexes structure for table TMEELEMACHINEPARTLINK
-- ----------------------------

-- ----------------------------
-- Checks structure for table TMEELEMACHINEPARTLINK
-- ----------------------------
ALTER TABLE "TMEELEMACHINEPARTLINK" ADD CHECK ("GWKEYID" IS NOT NULL);
ALTER TABLE "TMEELEMACHINEPARTLINK" ADD CHECK ("GWKEYID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table TMEELEMACHINEPARTLINK
-- ----------------------------
ALTER TABLE "TMEELEMACHINEPARTLINK" ADD PRIMARY KEY ("GWKEYID");

-- ----------------------------
-- Indexes structure for table TMEEXPDEVICEPARTLINK
-- ----------------------------

-- ----------------------------
-- Checks structure for table TMEEXPDEVICEPARTLINK
-- ----------------------------
ALTER TABLE "TMEEXPDEVICEPARTLINK" ADD CHECK ("GWKEYID" IS NOT NULL);
ALTER TABLE "TMEEXPDEVICEPARTLINK" ADD CHECK ("GWKEYID" IS NOT NULL);
ALTER TABLE "TMEEXPDEVICEPARTLINK" ADD CHECK ("GWKEYID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table TMEEXPDEVICEPARTLINK
-- ----------------------------
ALTER TABLE "TMEEXPDEVICEPARTLINK" ADD PRIMARY KEY ("GWKEYID");

-- ----------------------------
-- Indexes structure for table TMEMETALLICPARTLINK
-- ----------------------------

-- ----------------------------
-- Checks structure for table TMEMETALLICPARTLINK
-- ----------------------------
ALTER TABLE "TMEMETALLICPARTLINK" ADD CHECK ("GWKEYID" IS NOT NULL);
ALTER TABLE "TMEMETALLICPARTLINK" ADD CHECK ("GWKEYID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table TMEMETALLICPARTLINK
-- ----------------------------
ALTER TABLE "TMEMETALLICPARTLINK" ADD PRIMARY KEY ("GWKEYID");

-- ----------------------------
-- Indexes structure for table TMENONMETALLICPARTLINK
-- ----------------------------

-- ----------------------------
-- Checks structure for table TMENONMETALLICPARTLINK
-- ----------------------------
ALTER TABLE "TMENONMETALLICPARTLINK" ADD CHECK ("GWKEYID" IS NOT NULL);
ALTER TABLE "TMENONMETALLICPARTLINK" ADD CHECK ("GWKEYID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table TMENONMETALLICPARTLINK
-- ----------------------------
ALTER TABLE "TMENONMETALLICPARTLINK" ADD PRIMARY KEY ("GWKEYID");

-- ----------------------------
-- Indexes structure for table TMESTANDPARTLINK
-- ----------------------------

-- ----------------------------
-- Checks structure for table TMESTANDPARTLINK
-- ----------------------------
ALTER TABLE "TMESTANDPARTLINK" ADD CHECK ("GWKEYID" IS NOT NULL);
ALTER TABLE "TMESTANDPARTLINK" ADD CHECK ("GWKEYID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table TMESTANDPARTLINK
-- ----------------------------
ALTER TABLE "TMESTANDPARTLINK" ADD PRIMARY KEY ("GWKEYID");
-- ----------------------------
-- Indexes structure for table TECHNICSMATERIALLINK
-- ----------------------------

-- ----------------------------
-- Checks structure for table TECHNICSMATERIALLINK8
-- ----------------------------
ALTER TABLE "TECHNICSMATERIALLINK" ADD CHECK ("GWKEYID" IS NOT NULL);
ALTER TABLE "TECHNICSMATERIALLINK" ADD CHECK ("TECHNICSMATERIALID" IS NOT NULL);
ALTER TABLE "TECHNICSMATERIALLINK" ADD CHECK ("DICTIONARYID" IS NOT NULL);
-- ----------------------------
-- Primary Key structure for table TECHNICSMATERIALLINK
-- ----------------------------
ALTER TABLE "TECHNICSMATERIALLINK" ADD PRIMARY KEY ("TECHNICSMATERIALID","DICTIONARYID");
