
/*机电材料*/
-- ----------------------------
-- Table structure for TMEELEMACHINEPARTLINK
-- ----------------------------
DROP TABLE "TMEELEMACHINEPARTLINK";
CREATE TABLE "TMEELEMACHINEPARTLINK" (
"GWKEYID" VARCHAR2(255 BYTE) NOT NULL ,
"TECHNICSMATERIALENTRIESID" VARCHAR2(255 BYTE) NULL ,
"BMDJ" VARCHAR2(255 BYTE) NULL ,
"WZMC" VARCHAR2(255 BYTE) NULL ,
"XHGG" VARCHAR2(255 BYTE) NULL ,
"JLDW" VARCHAR2(255 BYTE) NULL ,
"SFJK" VARCHAR2(255 BYTE) NULL ,
"BZH" VARCHAR2(255 BYTE) NULL,
"PH" VARCHAR2(255 BYTE) NULL ,
"SCCJ" VARCHAR2(255 BYTE) NULL ,
"XNCS" VARCHAR2(255 BYTE) NULL ,
"TSSM" VARCHAR2(255 BYTE) NULL ,
"BMZT" VARCHAR2(255 BYTE) NULL ,
"SJBM" VARCHAR2(255 BYTE) NULL ,
"WZBM" VARCHAR2(255 BYTE) NULL ,
"WZFL" VARCHAR2(255 BYTE) NULL
);

/*火工品*/
-- ----------------------------
-- Table structure for TMEEXPDEVICEPARTLINK
-- ----------------------------
DROP TABLE "TMEEXPDEVICEPARTLINK";
CREATE TABLE "TMEEXPDEVICEPARTLINK" (
"GWKEYID" VARCHAR2(255 BYTE) NOT NULL ,
"TECHNICSMATERIALENTRIESID" VARCHAR2(255 BYTE) NULL ,
"BMDJ" VARCHAR2(255 BYTE) NULL ,
"WZMC" VARCHAR2(255 BYTE) NULL ,
"CPDH" VARCHAR2(255 BYTE) NULL ,
"JLDW" VARCHAR2(255 BYTE) NULL ,
"BZH" VARCHAR2(255 BYTE) NULL ,
"SCCJ" VARCHAR2(255 BYTE) NULL ,
"ZL" VARCHAR2(255 BYTE) NULL ,
"ZCSM" VARCHAR2(255 BYTE) NULL ,
"TNT" VARCHAR2(255 BYTE) NULL ,
"XNCS" VARCHAR2(255 BYTE) NULL ,
"WZBM" VARCHAR2(255 BYTE) NULL ,
"TSSM" VARCHAR2(255 BYTE) NULL ,
"BMZT" VARCHAR2(255 BYTE) NULL ,
"SJBM" VARCHAR2(255 BYTE) NULL ,
"WZFL" VARCHAR2(255 BYTE) NULL
);