com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Frock=/Default/\u5DE5\u88C5
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Frock|casc.sast.812.SpecFrog=/Default/\u5DE5\u88C5/\u4E13\u4E1A\u5DE5\u88C5
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Frock|casc.sast.812.CommonFrog=/Default/\u5DE5\u88C5/\u901A\u7528\u5DE5\u88C5
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Tool=/Default/\u5DE5\u5177
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Knife=/Default/\u5200\u5177
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Measure=/Default/\u91CF\u5177
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Equipment=/Default/\u8BBE\u5907
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Equipment|casc.sast.812.\u8F66\u5E8A=/Default/\u8BBE\u5907/\u8F66\u5E8A
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Equipment|casc.sast.812.\u78E8\u5E8A=/Default/\u8BBE\u5907/\u78E8\u5E8A
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Equipment|casc.sast.812.\u5228\u5E8A=/Default/\u8BBE\u5907/\u5228\u5E8A
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Equipment|casc.sast.812.\u94E3\u5E8A=/Default/\u8BBE\u5907/\u94E3\u5E8A
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Equipment|casc.sast.812.\u7EBF\u5207\u5272=/Default/\u8BBE\u5907/\u7EBF\u5207\u5272
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Equipment|casc.sast.812.\u94BB\u5E8A=/Default/\u8BBE\u5907/\u94BB\u5E8A
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Equipment|casc.sast.812.\u9557\u5E8A=/Default/\u8BBE\u5907/\u9557\u5E8A
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Equipment|casc.sast.812.\u6EDA\u9F7F\u673A=/Default/\u8BBE\u5907/\u6EDA\u9F7F\u673A
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Equipment|casc.sast.812.\u710A\u63A5\u8BBE\u5907=/Default/\u8BBE\u5907/\u710A\u63A5\u8BBE\u5907
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Equipment|casc.sast.812.\u52A0\u5DE5\u4E2D\u5FC3=/Default/\u8BBE\u5907/\u52A0\u5DE5\u4E2D\u5FC3
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Equipment|casc.sast.812.\u7535\u7F06\u5265\u76AE\u673A=/Default/\u8BBE\u5907/\u7535\u7F06\u5265\u76AE\u673A
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Equipment|casc.sast.812.\u6CE2\u5CF0\u710A\u673A=/Default/\u8BBE\u5907/\u6CE2\u5CF0\u710A\u673A
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Equipment|casc.sast.812.\u6C34\u6E05\u6D17\u673A=/Default/\u8BBE\u5907/\u6C34\u6E05\u6D17\u673A
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Equipment|casc.sast.812.\u70ED\u538B\u673A=/Default/\u8BBE\u5907/\u70ED\u538B\u673A
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Equipment|casc.sast.812.\u771F\u7A7A\u8BBE\u5907=/Default/\u8BBE\u5907/\u771F\u7A7A\u8BBE\u5907
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Equipment|casc.sast.812.\u70D8\u7BB1=/Default/\u8BBE\u5907/\u771F\u7A7A\u8BBE\u5907
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Equipment|casc.sast.812.\u8868\u5904\u8BBE\u5907=/Default/\u8BBE\u5907/\u8868\u5904\u8BBE\u5907
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Equipment|casc.sast.812.\u5316\u5B66\u6C89\u94DC\u751F\u4EA7\u7EBF=/Default/\u8BBE\u5907/\u5316\u5B66\u9648\u94DC\u751F\u4EA7\u7EBF
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Equipment|casc.sast.812.\u516D\u8F74\u6570\u63A7\u94BB\u5E8A=/Default/\u8BBE\u5907/\u516D\u8F74\u6570\u63A7\u94BB\u5E8A
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Equipment|casc.sast.812.\u5E73\u884C\u5149\u66DD\u5149\u673A=/Default/\u8BBE\u5907/\u5E73\u884C\u5149\u66DD\u5149\u673A
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Equipment|casc.sast.812.\u70ED\u538B\u7F50=/Default/\u8BBE\u5907/\u70ED\u538B\u7F50
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.ProceduceName=/Default/\u5DE5\u5E8F\u540D\u79F0
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.Equipment|casc.sast.812.\u5176\u5B83\u8BBE\u5907=/Default/\u8BBE\u5907/\u5176\u5B83\u8BBE\u5907

com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.149.CommonString=/Default/\u5DE5\u827A\u5E38\u7528\u8BED
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.812.CommonString=/Default/\u5DE5\u827A\u5E38\u7528\u8BED

com.ptc.windchill.mpml.resource.MPMPlant=/Default/\u5236\u9020\u5355\u4F4D
com.ptc.windchill.mpml.resource.MPMWorkCenter=/Default/\u5DE5\u4F4D
com.ptc.windchill.mpml.resource.MPMSkill=/Default/\u5DE5\u79CD
com.ptc.windchill.mpml.resource.MPMProcessMaterial=/Default/\u5DE5\u827A\u8F85\u6599
com.ptc.windchill.mpml.resource.MPMProcessMaterial|casc.sast.812.\u7535\u5B50\u6750\u6599=/Default/\u5DE5\u827A\u8F85\u6599
com.ptc.windchill.mpml.resource.MPMProcessMaterial|casc.sast.812.\u975E\u91D1\u5C5E\u6750\u6599\u53CA\u5236\u54C1=/Default/\u5DE5\u827A\u8F85\u6599
com.ptc.windchill.mpml.resource.MPMProcessMaterial|casc.sast.812.\u91D1\u5C5E\u6750\u6599\u53CA\u5236\u54C1=/Default/\u5DE5\u827A\u8F85\u6599
com.ptc.windchill.mpml.resource.MPMProcessMaterial|casc.sast.812.\u91D1\u5C5E\u6750\u6599\u53CA\u5236\u54C1|casc.sast.812.\u91D1\u5C5E\u5236\u54C1=/Default/\u5DE5\u827A\u8F85\u6599
com.ptc.windchill.mpml.resource.MPMProcessMaterial|casc.sast.812.\u91D1\u5C5E\u6750\u6599\u53CA\u5236\u54C1|casc.sast.812.\u94A2\u6750=/Default/\u5DE5\u827A\u8F85\u6599
com.ptc.windchill.mpml.resource.MPMProcessMaterial|casc.sast.812.\u91D1\u5C5E\u6750\u6599\u53CA\u5236\u54C1|casc.sast.812.\u9633\u6781\u6750\u6599=/Default/\u5DE5\u827A\u8F85\u6599

######SOP\u8D44\u6E90\u5BF9\u8C61\u5B58\u50A8\u4F4D\u7F6E\u914D\u7F6E START######
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.149.Parameters=/Default/SOP\u8D44\u6E90/\u5DE5\u827A\u53C2\u6570\u9879\u76EE
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.149.CustomArea=/Default/SOP\u8D44\u6E90/\u5B9A\u5236\u533A\u57DF
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.149.OperationJob=/Default/SOP\u8D44\u6E90/\u64CD\u4F5C\u5C97\u4F4D
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.149.SpecializedType=/Default/SOP\u8D44\u6E90/\u4E13\u4E1A\u7C7B\u522B
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.149.ProceduceName=/Default/SOP\u8D44\u6E90/\u5DE5\u5E8F\u540D\u79F0
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.149.ParametersName=/Default/SOP\u8D44\u6E90/\u53C2\u6570\u9879\u76EE\u540D\u79F0
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.149.MaterialCategory=/Default/SOP\u8D44\u6E90/\u7269\u8D44\u7C7B\u522B
com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.149.OperationName=/Default/SOP\u8D44\u6E90/\u64cd\u4f5c\u540d\u79f0
######SOP\u8D44\u6E90\u5BF9\u8C61\u5B58\u50A8\u4F4D\u7F6E\u914D\u7F6E EDN######

com.ptc.windchill.mpml.resource.MPMTooling|casc.sast.149.Frock=/Default/\u5de5\u88c5