CREATE TABLE GLCIPartLink (
   CIPARTNUMBER VARCHAR2(255) NOT NULL,
   WTPARTNUMBER VARCHAR2(255) NOT NULL,
   CONSTRAINT PK_GLCIPartLink PRIMARY KEY(CIPARTNUMBER, WTPARTNUMBER))
   STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
ENABLE PRIMARY KEY USING INDEX
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
 /