CREATE TABLE GLCILink (
   GLCATALOGNUMBER VARCHAR2(255) NOT NULL,
   GLCATALOGNAME VARCHAR2(255) NOT NULL,
   CIPARTNUMBER VARCHAR2(255) NOT NULL,
   GLSUPPLIERS VARCHAR2(600),
   CONSTRAINT PK_GLCILink PRIMARY KEY(GLCATALOGNUMBER, CIPARTNUMBER, GLCATALOGNAME))
   STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
ENABLE PRIMARY KEY USING INDEX
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
 /
