CREATE INDEX GLCatalog$COMPOSITE20 ON GLCatalog(GLCatalogNumber)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX GLCatalog$COMPOSITE21 ON GLCatalog(GLCatalogName)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
